### ISSUE TITLE
commit_batch to respect 100 entity limit

### ISSUE THREAD

**Issue by crwilcox** [Azure/azure-storage-python#1]
### Description:
Rather than leave it up to the user to decipher this* cryptic error message and implement the 100 entity limitation on batching themselves, it would be great if the library could handle this.

*WindowsAzureBatchOperationError('99:One of the request inputs is not valid.RequestId:*******Time:2015-06-30T20:19:29.9051959Z',)

#### @huguesv commented on 2015-06-30 21:08:08:
> That's an excellent suggestion!

**Comment by jehine-MSFT** [comment]
Hi @coffenbacher,

We have implemented the validation for exceeding 100 table batch operations along with some sweeping changes to the way Table Batching is done in this library. These changes will be released in our next major release.

Thanks for the feedback!

**Comment by coffenbacher** [comment]
Good to know! Thanks!

**Comment by jehine-MSFT** [comment]
Hello @coffenbacher ,

We have released the 0.30 version (#132) which addressed this feature request. If you have issues with the new version in regards to this issue, please reopen it and continue the discussion.

Thanks!
