### ISSUE TITLE
Low BLOB_MAX_CHUNK_DATA_SIZE leads to performance hits for max_connections=1

### ISSUE THREAD

**Issue by crwilcox** [Azure/azure-storage-python#10]
### Description:
When using azure.storage.blobservice.get_blob_to_file, the algorithm will download a 64MB (or smaller) file in one call REST call.

However larger files are chunked in 4MB blocks.  For a 65MB file this would result in 17 calls, which significantly decreases performance.  For my application, changing _BLOB_MAX_CHUNK_DATA_SIZE to be the same as _BLOB_MAX_DATA_SIZE (64MB) improved performance drastically.

Not sure of all use cases to know if this will impact other applications, but if it cannot be hard coded to 64MB, perhaps allowing a chunk_size  argument would help.

#### @huguesv commented on 2015-04-14 22:33:03:
> Thanks for letting us know about this.  Looking at the node storage sdk, it appears that download chunk size may not be limited to 4MB, unless the md5 is requested.  I'll do some testing.

**Comment by jehine-MSFT** [comment]
Hello @Segsfault,

Thanks for the feedback about our download APIs! We are working to improve the perf in all scenarios. For single-threaded downloads we have a design that will greatly improve perf and hope to complete implementation in time for our next major release. Additionally, we are in the process of finding a solution to better handle multi-threaded download.

Thanks again!

**Comment by emgerner-msft** [comment]
In 0.30.0 single threaded downloads will not be chunked by default whatsoever. This should always improve perf in this case as there is only a single network call made.

Multi threaded downloads (ie max_connections>1) will be chunked by the previous rules. First, a get properties will give us the size of the blob. Then, under 64MB will be done in a single get and over 64MB chunked into 4MB pieces which the various threads can download simulatenously. The variables for these limits have been renamed (MAX_SINGLE_GET_SIZE, MAX_CHUNK_GET_SIZE) but remain changeable.
