### ISSUE TITLE
Content-MD5 header does not validate properly for blob uploads in chunks

### ISSUE THREAD

**Issue by crwilcox** [Azure/azure-storage-python#11]
### Description:
I would like to use MD5 validation to ensure my data survives transport when I upload blobs to Azure storage. Per the documentation, I supply a content-MD5 header along with my upload, so that the service validates the incoming file against this header.

This works great for small files. **But once I try to upload files that require chunked uploads -- e.g. I'm currently trying to upload a 1GB file -- the validation is always unsuccessful.** I'm using `BlobService.put_block_blob_from_path(...)` for the upload.

For reference, here is how I calculate the MD5 locally and pass it along with my upload.

```
# md5 generation for validating uploads
import hashlib
def md5_for_file(f, block_size=2**20):
    md5 = hashlib.md5()
    while True:
        data = f.read(block_size)
        if not data:
            break
        md5.update(data)
    return md5.digest().encode('base64')[:-1] 
    
# do the uploads, with file path p
for p in paths:
    blob_name = path_leaf(p)
    original_md5 = md5_for_file(open(p, 'rb'))
    blob_service.put_block_blob_from_path(storage_container_name, blob_name, p, content_md5=original_md5) # specify md5 to do an md5 check automatically
```

I get a WindowsAzureError when I run the above, due to the MD5 not validating properly:

```
Traceback (most recent call last):
  File "azureUpload.py", line 44, in <module>
    blob_service.put_block_blob_from_path(storage_container_name, blob_name, p, content_md5=original_md5) # specify md5 to do an md5 check automatically
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/blobservice.py", line 764, in put_block_blob_from_path
    progress_callback)
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/blobservice.py", line 861, in put_block_blob_from_file
    x_ms_lease_id)
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/blobservice.py", line 696, in put_blob
    self._perform_request(request)
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/storageclient.py", line 150, in _perform_request
    _storage_error_handler(ex)
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/__init__.py", line 889, in _storage_error_handler
    return _general_error_handler(http_error)
  File "/usr/local/lib/python2.7/dist-packages/azure/__init__.py", line 931, in _general_error_handler
    http_error.respbody.decode('utf-8'))
azure.WindowsAzureError
```

# The issue

My local MD5 computation isn't the issue -- I've checked it against Azure with small uploads, and it produces the same result as md5sum for my 1GB file.

**How should big files be uploaded with MD5 validation?** It seems that the API should be changed so that MD5 is computed for each chunk.

# How to reproduce

Create a >64MB file using `dd if=/dev/urandom of=65M.random bs=1M count=65`, then upload it with the code above. You get the same traceback as I did.

But if you chop 20MB off that using `dd if=/dev/urandom of=45M.random bs=1M count=45`, we won't trigger chunking, and the upload succeeds, along with MD5 validation.

If you remove MD5 validation (don't specify `content_md5` parameter), both uploads succeed.

Thus, the issue lies with MD5 validation with files that trigger chunking.

#### @huguesv commented on 2015-01-05 15:57:16:
> Thanks for letting us know about this issue.

The documentation for Put Block List REST API says:
"Note that this header is associated with the request content, and not with the content of the blob itself."

So passing in the MD5 of the whole blob to Put Block List is definitely the wrong thing to do.

We should calculate the MD5 for each chunk and pass it to Put Block (Put Blob in the case of no chunking), if the user wants validation.  The content\_md5 parameter should be changed to a Boolean, matching the behavior of the useTransactionalMD5 parameter used in Node.js SDK:
https://github.com/Azure/azure-storage-node/blob/master/lib/services/blob/blobservice.js

All Page Blob and Block Blob APIs should be reviewed for this, both upload and download.

#### @maximz commented on 2015-01-06 18:44:13:
> @huguesv Thanks for the update. Let me know if there's any further way I can help. (For now, I've just disabled MD5 verification in my code)

**Comment by traxair** [comment]
So, how is this one going?

**Comment by emgerner-msft** [comment]
We're currently working to bring the entire library up to the newest REST version with all of the released features from the service -- please see the dev branch for this work. Once that is in preview, we will start working on a variety of smaller features such as this one. For now, as long as you're using https you should get the same body validation as if we're calculating MD5 per chunk.

**Comment by emgerner-msft** [comment]
As of [0.32.0](https://github.com/Azure/azure-storage-python/releases/tag/v0.32.0) the library supports automatic calculation of transactional MD5s for upload and download. Transactional MD5 is more versatile than stored MD5 as it is computed by the server on the actual stored data. It does not have the issue where the stored content MD5 can get out of date as the blob is updated. Simply use the validate_content MD5 to enable this for the upload of any blob type and blob download. Note that using MD5 validation has a performance penalty and HTTPS already protects against bitflips on the wire so this feature should be used primarily if HTTP is used.

The library does not build in calculation of the total blob MD5 or validate it on download as this historically in other libraries causes issues with the stored MD5 being out of date with the content. However, the user may still set and retrieve this value using the content_settings. Note that by default stored MD5 not returned by the download APIs unless particular provisions are made as described in the get method docs. It can still be retrieved by getting the blob properties.

**Comment by davidbetz** [comment]
Are you sure you can set your own custom MD5 at the time point of this commit?

We have multiple long-standing .NET applications in production where we actively use the "```Content-MD5```" header to set a custom hash (md5(content + relative file name), to detect renames). In trying to make a Python client for the same system, I'm getting the impression from "The MD5 value specified in the request did not match with the MD5 value calculated by the server." that this is computed on the server now. That's the message that comes from using "```ContentSettings(content_md5=our_custom_hash)```". Server-side computation would be disastrous; our custom md5 is NOT based on the content alone; it will never match the server-side computation on content. Our system works fine in .NET, but the Python port seems blocked.

Full message: 
```
<?xml version="1.0" encoding="utf-8"?><Error><Code>Md5Mismatch</Code><Message>The MD5 value specified in the request did not match with the MD5 value calculated by the server.
RequestId:e0e79dec-0001-0007-4641-e9b1f5000000
Time:2016-07-29T02:31:38.3965309Z</Message><UserSpecifiedMd5>pE0gS4+iILR9bFjtIcwSiA==</UserSpecifiedMd5><ServerCalculatedMd5>kS7IA7LOSeSlQQaNSVq1cA==</ServerCalculatedMd5></Error>
```
