### ISSUE TITLE
AttributeError: 'BlockBlobService' object has no attribute 'create_block_blob_from_path'

### ISSUE THREAD

**Issue by kaldown** [Azure/azure-storage-python#134]
Accocrding this manual I shoud use thise pice of code:

```
from azure.storage.blob import ContentSettings
block_blob_service.create_block_blob_from_path(
    'mycontainer',
    'myblockblob',
    'sunset.png',
    content_settings=ContentSettings(content_type='image/png')
            )
```
But got this error:

```
AttributeError: 'BlockBlobService' object has no attribute 'create_block_blob_from_path'
```

Tried from `git`, as well as from `pip`

`pip install azure-storage`

manual - https://azure.microsoft.com/en-in/documentation/articles/storage-python-how-to-use-blob-storage/

**Comment by jehine-MSFT** [comment]
Hello @kaldown,

With the new version, you need to create a block blob service and then call create_blob_from_path not create_block_blob_from_path. Please see the usage samples:

https://github.com/Azure/azure-storage-python/blob/master/samples/blob/block_blob_usage.py

Thanks!

**Comment by jehine-MSFT** [comment]
We are working to correct that issue in the documentation.

Thank you for finding this error!

**Comment by jehine-MSFT** [comment]
Hello @kaldown ,

We have addressed the issue with the content for the blog post.

Thank you bringing this to our attention and please do provide us feedback on how you like the new library!

Updated: https://azure.microsoft.com/en-us/documentation/articles/storage-python-how-to-use-blob-storage/
