### ISSUE TITLE
BlobService.set_container_acl optional param not documented

### ISSUE THREAD

**Issue by crwilcox** [Azure/azure-storage-python#14]
### Description:
`signed_identifiers` is also optional, but not documented as so.

![image](https://cloud.githubusercontent.com/assets/159209/3784443/70dba876-19b8-11e4-8f74-8ce55049f235.png)

**Comment by jehine-MSFT** [comment]
We have fix the documentation for set_container_acl and will be releasing this with our next major release.
Thanks for the feedback!

**Comment by jehine-MSFT** [comment]
Hello @ahmetalpbalkan ,

We have released the 0.30 version (#132) which addressed this feature request. If you have issues with the new version in regards to this issue, please reopen it and continue the discussion.

Thanks!
