### ISSUE TITLE
Get/Set metadata story is a bummer

### ISSUE THREAD

**Issue by emgerner-msft** [Azure/azure-storage-python#141]
The following code should 'just work', in my opinion:
metadata = blob_service.get_container_metadata(state)
blob_service.set_container_metadata(state, metadata)

What I am expecting to happen here is that I retrieve the metadata, and then re-write it. At the moment this isn't possible and returns with the following error:
azure.common.AzureHttpError: The metadata specified is invalid. It has characters that are not permitted.
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidMetadata</Code><Message>The metadata specified is invalid. It has characters that are not permitted.
RequestId:a91a1861-0001-0067-3cf0-7b83d1000000
Time:2016-03-11T23:47:14.5882290Z</Message></Error>

This EXACT scenario isn't required/necessary, but it is the crux of the problem where I'd simply like to 'append' metadata to existing metadata. In order to work around this I suspect (unless someone points out otherwise) I will need to strip out the x-ms-meta- prefix out of the keys and THEN I can resubmit. That's a lot of extra cycles for the developer, as well as the computer that do nothing but get in the way.

**Comment by emgerner-msft** [comment]
We completely agree that this is a pain! So, we fixed it in our [library revamp](https://github.com/Azure/azure-storage-python/issues/132) along with a bunch of other usability concerns. The exact code you wrote above should work exactly as expected as of version 0.30.0. If you'd like, [here's a sample](https://github.com/Azure/azure-storage-python/blob/master/samples/blob/container_usage.py#L96) as well.

As a result of many of these usability changes, 0.30.0 is a relatively breaking release. We've tried to provide a variety of docs to help upgrade (all linked to in our revamp notice above), but please feel free to open issues if you have questions, feedback, or other concerns.

**Comment by bryanar** [comment]
*teary eyed* It's ... beautiful! Thank you! (I updated to 0.30 and it works fantastically)

**Comment by emgerner-msft** [comment]
Haha, thanks, glad you're happy! Will close the issue then.
