### ISSUE TITLE
Get the blob URL after 'create_blob_from_path'

### ISSUE THREAD

**Issue by FabienLavocat** [Azure/azure-storage-python#142]
That would be great if the functions **create_blob_from_path**, **create_blob_from_stream**, **create_blob_from_bytes** could return the Blob URL.

**Comment by emgerner-msft** [comment]
If you want to get a well-formed URL, it should be easy enough with [make_blob_url](https://github.com/Azure/azure-storage-python/blob/master/azure/storage/blob/baseblobservice.py#L172). This doesn't make a network call or anything fancy, so it should be very fast. This function also gives you nice options like choosing whether or not to include a SAS token. Does this function meet your needs, and if not, could you clarify further what you're looking for?

**Comment by FabienLavocat** [comment]
You're right, I can use make_blob_url directly after the call to create_blob_from_path.
Thanks!
