### ISSUE TITLE
Return x-ms-request-id from storage service query_entities

### ISSUE THREAD

**Issue by crwilcox** [Azure/azure-storage-python#15]
### Description:
For diagnostics, in _convert_response_to_feeds, add something like this:
```
if 'x-ms-request-id' in name:
            setattr(feeds, 'x_ms_request_id', value)
```

**Comment by jehine-MSFT** [comment]
We plan to expose a way for clients to set and access the request-id as apart of our next major release.

Thanks for the feedback!

**Comment by emgerner-msft** [comment]
As of [0.32.0](https://github.com/Azure/azure-storage-python/releases/tag/v0.32.0) the library automatically sends x-ms-request-id with every request. It also supports setting request and response callbacks to read and modify the HTTP requests and responses as they are made. This allows both reading or overriding the request id value. See the [samples](https://github.com/Azure/azure-storage-python/blob/master/samples/advanced/client.py#L78) for more information on these callbacks.
