### ISSUE TITLE
the package is not working on pypy3

### ISSUE THREAD

**Issue by bonisbal** [Azure/azure-storage-python#157]
```
>>>> import azure.storage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/pypy3/2.4.0/libexec/site-packages/azure/storage/__init__.py", line 21, in <module>
    from .models import (
  File "/usr/local/Cellar/pypy3/2.4.0/libexec/site-packages/azure/storage/models.py", line 20, in <module>
    from collections.abc import Iterable
ImportError: No module named collections.abc
```

**Comment by emgerner-msft** [comment]
What version of Python are you using?

**Comment by abdulito** [comment]
I have a similar issue, this happens when trying to install "azure" again on an existing installation. Here is how to reproduce:

```
sudo pip install azure --upgrade

sudo pip install azure --upgrade --force-reinstall
```

And please note that this is not related to the older version of azure that requires uninstall before upgrading.

**Comment by abdulito** [comment]
As a workaround here is what i do

```
sudo rm -rf /usr/local/lib/python2.7/dist-packages/azure*
sudo rm -rf /usr/local/lib/python2.7/site-packages/azure*

sudo pip install azure
```

**Comment by huguesv** [comment]
Looking at http://doc.pypy.org/en/latest/release-pypy3-2.4.0.html, it looks like that version of pypy is based on Python 3.2, which is not supported by the SDK (2.7 or 3.3+ only).  `collections.abc` was new in 3.3: https://docs.python.org/3.3/library/collections.abc.html

**Comment by lmazuel** [comment]
However, the ABC classes were moved in `collections.abc` in 3.3, before there was in `collections` directly. It's still the case for Python 2.7, it's why the code of `models` do:
```python
if sys.version_info < (3,):
    from collections import Iterable
    _unicode_type = unicode
else:
    from collections.abc import Iterable
    _unicode_type = str
```

If you look at the code in Python 3.5, `from collections import Iterable` still work
https://hg.python.org/cpython/file/3.5/Lib/collections/__init__.py
```python
# For backwards compatibility, continue to make the collections ABCs
# available through the collections module.
from _collections_abc import *
import _collections_abc
__all__ += _collections_abc.__all__
```

Maybe a more compatible way should be to try:
```
try: # Python 3.4 and after
   from collections.abc import Iterable
except ImportError: # Works for Python 2.7 and maybe some other interpreter
   from collections import Iterable
```

Important: I do NOT say that this is enough for Storage to work on PyPy. I just speak about this particular import problem.

**Comment by emgerner-msft** [comment]
We definitely can solve this particular import problem. However, the storage library is not tested with 3.2, and from talking to @huguesv there a likely more problems which are more subtle. I'm wondering if it's almost better not to fix this so its very obvious the version won't work rather than try to debug more subtle problems.

**Comment by lmazuel** [comment]
Looking at the PyPy [download page](http://pypy.org/download.html):
* the Python 2.7 compatible release — PyPy 5.0.1
* the Python 3.2.5 compatible release — PyPy3 2.4.0

So, yes I think you are right, we do not support Python 3 if not at least 3.3, so direct consequence is that we do not support PyPy3 2.4.0.
