### ISSUE TITLE
Authentication Errors when trying to list containers with an account SAS

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-storage-python#159]
I've created the following code which illustrates and simplifies how I'm using the SDK:

```Python
from datetime import datetime

from azure.storage import CloudStorageAccount
from azure.storage.blob import BlockBlobService
from azure.storage.models import ResourceTypes, Services, AccessPolicy
from azure.storage.blob.models import ContainerPermissions, PublicAccess

ACCOUNT_KEY = "XXX"
ACCOUNT_NAME = "NAME"

csa = CloudStorageAccount(account_name=ACCOUNT_NAME, account_key=ACCOUNT_KEY)
    
services = Services(blob=True, queue=True, table=True, file=True)
resource_types = ResourceTypes(service=True, container=True, object=True)
permission = ContainerPermissions(read=True, write=True, delete=True, list=True)
date_format = '%Y-%m-%dT%H:%MZ'
expiry = datetime.strptime('2017-01-01T00:00Z', date_format)

sas_token = csa.generate_shared_access_signature(services, resource_types, permission, expiry)
print('\n===Generated SAS Token ===')
print(sas_token)

bbs = BlockBlobService(account_name=ACCOUNT_NAME,sas_token=sas_token)
results = bbs.list_containers()
print('\n=== RESULTS ===')
print(results)
```

I want to create an account SAS that lets me access anything with all permissions. For this script, I had to make a small change to line 665 in `sharedaccesssignature.py`

```Python
664        self._add_query(_QueryStringConstants.SIGNED_SIGNATURE, 
665                        _sign_string(account_key, string_to_sign, False))
```
If I did not include the FALSE, which indicates that _sign_string is base 64, it throws an incorrect padding error. When I run this in my actual scenario, it does not raise this error (without the modification).

Either way, it returns a token that looks essentially the same as what I see.

```
sv=2015-04-05&sp=rwdl&se=2017-01-01T00%3A00%3A00Z&sig=SFFj8zd4/A5n2m8xnH4/xnCrafM/u/Ij9YZDcO6RaY4%3D&srt=sco&ss=bqtf
```

When I try and use this SAS token to retrieve the list of containers, I get the following error:

```
raise AzureHttpError(message, http_error.status)
azure.common.AzureHttpError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:e992fcb7-0001-001e-58e0-956009000000
Time:2016-04-14T00:00:59.1943001Z</Message><AuthenticationErrorDetail>Signature did not match. String to sign used was travistestresourcegr3014
rwdl
bqtf
sco

2017-01-01T00:00:00Z


2015-04-05
</AuthenticationErrorDetail></Error>
```

I thought it might be related to the fact that the token is in URL encoded form, but in debugging it seems that this gets decoded later on and is not the cause.

This has been frustrating me all afternoon. Any help would be much appreciated.

**Comment by emgerner-msft** [comment]
It absolutely should throw that padding error. This checks that the key you're signing with is base64, which it must be. If it's not, they key probably 1) has whitespace around it that was accidentally copied or 2) a portion of the key is missing. That's probably what's going wrong and why your SAS token results in an auth issue. Remove the changed library code, and check that your key is valid. If that doesn't work, report back where you're getting your key, and your version of Python.

**Comment by tjprescott** [comment]
Yep, you're right--part of the key was missing. In the actual use scenario, the user has the option of specifying the SAS token as a parameter or setting it in an environment variable. It seems like the option to specify it as a parameter is working, but setting it as an environment variable is not. 
...
But that's on me. Thanks for the help!
