### ISSUE TITLE
BlobService.put_blob needs timeout parameter

### ISSUE THREAD

**Issue by crwilcox** [Azure/azure-storage-python#17]
### Description:

It seems like sometime my socket connections from a Linux Azure VM to Azure Storage are stalling.  Can we add a timeout parameter to put_blob like some of the other functions?

Traceback below:

```
Unexpected upload error: <class 'socket.error'>
Traceback (most recent call last):
  File "GetHistory.py", line 81, in getAndUploadHist
    _bs.put_blob('thistory',filename,sz ,x_ms_blob_type='BlockBlob')
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/blobservice.py", line 693, in put_blob
    self._perform_request(request)
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/storageclient.py", line 143, in _perform_request
    resp = self._filter(request)
  File "/usr/local/lib/python2.7/dist-packages/azure/storage/storageclient.py", line 132, in _perform_request_worker
    return self._httpclient.perform_request(request)
  File "/usr/local/lib/python2.7/dist-packages/azure/http/httpclient.py", line 190, in perform_request
    self.send_request_body(connection, request.body)
  File "/usr/local/lib/python2.7/dist-packages/azure/http/httpclient.py", line 173, in send_request_body
    connection.send(request_body)
  File "/usr/lib/python2.7/httplib.py", line 805, in send
    self.sock.sendall(data)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 104] Connection reset by peer
```

**Comment by jehine-MSFT** [comment]
We plan to support setting both a client-side and a server-side timeout in our next release. Both will be configurable and will we allow each individual API to override the default. We are still working on the design for this as there are a lot of different solutions to this issue and want to choose the best one. We hope to complete this functionality and release it with our next major release.

**Comment by jakesher** [comment]
Any movement on this, I am experiencing a similar issue.  Thanks.

**Comment by jehine-MSFT** [comment]
We are working diligently to get a big release out by the end of February, so hopefully you will get this feature and a bunch of other bug fixes by 2/29.

**Comment by jakesher** [comment]
@jehine-MSFT Perfect! Thank you!! :))

**Comment by emgerner-msft** [comment]
After closer examination, what you're asking for actually doesn't solve the problem you've stated. A timeout parameter is now present on every API which makes service calls, but the timeout parameter isn't related to sockets. It applies to the service. Namely, the storage service itself will return a timeout error if it cannot complete the request in the specified amount of time.

Client side timeouts will be coming in some form or another, but like JC said there's a lot of different solutions. For example, the requests module which we use under the covers exposes a [timeout](http://docs.python-requests.org/en/master/user/quickstart/#timeouts) parameter but it's not really what you're asking for either: "timeout is not a time limit on the entire response download; rather, an exception is raised if the server has not issued a response for timeout seconds (more precisely, if no bytes have been received on the underlying socket for timeout seconds)."

So, while we will add a feature which handles socket timeouts in one way or another (to be determined), the 'total download time' version of timeout is actually not trivial.

**Comment by zezha-msft** [comment]
The default socket timeout could be set in _constants.py. It is set to 20seconds by default. It is also configurable by modifying the socket_timeout property on the service objects. Please let me know if you have any concern or question.
