### ISSUE TITLE
There is no way to turn off connection verification for SDK calls

### ISSUE THREAD

**Issue by BurtBiel** [Azure/azure-storage-python#175]
This is needed to use proxy tools to inspect the HTTP calls.

**Comment by emgerner-msft** [comment]
I'm not sure from this description what you're looking for. Could you clarify what you expect to happen and how you'd normally do this?

**Comment by emgerner-msft** [comment]
To clarify, it's quite easy to [set a proxy]](https://github.com/Azure/azure-storage-python/blob/master/samples/advanced/client.py#L67). We test with Fiddler regularly. If you want to use HTTP to make sniffing traffic easier, you can [change the protocol](https://github.com/Azure/azure-storage-python/blob/master/samples/advanced/client.py#L47). If you want to do something special with requests you can pass in a [custom session](https://github.com/Azure/azure-storage-python/blob/master/samples/advanced/client.py#L57). This obviously requires more care and testing as it's changing a fundamental aspect of how we're accessing storage.

All of these features should be available in most versions of the library and most definitely all the newer ones. If none of this is what you want, you'll need to clarify further what you're trying to do.

**Comment by BurtBiel** [comment]
I tried setting the protocol to http like the code in the link, but I still get an SSL error with Fiddler running.  Are there any other steps required to turn off SSL?  As another option, turning off the SSL verification and leaving SSL on would also solve my scenario.

Thanks,

Burt

**Comment by BurtBiel** [comment]
Actually, hold off on this.  The setting appears to work in at least some instances.  I'll keep investigating on my end.

Thanks,

Burt

From: Burt Bielicki
Sent: Wednesday, May 18, 2016 8:49 AM
To: 'Azure/azure-storage-python' <reply@reply.github.com>; Azure/azure-storage-python <azure-storage-python@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [Azure/azure-storage-python] There is no way to turn off connection verification for SDK calls (#175)

I tried setting the protocol to http like the code in the link, but I still get an SSL error with Fiddler running.  Are there any other steps required to turn off SSL?  As another option, turning off the SSL verification and leaving SSL on would also solve my scenario.

Thanks,

Burt

**Comment by BurtBiel** [comment]
My apologies for the spam, I think I haven’t had enough coffee yet this morning ☺.

I'm actually not seeing the http protocol setting take effect in any of the storage commands I issued.  With Fiddler open, I get the SSL validation error each time.  Any ideas are appreciated.

Thanks,

Burt

From: Burt Bielicki
Sent: Wednesday, May 18, 2016 8:54 AM
To: 'Azure/azure-storage-python' <reply@reply.github.com>; 'Azure/azure-storage-python' <azure-storage-python@noreply.github.com>
Cc: 'Author' <author@noreply.github.com>
Subject: RE: [Azure/azure-storage-python] There is no way to turn off connection verification for SDK calls (#175)

Actually, hold off on this.  The setting appears to work in at least some instances.  I'll keep investigating on my end.

Thanks,

Burt

From: Burt Bielicki
Sent: Wednesday, May 18, 2016 8:49 AM
To: 'Azure/azure-storage-python' <reply@reply.github.com>; Azure/azure-storage-python <azure-storage-python@noreply.github.com<mailto:azure-storage-python@noreply.github.com>>
Cc: Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Subject: RE: [Azure/azure-storage-python] There is no way to turn off connection verification for SDK calls (#175)

I tried setting the protocol to http like the code in the link, but I still get an SSL error with Fiddler running.  Are there any other steps required to turn off SSL?  As another option, turning off the SSL verification and leaving SSL on would also solve my scenario.

Thanks,

Burt

**Comment by emgerner-msft** [comment]
Considering we use Fiddler as well (and I just tested it worked for me), I'll need more specifics from you on the code you're using in order to debug further. This includes 1) how you're setting Fiddler as the proxy for the library and 2) how you're setting the protocol and 3) how you're creating your client. If you can post that code I'll try to reproduce your issue with exactly how you've done things.

**Comment by emgerner-msft** [comment]
Ping... :)

**Comment by BurtBiel** [comment]
This issue is specific to the data plane commands, the management plane works for us.

We have a general client creation like this:

client = service_type(account_name=account_name,
                          account_key=account_key,
                          connection_string=connection_string,
                          sas_token=sas_token)
            # need to disable connection verification here

storage_client = get_data_service_client(
        BlockBlobService,
        storage_account.name,
        keys.key1)

We would like a way to disable the client's connection verification.  For the management plane we set a property on the client object.  I haven't gotten a chance to try the latest SDK yet, we're still working through some issues before we can merge it into our project.

**Comment by emgerner-msft** [comment]
You mentioned that you'd tried setting the protocol like in the [sample](https://github.com/Azure/azure-storage-python/blob/master/samples/advanced/client.py#L47) I gave, but I don't see that in the code above. Could you include what you tried there?

The above unsurprisingly doesn't work since you haven't set the protocol to http like in the sample and the default for security is https.
