### ISSUE TITLE
Storage queue service should automatically encode/decode base 64

### ISSUE THREAD

**Issue by crwilcox** [Azure/azure-storage-python#18]
### Description:
The other SDKs (.NET, Node.js) do that, so if you want to interop with them, it's currently the user's responsibility to do the encoding/decoding when using the Python SDK.

We should make it transparent and automatically encode/decode base64 when sending/receiving queue messages.

This would be a breaking change.

If we don't do this, we should fix the docs at http://azure.microsoft.com/en-us/documentation/articles/storage-python-how-to-use-queue-storage to show the encoding/decoding code required on the client's side.

#### @cheif commented on 2014-04-25 15:01:51:
> I totally agree, the main idea of a SDK is to abstract away the implementation-details of the underlying resource, such as the transport using base64.

I think the best way to break the API is to bundle the breaking changes into a new major release (that would be 1.0.0 in this case), I think that there are some other things that also could be have a better abstraction (e.g. that StorageQueue.get_messages() should be a generator an not take a num_messages argument, that is also a leaky abstraction) or could be more pythonic (e.g. that QueueMessage-objects should be able to delete themselves, without using a StorageQueue-object, and a Blob-object being able to read their own data)

EDIT:
I realize that the "more-pythonic" changes can be implemented without breaking the API, I'd be happy to create a PR if others also think it's a good idea?

#### @saschagottfried commented on 2014-05-28 09:22:53:
> I had this issue this week with version 0.8.0 while developing code that receives queue messages transporting just a GUID that was inserted by .NET code. Since the .NET client did not insert XML or JSON into queue message I did not recognize the data as a base64 string. After checking .NET code is using usual code to insert queues messages, I eventually found MSDN information regarding base64 encoding/decoding of queue message. 

I expected this topic to be in discussion, so I am happy that package developers themselves make that an issue.

base64 decoding was not a big deal. The real problem at least for me was that I, as a developer, was not aware of that need to decode. Help developer to be aware that there are conditions where message.message_text is a base64 encoded string and therefore has to be decoded. And yes, update your docs as a first step towards a more pythonic Message Queue API. Otherwise you may risk to reduce Python developer satisfaction. That's not what you want since Azure rocks.

@cheif 
just do it and make a pull request. Open source is meant for contributions.

**Comment by emgerner-msft** [comment]
We've made a large variety of fixes to the queue API, largely on improving the return values (as was mentioned in another issue). For the encoding/decoding work it's not quite so clear what we should do. The Azure service itself requires at least XML encoding as the queue message is passed in XML tags. Base64 is used in some other languages (ex .Net) as there were whitespace preservation issues with the default xml encoder. 

In Python our testing shows no issues with the xml encoder and decoder, nor with base64. XML encode/decode will add a lot less length or no length to queue messages which are relatively constrained at 64KB. Base64 encoding is more compatible with some of our other languages but will in most cases add significant length to the message which we have heard as a complaint as well. So, if only using Python XML is probably best but for cross-lang base64 might be better.

In any case, we will provide hooks to control encoding and decoding on the queue service. With these hooks we will add documentation on both base64 and xml encoding and the trade-offs. Perhaps these hooks and docs are all you were looking for, but if you have feedback on the optimal default, we'd be interested in hearing.

**Comment by jehine-MSFT** [comment]
Hello @chief & @saschagottfried ,

We have released the 0.30 version (#132) which addressed this feature request. We decided to set the default encoding/decoding to XML but have enabled base64 encoding by passing the [binary_base64encode](https://github.com/Azure/azure-storage-python/blob/master/azure/storage/queue/models.py#L122) method when creating a queue service. If you have issues with the new version in regards to this issue, please reopen it and continue the discussion.

Thanks!
