### ISSUE TITLE
Emtpy ACL entry makes it impossible to retrieve ACL.

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-storage-python#180]
```Python
from azure.storage.blob import BlockBlobService
from azure.storage.models import AccessPolicy

cs = 'blah'
rg = 'blah'
sa = 'blah'
container = 'blah'

client = BlockBlobService(connection_string=cs)
client.create_container(container)
client.set_container_acl(container, {'corrupt': AccessPolicy()})
acl = client.get_container_acl(container)
```

This results in the following:

```
XML: b'\xef\xbb\xbf<?xml version="1.0" encoding="utf-8"?><SignedIdentifiers><SignedIdentifier><Id>corrupt</Id></SignedIdentifier></SignedIdentifiers>'
Traceback (most recent call last):
  File "C:\Users\trpresco\Documents\github\azure-cli\src\azure\acl_bug_repro.py", line 14, in <module>
    acl = client.get_container_acl(container)
  File "c:\users\trpresco\documents\github\azure-cli\env\lib\site-packages\azure\storage\blob\baseblobservice.py", line 689, in get_container_acl
    return _convert_xml_to_signed_identifiers_and_access(response)
  File "c:\users\trpresco\documents\github\azure-cli\env\lib\site-packages\azure\storage\blob\_deserialization.py", line 132, in _convert_xml_to_signed_identifiers_and_access
    acl = _convert_xml_to_signed_identifiers(response.body)
  File "c:\users\trpresco\documents\github\azure-cli\env\lib\site-packages\azure\storage\_deserialization.py", line 150, in _convert_xml_to_signed_identifiers
    start_element = access_policy_element.find('Start')
AttributeError: 'NoneType' object has no attribute 'find'
```

At this point all I can do is erase the container and recreate it. We have operations to delete an entry in the ACL, but it's contingent on being able to retrieve the list.

Currently we have a workaround in our application that ensures the user supplies at least one of the three parameters (start, expiry, permissions) but it would be helpful if the SDK threw a more useful error and didn't save the invalid entry.

**Comment by emgerner-msft** [comment]
>>At this point all I can do is erase the container and recreate it. We have operations to delete an entry in the ACL, but it's contingent on being able to retrieve the list.

This is now fixed in the dev branch. You should be able to both create and get empty ACLs. We'll get the fix out in our next release.

>>Currently we have a workaround in our application that ensures the user supplies at least one of the three parameters (start, expiry, permissions) but it would be helpful if the SDK threw a more useful error and didn't save the invalid entry.

Please *do not* ensure the user puts in at least one of the three parameters. Empty ACLs are valid and have use cases. For more info on this, see the [AccessPolicy documentation](https://github.com/Azure/azure-storage-python/blob/master/azure/storage/models.py#L316).
