### ISSUE TITLE
xml.etree error when importing azure.storage.blob

### ISSUE THREAD

**Issue by mattmcloughlin** [Azure/azure-storage-python#182]
I am using Python 2.7, and have the following statement:

from azure.storage.blob import BlockBlobService, ContainerPermissions

When debugging the Python script in VS 2015 (latest), I get the following error:

copy.Error was unhandled by user code Message: un(shallow)copyable object of type

Clicking "continue" allows you to safely ignore the error, but this still seems like a bug.

(screenshot attached).

<img width="505" alt="jrz33" src="https://cloud.githubusercontent.com/assets/10806332/15861437/5f447c5e-2c9a-11e6-8da3-a9f565ce5ce3.png">

**Comment by emgerner-msft** [comment]
cElement tree isn't part of our library, just something we use in Python. Seems like if this is a bug, it's in either Python or Visual Studio. Could you clarify a little more why this looks like a storage issue to you (maybe I'm missing context)?

**Comment by huguesv** [comment]
Hi Matt, see this: https://github.com/Microsoft/PTVS/issues/1218

**Comment by emgerner-msft** [comment]
Thanks Hugues! That looks like the issue, and a potential work around. I'll close this here.
