### ISSUE TITLE
create_blob_from_bytes issues ResourceWarning

### ISSUE THREAD

**Issue by Korijn** [Azure/azure-storage-python#188]
When I call `create_blob_from_bytes` with a `bytes` object, I see the following warning in the console (this is against the storage emulator, using version 0.32.0):

```
sys:1: ResourceWarning: unclosed <socket.socket fd=1060, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 55469), raddr=('127.0.0.1', 10000)>
```

**Comment by emgerner-msft** [comment]
Update: We are looking at this, it's just taking a while to debug. This definitely is emulator specific (aka we don't see it against prod), but we're not sure if the fix is in the emulator or the Python library.

**Comment by Korijn** [comment]
Just letting you know this is still happening with Emulator version 4.4.

**Comment by Korijn** [comment]
Still an issue, also with *real* storage!

**Comment by erezvani1529** [comment]
Hi @Korijn,

Thanks for following up about this issue. Would you please share a little bit about your usage of the library? (version of the sdk, whether or not you are using a proxy and the options you are setting on your call)

We will try to repro on our side and get back to you with more info soon :)

Thanks!
