### ISSUE TITLE
Using JSON payload

### ISSUE THREAD

**Issue by crwilcox** [Azure/azure-storage-python#19]
### Description:
Since Azure storage now supports JSON, it might be beneficial to parse JSON vs XML using python (haven't bench-marked) 

#### @huguesv commented on 2015-03-05 21:17:00:
> Storage and Service Bus now use ElementTree for xml deserialization.  This, along with some other changes, have improved the performance of deserialization significantly (in the coming 0.10 release).
https://github.com/Azure/azure-sdk-for-python/issues/254

**Comment by jehine-MSFT** [comment]
@emgerner-msft add JSON support for table payloads. A build with this will go out with the next major fix release.
Thanks!

**Comment by jehine-MSFT** [comment]
Hello @uschen,

We have released the 0.30 version (#132) which addressed this feature request. If you have issues with the new version in regards to this issue, please reopen it and continue the discussion.

Thanks!
