### ISSUE TITLE
Blob objects returned by list_blobs has None metadata properties

### ISSUE THREAD

**Issue by smereczynski** [Azure/azure-storage-python#192]
azure-storage==0.32.0
Python 3.4.3
requests==2.10.0

If You use:

```
from azure.storage import CloudStorageAccount
ACC = CloudStorageAccount(account_name, account_key)
SRV = ACC.create_block_blob_service()
GEN = SRV.list_blobs(container_name)
for blob in GEN:
    print(blob.metadata)
```

to get list of blobs in container and their metadata, You will have:

None
None
None
etc...

But if You use:

```
blob0 = SRV.get_blob_properties(container_name, blob_name)
print(blob0)
```

Everything is OK:

{'val1': 'foo', 'val2': 'blah'}

In both cases we have azure.storage.blob.models.Blob object so there should be 'metadata' property as in Model.

**Comment by erezvani1529** [comment]
Hi @smereczynski,

List blobs by default does not return metadata unless you specify "Metadata" in the "include" parameter when calling the method. Have you tried adding this parameter to your calls?

**Comment by smereczynski** [comment]
@erezvani1529 hmmm I didn't. Probably because of lack of documentation ;) I will try and get back with results (probably for closing this issue). Thanx!

**Comment by smereczynski** [comment]
@erezvani1529 OK. Of course it works. Is there any plan to create some reliable documentation for Python SDK?

**Comment by erezvani1529** [comment]
@smereczynski Thanks for the feedback. To get started please refer to [code documentation](http://azure.github.io/azure-storage-python/ ) for detailed information about APIs and different modules. 

Our teams are actively working on the existing documentations and samples for a better developer experience.

Thanks!

**Comment by karishmakhubchandani** [comment]
Hi even m facing the same problem. I m using list_blobs but when i try to print snapshot it shows none. and the link you are pointing to give page not found

**Comment by zezha-msft** [comment]
Hi @karishmakhubchandani, please refer to the [sample](https://github.com/Azure/azure-storage-python/blob/master/samples/blob/container_usage.py#L238).
