### ISSUE TITLE
Link to the Docs

### ISSUE THREAD

**Issue by tomviner** [Azure/azure-storage-python#193]
I understand you [may be moving the docs](https://github.com/Azure/azure-storage-python/issues/78#issuecomment-185448701). But whether it's the [github.io docs](https://azure.github.io/azure-storage-python/
) or the [readthedocs docs](https://azure-storage.readthedocs.io/), the README should contain a link to some docs somewhere.

Also link via the header box on Github please:
![image](https://cloud.githubusercontent.com/assets/167319/16449251/3b7f4ef6-3dee-11e6-97a8-536b569fbbf6.png)

**Comment by pemari-msft** [comment]
Thanks for the comment. This is good feedback. @rickle-msft , can you help out on this one (edit the readme to point to github.io)?

**Comment by pemari-msft** [comment]
The second line of our readme reads: `For documentation please see the Microsoft Azure Python Developer Center and our GitHub.io Reference Page.` with a link to github.io. I'll look into the header box (I don't think I have permissions for that right now). Thanks!
