### ISSUE TITLE
Swallows successive multiple slashes in blob URLs

### ISSUE THREAD

**Issue by ahmetalpbalkan** [Azure/azure-storage-python#194]
Blob storage supports blob names like: `http://.../container/blob//name.txt` (in this case blob name should be `blob//name.txt` (if you try to fetch `blob/name.txt` via HTTP client, it won't work).

Storage account swallows successive multiple slashes when 

1. creating the blobs
2. getting the blob [...properties etc]

When I try to create a blob like:

    bs.put_blob('foo','has//double//slashes','','BlockBlob')

Its name shows up as `has/double/slashes` in the backend and when I try to fetch it:

    bs.get_blob_properties('foo', 'has//double//slashes')
    bs.get_blob_properties('foo', 'has/double/slashes')

they both return success. This should not be true as `has/double/slashes` and `has//double//slashes` are different resources according to Azure Blob Storage (but not to the URL specification –that's by design in Azure Blob Storage; but IMO, a mistaken one).

In any case, this is a bug.

**Comment by jofriedm-msft** [comment]
Hi @ahmetalpbalkan ,

It appears you are using an older version of the client. We tried to repo this with the latest client using our public APIs as well as calling _put_blob() directly (which is now private) and the multiple slashes are preserved. Multiple slashes also appear to be preserved for get_blob_properties()

Can you try updating to the latest client and let me know if you are still experiencing this issue?

**Comment by rambo-msft** [comment]
To ease your transition if you do update (as it is likely you may be using a version prior to 0.30.0), there are now separate classes for each blob type.

For `BlockBlobService`, as @jofriedm-msft mentioned, put_blob was made private/internal, and now can be used with the Convenience API:  `create_blob_from_stream`. 

For` PageBlobService` and `AppendBlobService`, `put_blob` was replaced with `create_blob`.

You can refer to [Breaking Changes](https://github.com/Azure/azure-storage-python/blob/bc985392407459717634b46eda7d8f66b7ffb4dc/BreakingChanges.md)  to see a more detailed list of the API changes.

At any rate,  `//` in  `has//double//slashes` corresponds to an empty directory and on our end these values also appear to be preserved with both create and fetch operations.

**Comment by ahmetalpbalkan** [comment]
Ah no biggie, I just used the old `BlobService` client in the SDK. and I was actually just giving Python SDK a spin because I wanted to see how it behaves with slashes and special characters in blob names. We've got some issues about these in the Go SDK.
