### ISSUE TITLE
Blob Service get_blob_to_path progress_callback seems poorly undocumented

### ISSUE THREAD

**Issue by zfrenchee** [Azure/azure-storage-python#197]
When is the callback called? I can see example use in the [test](https://github.com/Azure/azure-storage-python/blob/bc985392407459717634b46eda7d8f66b7ffb4dc/tests/test_get_blob.py) but I don't know when it'll be called. I have to make inferences based on the assertions [here](https://github.com/Azure/azure-storage-python/blob/bc985392407459717634b46eda7d8f66b7ffb4dc/tests/testcase.py#L306). It would be nice if someone filled in the [TODOs in the usage examples](https://github.com/Azure/azure-storage-python/blob/master/samples/blob/block_blob_usage.py#L323)

**Comment by kfarmer-msft** [comment]
Data from the service is brought down in multiple chunks.  The callback gets called for each chunk received.

**Comment by zfrenchee** [comment]
By chunk do you mean block? Or is a chunk some number of blocks?

**Comment by kfarmer-msft** [comment]
Range of bytes request from the server.  See the docs on the [BaseBlobService](https://github.com/Azure/azure-storage-python/blob/bc985392407459717634b46eda7d8f66b7ffb4dc/azure/storage/blob/baseblobservice.py) class.

**Comment by kfarmer-msft** [comment]
The comments in the sample code for blob_with_path are intended to direct you the examples shown in blob_with_bytes, not to act as TODOs.  We apologize if that wasn't clear.
