### ISSUE TITLE
Table name validation

### ISSUE THREAD

**Issue by crwilcox** [Azure/azure-storage-python#20]
### Description:
It seems that you are unable to use punctuation in table names, although it isn't clear what is and isn't allowed. 

```python
>>> ts = TableService()
>>> ts.create_table("foo")
True
>>> ts.create_table("routing_table")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\azure\storage\tableservice.py", line 135, in create_table
    _dont_fail_on_exist(e)
  File "C:\Python27\lib\site-packages\azure\__init__.py", line 453, in _dont_fail_on_exist
    raise error
azure.WindowsAzureError: Unknown error (Bad Request)
>>> ts.create_table("routingtable")
True
```

It would be nice if some sort of client-side validation was done, if possible.

#### @slyons commented on 2012-06-27 21:43:31:
> On further review it looks like it's not just punctuation that causes it, but I'm not quite sure what the cause is.

```python
>>> target = "routing_table"
>>> for fn in funcs:
...     try:
...             print fn, fn(target)
...             ts.create_table(fn(target))
...     except Exception, e:
...             print repr(e)
...     else:
...             print fn, "passed!"
...
<function b64encode at 0x0000000001FCC7B8> cm91dGluZ190YWJsZQ==
WindowsAzureError(u'Unknown error (Bad Request)',)
<function urlsafe_b64encode at 0x0000000001FCC978> cm91dGluZ190YWJsZQ==
WindowsAzureError(u'Unknown error (Bad Request)',)
<function b32encode at 0x0000000001FCCA58> OJXXK5DJNZTV65DBMJWGK===
WindowsAzureError(u'Unknown error (Bad Request)',)
<function b16encode at 0x0000000001FCCB38> 726F7574696E675F7461626C65
WindowsAzureError(u'Unknown error (Bad Request)',)

>>> target="routingtable"
>>> for fn in funcs:
...     try:
...             print fn, fn(target)
...             ts.create_table(fn(target))
...     except Exception, e:
...             print repr(e)
...     else:
...             print fn, "passed!"
...
<function b64encode at 0x0000000001FCC7B8> cm91dGluZ3RhYmxl
False
<function b64encode at 0x0000000001FCC7B8> passed!
<function urlsafe_b64encode at 0x0000000001FCC978> cm91dGluZ3RhYmxl
False
<function urlsafe_b64encode at 0x0000000001FCC978> passed!
<function b32encode at 0x0000000001FCCA58> OJXXK5DJNZTXIYLCNRSQ====
WindowsAzureError(u'Unknown error (Bad Request)',)
<function b16encode at 0x0000000001FCCB38> 726F7574696E677461626C65
WindowsAzureError(u'Unknown error (Bad Request)',)
```

#### @weidongh commented on 2012-07-05 16:44:36:
> Table names may contain only alphanumeric characters and cannot begin with a numeric character. They are case-insensitive and must be from 3 to 63 characters long.
Please refer to http://msdn.microsoft.com/en-us/library/windowsazure/dd179338.aspx. 

We will add comments for the requirement of table name in next push.  

#### @mrhwick commented on 2012-10-22 16:06:38:
> The regular expression defines the rules most concisely.

These rules are also described by the regular expression "^[A-Za-z][A-Za-z0-9]{2,62}$".

**Comment by emgerner-msft** [comment]
Here's what we will be doing to fix this:
 1. Improve the method-level documentation to better specifying naming limitations. These changes will come out in the next major library release.
 2. Take a service-side feature request to make the error messages more informative.
