### ISSUE TITLE
Unable  to create additional Queue ACL entries when existing entry contains 'process' permission

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-storage-python#203]
``` Python
from azure.storage.queue import QueueService
from azure.storage.queue.models import QueuePermissions

cs = 'blah'
rg = 'blah'
sa = 'blah'
queue = 'blah'

client = QueueService(connection_string=cs)

client.create_queue(queue)
acl = {'1': AccessPolicy(permission='r')}
acl['2'] = AccessPolicy(permission='a')
client.set_queue_acl(queue, acl)
```

At this point, you will get the unhelpful error I described in #181. However, the SDK states (and the other service allow) that the ACL should be able to contain 5 entries. If I delete the single entry, I can create another no problem.

**Comment by jofriedm-msft** [comment]
Hi @tjprescott,
I am unable to repro this problem using the latest version of the client library.

What version of the library are you using? If you aren't using the latest can you try updating and see if this problem persists?

If you are using the latest version of the library already can you provide a fiddler trace?

**Comment by tjprescott** [comment]
We're using 'azure-storage 0.32.0'

**Comment by jofriedm-msft** [comment]
@tjprescott Can you try updating your client library and see if the problem persists?

**Comment by tjprescott** [comment]
I have a better repro. Apparently it's not that you can only have 1 entry.

```Python
from azure.storage.queue import QueueService
from azure.storage.models import AccessPolicy

cs = "blah"
rg = 'blah'
sa = 'blah'
queue = 'blah'

client = QueueService(connection_string=cs)
client.create_queue(queue)

client.set_queue_acl(queue, {})
acl = client.get_queue_acl(queue)

acl = {'1': AccessPolicy(permission='raup')}
client.set_queue_acl(queue, acl)

print('OK 1!')

acl = client.get_queue_acl(queue)
acl['2'] = AccessPolicy(permission='a')
client.set_queue_acl(queue, acl)

print('OK BOTH!')
```
When I create the first access policy, it will always pass if I pass in a valid permissions string (meaning the correct order). However, the attempt to add a second policy only succeeds if the first policy was 'p' or 'rp'.  If I try any other combination that includes the process permission (up, rup, ap, rap, aup, raup), the second attempt always fails with that incredibly unhelpful 'XML is invalid' error.

I've done a similar experiment with the other services (blob, file, table) and this doesn't happen.

**Comment by jofriedm-msft** [comment]
Hi @tjprescott 

Yes, there appears to be a bug on the service where GetACL() does not return back the correct order only for queues. I have created a bug for this and we will fix it in an upcoming service release. Thank you for pointing this out! 👍

**Comment by zezha-msft** [comment]
This issue has been fixed.
