### ISSUE TITLE
try to use python with azure.storage module to create azure query but show error

### ISSUE THREAD

**Issue by kuomingwu** [Azure/azure-storage-python#208]
[environment]

python version : 2.7
azure-storage version : 0.32.0
OS: SUSE 12 

[error message]

AttributeError: 'QueueMessage' object has no attribute 'message_id'

[error detail]

create , put, peer and dequeue with error

AttributeError: 'QueueMessage' object has no attribute 'message_id'
## lcsdweb07:/scripts/python # pip show azure-storage

Name: azure-storage
Version: 0.32.0
Location: /usr/lib/python2.7/site-packages
Requires: azure-nspkg, azure-common, python-dateutil, requests, futures

lcsdweb07:/scripts/python # python
Python 2.7.9  [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.

from azure.storage.queue import QueueService

queue_service = QueueService(account_name='lcsdqueuetest', account_key='key')
# Dequeue message

messages = queue_service.get_messages('scalequeue')
for message in messages:
    print(message.content)
    queue_service.delete_message('scalequeue', message.message_id, message.pop_receipt)

![image](https://cloud.githubusercontent.com/assets/6070952/17585817/96f6a044-5ff0-11e6-9261-2046d6a5f75b.png)

**Comment by jofriedm-msft** [comment]
Hi @kuomingwu ,

I see that we changed the attribute message_id to id in v 0.33.0 of the library. Can you confirm that you aren't using a later version? Can you also try updating to the latest version of the library and see if this problem persists
