### ISSUE TITLE
Incorrect Documentation of ID parameter for generate_{service}_shared_access_signature

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-storage-python#210]
For the BlobService, FileService and QueueService, the docstring for the ID parameter incorrectly states that to created a stored access policy, use the `set_{service}_service_properties` method. However, this method is used for settings like the CORS and logging, not stored access policies. The TableService correctly states that you should use `set_table_acl`. 

Additionally, they say you can use an ID to one of these access policies, but I have not found a way to actually get the ID of a stored access policy. It is not part of the ACL object and doesn't appear as a collection in object to which the policy is associated. What is the format for this ID?

**Comment by jofriedm-msft** [comment]
Hi @tjprescott ,

Yes, the documentation for generate_{service}_shared_access_signature should say use :func:`~set_{service}_acl under the id param description for all services. I will make this fix.

As for the second part of your question, the id is a unique 64 character str. We have examples use cases in sas_usage.py within our samples.

**Comment by tjprescott** [comment]
So, looking at the samples, it looks like the "id" is just the key for the ACL entry, not an ID in the normal Azure sense (/subscriptions/.../resourceType/resourceName/childResourceType/...etc.) Is this correct?

**Comment by jofriedm-msft** [comment]
@tjprescott  That is correct. Each object supports up to 5 ACLs with each one having their own unique identifier. Here is the rest API spec for Set Container ACL https://msdn.microsoft.com/en-us/library/azure/dd179391.aspx
