### ISSUE TITLE
Dangerous default value for 'acquire_*_lease'

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-storage-python#216]
During our review with the storage service team, they pointed out that infinite (-1) is a dangerous value for container/blob lease duration. Consider changing the default value so that the default operation is the safe operation.

CC:  @hasonmsft, @vinjiang, @johanste, @mayurid

**Comment by kfarmer-msft** [comment]
Many customer scenarios use infinite lease without issue.  If there's a need to break the lease, that is already supported.

**Comment by johanste** [comment]
I don't believe that @tjprescott is suggesting that we'd disallow infinite lease. The question is if it is a good (and safe) default. The guidance we were given for implementing CLI commands over this method was to *not* use infinite as the default value (unless the user explicitly opt in to it), and we are suggesting that the same guidance should be applicable to the SDK itself.

**Comment by pemari-msft** [comment]
There is nothing unsafe about an infinite lease. Please feel free to reach out to me offline to share where you received your guidance so we can discuss with those people as well.

**Comment by hasonmsft** [comment]
@pemari-msft , I suggested with this because infinite lease will block users from deletion unless they break the lease explicitly. A lease with timeout will be more safe. :)

**Comment by pemari-msft** [comment]
Delete protection isn't unsafe. Overall, this feature has nothing to do with security or safety, so an infinite default is fine.

**Comment by pemari-msft** [comment]
We can let the customer set a value that makes sense for their scenario.
