### ISSUE TITLE
Pre-condition Headers not Supported by Storage Service

### ISSUE THREAD

**Issue by tjprescott** [Azure/azure-storage-python#217]
During our review with the storage service team, they pointed out that the SDK exposes numerous pre-condition headers that are not in fact supported by the service. If these parameters do nothing, they should probably not be part of the public SDK interface.

Here are some of the SDK calls which expose unsupported pre-condition headers:

- `*BlobService.get_blob_metadata`
- `*BlobService.get_blob_properties`
- `*BlobService.acquire_container_lease`
- `*BlobService.break_container_lease`
- `*BlobService.change_container_lease`
- `*BlobService.release_container_lease`
- `*BlobService.renew_container_lease`
- `*BlobService.set_container_metadata`

There may be more, but those were the ones specifically called out by the storage service team.

CC: @hasonmsft, @vinjiang, @johanste, @mayurid

**Comment by pemari-msft** [comment]
These APIs do indeed support conditional headers as per our REST spec.
