### ISSUE TITLE
Make Entity subclass of dict

### ISSUE THREAD

**Issue by huguesv** [Azure/azure-storage-python#22]
We should integrate this change:
https://github.com/Azure/azure-sdk-for-python/pull/411

We already allow passing dicts or Entity objects *into* azure storage, but for queries, we always return Entity objects.  This change lets the user access the entity objects as dicts.

**Comment by huguesv** [comment]
Note that we can get rid of the WindowsAzureData base class, and just derive from dict.
In serialization code, we can remove the check if it's a dict or an entity object, since they are all dicts.

**Comment by jehine-MSFT** [comment]
@emgerner-msft merged the suggested fix. A build with this will go out with the next bug fix release. Thanks!

**Comment by jehine-MSFT** [comment]
Hello @Philmist,

We have released the 0.30 version (#132) which addressed this feature request. If you have issues with the new version in regards to this issue, please reopen it and continue the discussion.

Thanks!
