### ISSUE TITLE
Upload File into Blob Storage

### ISSUE THREAD

**Issue by adityosnrost** [Azure/azure-storage-python#222]
Hi, 

I'm trying to upload an image into my storage. But, I've got an error with simple example from https://azure.microsoft.com/en-us/documentation/articles/storage-python-how-to-use-blob-storage/ sample.

here is my code:

![error upload](https://cloud.githubusercontent.com/assets/8223156/18614409/2c551b9a-7db8-11e6-935b-0bead78f7f4c.PNG)

Here is the error result on uploadfile:

![image](https://cloud.githubusercontent.com/assets/8223156/18614405/23348c08-7db8-11e6-9fbb-af52948a7f47.png)

**Comment by rambo-msft** [comment]
Hi @adityosnrost,
This type of error is usually associated with a malformed `account_key`.
Can you confirm it is the same value listed in the Azure portal. It should end with `==` and have no leading or trailing whitespaces.

Thanks!

**Comment by adityosnrost** [comment]
Hi,

Sorry for my late reply. I've fixed the problem. There was error with this:
![image](https://cloud.githubusercontent.com/assets/8223156/18809681/9d6a2f16-82ac-11e6-9d81-5843d0bb946c.png)

Then, I commented this line and I've got an error on using SDK. After that, I recover the cElementTree.py and everything is working well.

Thank You

Best Regards,

Adityo Setyonugroho
