### ISSUE TITLE
Creating an Empty Block Blob

### ISSUE THREAD

**Issue by adityosnrost** [Azure/azure-storage-python#223]
Hi,

I would like to update an Empty Block Blob. How can I do it ? I have scenario, that I'm the who creating an empty block blob and creating SAS locator. Then, someone is uploading file into it using python SDK also.

_Note_
So far, I have been able to do this:
- creating empty Block Blob
- generating SAS locator for the blob

Thanks

Best Regards,

Adityo

**Comment by pemari-msft** [comment]
I'm not sure I quite understand -- it sounds like you may want to use the `PutBlock` and `PutBlockList` apis. Take a look at our [samples ](https://github.com/Azure/azure-storage-python/blob/master/samples/blob/block_blob_usage.py) and let us know if you have any issues.

**Comment by rambo-msft** [comment]
Hi @adityosnrost ,
Haven't heard from you in a while. If you are still running into any issues and need more assistance feel free to open this back up :-).
