### ISSUE TITLE
retry attempt configuration in blob download

### ISSUE THREAD

**Issue by samrudh** [Azure/azure-storage-python#226]
When we are performing download, how can we configure retry? In the old versions of SDK I saw max_retry parameter, do we have something like that now? 
I need to handle the network fluctuations on the client machine while attempting file download and avoid re-downloading of complete files again.
Azure-storage python SDK version: 0.33.0
python: 2.7
OS: linux

**Comment by rambo-msft** [comment]
Hi @samrudh,
In v0.33.0, retry parameters for our create and get functions were [removed](https://github.com/Azure/azure-storage-python/blob/master/BreakingChanges.md) in favor of client-level retry policies. Take a look at this [sample](https://github.com/Azure/azure-storage-python/blob/master/samples/advanced/client.py) which covers retry usage for blobs.
