### ISSUE TITLE
Support for different environments (e.g. Microsoft Cloud Germany)?

### ISSUE THREAD

**Issue by arafato** [Azure/azure-storage-python#227]
Hi --, 

are all Azure environments (e.g. German Cloud) supported by the SDK? Can you specify the environment to use? I haven't found anything in the SDK. Thanks!

Best regards
--Oliver.

**Comment by erezvani1529** [comment]
Hi @arafato,

You can use storage SDKs to make call to any valid Storage Account given its connection string/credentials(regardless of which Geo zone your account is created on). 

You might want to checkout [Azure Storage Emulator ](https://azure.microsoft.com/en-us/documentation/articles/storage-use-emulator/)for development and testing as well.

Thanks!

**Comment by arafato** [comment]
Thanks @erezvani1529! 
So given only the storage account name and the credentials/shared key how does the SDK know which environment and correct endpoints respectively to use? The international Azure cloud has a `.core.windows.net` storage endpoint suffix while the German Cloud has a `.core.cloudapi.de` storage endpoint suffix for example. Am I overlooking something?

**Comment by erezvani1529** [comment]
You can explicitly specify the service endpoints instead of using the default endpoints in your connection string. This [link ](https://azure.microsoft.com/en-us/documentation/articles/storage-configure-connection-string/) provides more details for different cases.

Let us know if there is anything else not clear :)

Thanks!

**Comment by arafato** [comment]
Thanks @erezvani1529! 
I've also realized that you can override the storage endpoint suffix in the constructor of `BlockBlobService` which is what I will be using. [https://github.com/Azure/azure-storage-python/blob/master/azure/storage/blob/blockblobservice.py#L117](https://github.com/Azure/azure-storage-python/blob/master/azure/storage/blob/blockblobservice.py#L117)

**Comment by steffenmllr** [comment]
I just ran into the same issue. Would be nice if that would be in the docs somewhere.
This is how to use the `FileService` in the German cloud.

```
from azure.storage.file import FileService
file_service = FileService(endpoint_suffix="core.cloudapi.de", account_name='myAccountName', account_key='myAccountKey')
```

**Comment by zezha-msft** [comment]
Hi @steffenmllr, there is a [sample](https://github.com/Azure/azure-storage-python/blob/master/samples/advanced/client.py#L82) for this. Thanks!

**Comment by steffenmllr** [comment]
@zezha-msft ah ok thanks for the info. Looks like I was just searching for the wrong terms.
