### ISSUE TITLE
Can't work with China cloud when using connection string

### ISSUE THREAD

**Issue by derekbekoe** [Azure/azure-storage-python#229]
REPRO WITH:

```
from azure.storage.blob import BlockBlobService
connection_string = 'A_CONNECTION_STRING_FOR_CHINA_STORAGE_ACCOUNT'
endpoint_suffix = '.core.chinacloudapi.cn'
client = BlockBlobService(connection_string=connection_string, endpoint_suffix=endpoint_suffix)
containers = list(client.list_containers())
print(containers)
```

The script will hang has it attempts to use the endpoint `.blob.core.windows.net` (even though endpoint_suffix is for China cloud) and the storage account at that endpoint does not exist.

Looks like in the `get_service_parameters` method, `endpoint_suffix` is not passed to `_ServiceParameters._from_connection_string` and so the default is used.

Offending file: https://github.com/Azure/azure-storage-python/blob/717f616809c82b6cbf3e258f3d94303e6fabe411/azure/storage/_connection.py#L96

cc: @johanste, @tjprescott, @mayurid

**Comment by derekbekoe** [comment]
If I provide a connection string and the connection string doesn't contain `EndpointSuffix` (as was my case), I'd expect the SDK to use the endpoint_suffix specified in the Service constructor rather than ignoring it and using a default.

**Comment by jofriedm-msft** [comment]
Hi @derekbekoe, thank you for pointing this out. There does appear to be a bug where endpoint_suffix is not being used. We will fix this in an upcoming release. Thanks for pointing this out!

**Comment by mayurid** [comment]
@jofriedm-msft : Whats the eta for the upcoming release?

**Comment by rambo-msft** [comment]
Update -- As per the documentation, this functionality is by design.
```
:param str connection_string:
            If specified, this will override all other parameters besides 
            request session. See
            http://azure.microsoft.com/en-us/documentation/articles/storage-configure-connection-string/
            for the connection string format.
```

The `connection_string` should contain the `EndPointSuffix` if it's being used as the other parameters will be ignored/overriden.
