### ISSUE TITLE
Get Azure container BILLABLE SIZE 

### ISSUE THREAD

**Issue by vijayrajah** [Azure/azure-storage-python#231]
Azure standard storage, cost is based on actual used size not allocated size. This data is in the portal (portal.azure.com) under container properties.

There seems to be no way to get this data via API. Is is possible to get this info with python API?

**Comment by jofriedm-msft** [comment]
Hi @vijayrajah , 

If you enable $metrics you can view the entire capacity taken up by the blob service. For more info on how to enable and access these metrics take a look at https://msdn.microsoft.com/en-us/library/azure/hh343258.aspx

To see the specific capacity being used by a single blob or container requires a little more manual work.
The best option available currently is outlined in 
"How to Estimate Capacity" at https://blogs.msdn.microsoft.com/windowsazurestorage/2010/07/08/understanding-windows-azure-storage-billing-bandwidth-transactions-and-capacity/

**Comment by vijayrajah** [comment]
hi @jofriedm-msft 

Thanks for this.. I tried the get_page_ranges(), from the pageblob service API. But, it is very slow.. I'm calling the get_page_ranges() for every Page Blob. Is there a way to do it at an container level, instead of at Blob level.

**Comment by jofriedm-msft** [comment]
@vijayrajah , unfortunately there are no container level APIs or faster ways at this time to estimate the size.
