### ISSUE TITLE
Receiving error: "ImportError: cannot import name 'ContentSettings'" 

### ISSUE THREAD

**Issue by aarsan** [Azure/azure-storage-python#232]
I am having an issue running the command in the following ticket:

https://github.com/Azure/azure-storage-python/issues/134 

Trying to run the following piece of code:

    from azure.storage.blob import ContentSettings
        block_blob_service.create_blob_from_path(
            'mycontainer',
            'myblockblob',
            'sunset.png',
        content_settings=ContentSettings(content_type='image/png')
        )

and I receive the following error:

Receiving error: "ImportError: cannot import name 'ContentSettings'"

**Comment by rambo-msft** [comment]
Hi @aarsan,
The code as is works fine on my end. Many of these "cannot import name" errors are a result of environmental issues and/or circular imports. 
Can you first ensure you're using the latest version via:
`pip install azure-storage --upgrade`
Can you also share the other relevant parts of your script (imports)!

Thanks.

**Comment by aarsan** [comment]
Thanks. Looks like I just needed an upgrade. Appreciate the help
