### ISSUE TITLE
Request: Create URL to blob snapshot by make_blob_url

### ISSUE THREAD

**Issue by troydai** [Azure/azure-storage-python#233]
The current `make_blob_url` doesn't generate url for blob snapshot. It will helpful if snapshot time stamp can be given to generate snapshot URL.

https://github.com/Azure/azure-storage-python/blob/717f616809c82b6cbf3e258f3d94303e6fabe411/azure/storage/blob/baseblobservice.py#L218

**Comment by rambo-msft** [comment]
Hi @troydai,
Thanks for your suggestion. We'll definitely take that into consideration for our next release. :-).

**Comment by yanheven** [comment]
hi, @troydai , I also want this feature, see this pull request https://github.com/Azure/azure-storage-python/pull/234

**Comment by yanheven** [comment]
reopen PR against the dev branch https://github.com/Azure/azure-storage-python/pull/236
