### ISSUE TITLE
Add API to generated URL for container

### ISSUE THREAD

**Issue by troydai** [Azure/azure-storage-python#237]
Just like the `BaseBlobService.make_blob_url`

**Comment by zezha-msft** [comment]
The API was [added](https://github.com/Azure/azure-storage-python/commit/6885b6c4161b0a4aa1983c8460e43dbb550fcf59) and will go out with the next release.

**Comment by zezha-msft** [comment]
This was fixed in release 1.0.0 of the blob package.
