### ISSUE TITLE
Azure -storage :queue_service.put_message invalid syntax

### ISSUE THREAD

**Issue by saajnambiar** [Azure/azure-storage-python#238]
hello, i am using asure-storage package in raspbian linux environ ment and coding in python3.

following is the sample code i am trying to run:
from azure.storage.queue import QueueService
from base64 import b64encode
def main():
		queue_service = QueueService(account_name='myaccount', account_key='mykey')
		queue_service.create_queue('taskqueue')
		encoded_msg = b64encode('hello world')
		encoded_msg_txt = encoded_msg.decode()
		queue_service.put_message('taskqueue',encoded_msg_txt)
		
		
		queue_service.delete_queue('taskqueue')

if __name__ == '__main__':
    programRun()

error:
pi@raspberrypi ~/Desktop $ sudo python3 main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from azure.storage.queue import QueueService
  File "/usr/local/lib/python3.2/dist-packages/azure_storage-0.33.0-py3.2.egg/azure/storage/__init__.py", line 21, in <module>
    from .models import (
  File "/usr/local/lib/python3.2/dist-packages/azure_storage-0.33.0-py3.2.egg/azure/storage/models.py", line 221
    self.version = u'1.0'
                                 ^
SyntaxError: invalid syntax

Could you please help me to sort it out?

**Comment by rambo-msft** [comment]
Hi @saajnambiar ,
While I could not repro this on my rpi, if you're still having issues, make sure your `azure-common` (Azure python SDK)  package is up to date and try to run the code again.

**Comment by saajnambiar** [comment]
Thanks for reply @rambo-msft ,

I have sorted it out by installing latest version of cryptography package.
thanks man your effort highly appreciated.
