### ISSUE TITLE
create_blob_from_path ('Connection aborted.', timeout('The write operation timed out',))

### ISSUE THREAD

**Issue by mitesh3008** [Azure/azure-storage-python#239]
library version : azure-storage==0.33.0

`from azure.storage.blob import ContentSettings
from azure.storage.blob import BlockBlobService
import magic`

`def save_doc_to_blob(container_name, file_path, blob_name):
    file_type = content_type(file_path)
    blob_service.create_blob_from_path(
        container_name,
        blob_name,
        file_path,
        content_settings=ContentSettings(content_type=file_type),
    )`

`def content_type(file_name):
    return magic.from_file(file_name, mime=True)
`

getting ('Connection aborted.', timeout('The write operation timed out',).

**Comment by jofriedm-msft** [comment]
Hi @mitesh3008, can you share a fiddler trace? Is this happening for all requests or just some of the time?
