### ISSUE TITLE
Installing azure-storage-python off-line

### ISSUE THREAD

**Issue by redvries** [Azure/azure-storage-python#240]
I would like to install the azure-storage-python package on an environment that has no access to the internet.
I used the download version but unfortnatly this too needs access to the web.
Are there any other options?

**Comment by rambo-msft** [comment]
@redvries,
Since the package is on PYPI, install it on a machine that does have internet connection (full setup) and tar/zip up all the dependencies in the `site-packages` folder and move it over to your new environment. This should do the trick, let me know otherwise.

Thanks.
