### ISSUE TITLE
No Module named Common error

### ISSUE THREAD

**Issue by beraybentesen** [Azure/azure-storage-python#244]
I've installed from scratch 4-5 times but still getting same error when I run code that works on different Raspberry Pi. 

Tried both pip and git clone but did nothing. Also tried installing only azure not azure-storage.

**Comment by beraybentesen** [comment]
Okay, after 2 days I've solved my problem. But this library won't work with neither pip or git clone. Only old version (0.11.1 ) works without any 'No Module named XX Error'. 

I work with Raspberry Pi 2 with Raspbian OS with Python 2.7

**Comment by rambo-msft** [comment]
Hi @beraybentesen 
For the latest version, try updating the cryptography package you are using (and the same with azure-common), then reinstall the storage package using the pip or the git clone instructions.

**Comment by michaelseto** [comment]
How do you update the cryptography package and azure-common?

I installed via ::

sudo pip install -U cffi
sudo yum install gcc libffi-devel python-devel openssl-devel

**Comment by michaelseto** [comment]
sudo pip install cryptography
Requirement already satisfied: cryptography in /usr/lib/python2.7/site-packages/cryptography-1.7.2-py2.7-linux-x86_64.egg
Requirement already satisfied: idna>=2.0 in /usr/lib/python2.7/site-packages (from cryptography)
Requirement already satisfied: pyasn1>=0.1.8 in /usr/lib/python2.7/site-packages (from cryptography)
Requirement already satisfied: six>=1.4.1 in /usr/lib/python2.7/site-packages (from cryptography)
Requirement already satisfied: setuptools>=11.3 in /usr/lib/python2.7/site-packages (from cryptography)
Requirement already satisfied: enum34 in /usr/lib/python2.7/site-packages (from cryptography)
Requirement already satisfied: ipaddress in /usr/lib/python2.7/site-packages (from cryptography)
Requirement already satisfied: cffi>=1.4.1 in /usr/lib64/python2.7/site-packages (from cryptography)
Requirement already satisfied: appdirs>=1.4.0 in /usr/lib/python2.7/site-packages (from setuptools>=11.3->cryptography)
Requirement already satisfied: packaging>=16.8 in /usr/lib/python2.7/site-packages (from setuptools>=11.3->cryptography)
Requirement already satisfied: pycparser in /usr/lib/python2.7/site-packages (from cffi>=1.4.1->cryptography)
Requirement already satisfied: pyparsing in /usr/lib/python2.7/site-packages (from packaging>=16.8->setuptools>=11.3->cryptography)

**Comment by rambo-msft** [comment]
Hi @michaelseto ,
If you haven't figured it out already,
`pip install Django --upgrade`.
Feel free to open this back up if you need more assistance and/or still running into issues.
