### ISSUE TITLE
Create blob from X fails with timeout error

### ISSUE THREAD

**Issue by denisgarci** [Azure/azure-storage-python#245]
Hi,

I'm trying to upload a bunch of CSV to Azure Blob Storage using this library and I'm having the following exception: `AzureException: ('Connection aborted.', timeout('The write operation timed out',))`.

I tried every  `create_from_blob_from_*` method and I get the same error. I also changed the name of the blob each time (I thought I was having the following issue: https://github.com/Azure/azure-batch-samples/issues/43).

I can upload without any issue using Azure Storage Explorer. The file is not huge (51MiB).

Any help to further investigate this issue would be appreciated! 

Thanks,

Denis

**Comment by rambo-msft** [comment]
Hi @denisgarci ,
Were you able to resolve this issue?
