### ISSUE TITLE
FR: better nav/toc in read the docs 

### ISSUE THREAD

**Issue by zfrenchee** [Azure/azure-storage-python#251]
It's pretty hard to navigate the documentation largely because the pages are long and each method on those long pages isn't in the TOC, meaning you need to scroll to find it (I think). It would be nice if those methods could appear on the left somehow. 

<img width="1154" alt="screen shot 2017-01-13 at 3 58 43 pm" src="https://cloud.githubusercontent.com/assets/2761597/21945430/3b601908-d9a9-11e6-897d-38dbf132a97e.png">

**Comment by rambo-msft** [comment]
Yes, I agree that can be very helpful for navigation. I'll look into see what can be done on that front.
Thanks for the feedback!

**Comment by zezha-msft** [comment]
Unfortunately there doesn't seem to be much that we could do. For the moment you could rely on Ctrl+f to find the methods 😃
