### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by aggFTW** [Azure/azure-storage-python#255]
Hello, when will a v1.0 be released? We are developing an app but need to take a dependency on a stable library.

Thanks!

**Comment by rambo-msft** [comment]
Hi @aggFTW, 
While I wish I could give you a clear answer, there are still many features and a considerable amount of stress/performance that needs to be completed before we release v1.0/GA. However, It is something we are making great progress towards, we'll be sure to keep the community up-to-date when have a more definitive timeline.

**Comment by aggFTW** [comment]
Do you have a timeline for when you'd have a timeline? :)
