### ISSUE TITLE
Wrong Signature String generation because of missing content-type header

### ISSUE THREAD

**Issue by raphaeljoie** [Azure/azure-storage-python#256]
I use this package with Blobxfer and I get an authorization error on every call. I use PUT bloc and PUT block list endoints.

The reason is that the Signature String generated by Azure package uses an empty content-type header since there is no default value. Here is how headers values are declared in _put_block
`
request.headers = {
    'x-ms-lease-id': _to_str(lease_id)
}
`

but it seems that the Azure api uses a default value (= "application/x-www-urlencoded") for this header when empty. It falls to an signed signature miss match. The solution would be to set a default Content-Type header for every calls where a default value is used API side when computing the signature

`
request.headers = {
    'x-ms-lease-id': _to_str(lease_id),
    'content-type': 'application/octet-stream'
}
`

**Comment by raphaeljoie** [comment]
Hey @rambo-msft, could you check this and the bugfix purposed ? I will put in production a server that uses this bugfix and I'd like to have a confirmation that my solution is stable

**Comment by rambo-msft** [comment]
Hi @raphaeljoie ,
I am trying to better understand this scenario, could you elaborate on how you are using Blobxfer and this library.

> but it seems that the Azure api uses a default value

Can you also clarify where this is happening? i.e. where  ` application/x-www-urlencoded` is being inserted.

**Comment by rambo-msft** [comment]
If you're still having issues feel free to open this back up.
