### ISSUE TITLE
IndexError during exception handling

### ISSUE THREAD

**Issue by danmilon** [Azure/azure-storage-python#259]
Here https://github.com/Azure/azure-storage-python/blob/master/azure/storage/storageclient.py#L248 its not certain that the exception has any args. For example

```
>>> try:
...     raise Exception()
... except Exception as exc:
...     print(exc.args[0])
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
Exception

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
IndexError: tuple index out of range
```

**Comment by rambo-msft** [comment]
Thanks for pointing this out @danmilon , it's something I will be reworking, same as #261 .

**Comment by rambo-msft** [comment]
Hi @danmilon ,
This is fixed in the new release. Thanks!
