### ISSUE TITLE
Index error "tuple out of range" during exception handling

### ISSUE THREAD

**Issue by saherahwal** [Azure/azure-storage-python#261]
For the class azure/storage/storageclient.py in line raise 248 at statement:

AzureException('{}: {}'.format(ex.__class__.__name__, ex.args[0]))

ex.args[0] is not valid and the exception thrown is index out of range. I was getting timeout exceptions actually and these were not caught properly.

**Comment by rambo-msft** [comment]
Thanks @saherahwal , will investigate and address this with one of the upcoming releases.

**Comment by rambo-msft** [comment]
Hi @saherahwal ,
We have addressed with our latest release.
Thanks!
