### ISSUE TITLE
Exception handling with create_blob_from_path

### ISSUE THREAD

**Issue by michaelseto** [Azure/azure-storage-python#263]
If for some reason the create_blob_from_path method runs into issues, what would be the proper way to handle the exception? As in, when you are writing your 'except' block, it would be except __??what??__ as e: ? I want to be able to handle that exception when a blob upload fails so it can email me via sendmail so I know a backup that is attempting to be offloaded to Azure storage has failed.

Thank you!

**Comment by xclientdev-msft** [comment]
Hi @michaelseto ,

> As in, when you are writing your 'except' block, it would be except ??what?? 

You'll want to except `AzureException`, which is what we use to encapsulate all HTTP/Service related errors.
