### ISSUE TITLE
block blobs not supported

### ISSUE THREAD

**Issue by dfernan** [Azure/azure-storage-python#264]
Hi,

If I try:

`block_blob_service.create_blob_from_bytes(container_name, blob_name, data)`

I get an error saying:
```
azure.common.AzureHttpError: Block blobs are not supported.
<?xml version="1.0" encoding="utf-8"?>
<Error><Code>BlobTypeNotSupported</Code><Message>Block blobs are not supported.
```

Do you have any suggestions on how to write to a premium account using this python SDK?

NOTE: This is related to this issue (I got sent here from this post):
https://github.com/Azure/azure-cli/issues/977#issuecomment-280393859

**Comment by pemari-msft** [comment]
Premium Storage only supports page blobs. You'll want to use the page_blob_service.
