### ISSUE TITLE
delete_blob fails if the blob has '.' in the name

### ISSUE THREAD

**Issue by toddysm** [Azure/azure-storage-python#272]
It seems that delete_blob doesn't urlencode the name of the blob before sending to the REST API. If the name of the blob has a dot in it (.) the following call fails:

`block_blob_service.delete_blob('mycontainer', 'mydotted.blob')`

However, the following call succeeds:

`block_blob_service.delete_blob('mycontainer', urllib.quote('mydotted.blob'))`

Creating a blob with a dot in the name is not a problem though.

**Comment by rambo-msft** [comment]
HI @toddysm,
I could not repro this on my end, which version of the storage library are you using?
If you're using urllib.quote, I am assuming you're using python 2.7.x.
I tested locally and urllib.quote did not escape the '.' character as it's not part of reserved URL characters that need to be percent encoded. I am curious how that is affecting your results.

Could you update your requests library as well and see if you still run into this problem.

Thanks!

**Comment by toddysm** [comment]
I was using azure-storage 0.33.0. After upgrading to 0.34.0 I am also not able to repro the issue.

**Comment by rambo-msft** [comment]
@toddysm ,
Definitely strange, but I'm glad upgrading resolved your issue!
