### ISSUE TITLE
StorageClient.location_mode does not support 'PrimaryThenSecondary'

### ISSUE THREAD

**Issue by FedorRomanov** [Azure/azure-storage-python#279]
Currently, StorageClient.location_mode support only `PRIMARY` and `SECONDARY` values, see below
>    :ivar LocationMode location_mode:
>         The host location to use to make requests. Defaults to LocationMode.PRIMARY.
>         Note that this setting only applies to RA-GRS accounts as other account 
>         types do not allow reading from secondary. If the location_mode is set to 
>         LocationMode.SECONDARY, read requests will be sent to the secondary endpoint. 
>         Write requests will continue to be sent to primary.

However, according to MSFT docs, there must be `PrimaryThenSecondary` and `SecondaryThenPrimary` values, check https://docs.microsoft.com/en-us/azure/storage/storage-designing-ha-apps-with-ragrs 

> If you are using the storage client library to access RA-GRS data, you can specify the retry behavior of a read request by setting a value for the LocationMode property to one of the following:
> PrimaryOnly (the default)
> PrimaryThenSecondary
> SecondaryOnly
> SecondaryThenPrimary

Pls, add support for missing `PrimaryThenSecondary` and `SecondaryThenPrimary` values in Python SDK

**Comment by rambo-msft** [comment]
Hi @FedorRomanov ,
 Thanks we we will look into adding this for our next release.

**Comment by rambo-msft** [comment]
@FedorRomanov ,
If you look at our [sample](https://github.com/Azure/azure-storage-python/blob/master/samples/advanced/client.py#L60 ) on retries, we go over how to achieve this functionality.
