### ISSUE TITLE
TableService commit_batch doesn't work on a storage emulator.

### ISSUE THREAD

**Issue by daigok** [Azure/azure-storage-python#280]
I'm using Azure Storage Emulator 5.1.0.0 and azure storage python 0.34.0. If I use azure table storage (not a storage emulator), it works perfectly. However, the same code doesn't work on a storage emulator. Also if I don't use commit_batch, it works fine. 

The error of commit_batch is following:
`<?xml version="1.0" encoding="utf-8"?><error xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><code>InvalidInput</code><message xml:lang="ja-JP">0:The URI \'http://127.0.0.1:10002/IpAddresses\' is not valid since it is not based on \'http://127.0.0.1:10002/devstoreaccount1/\'.RequestId:c8797134-cadb-4d9a-bc10-269a93fc21fbTime:2017-04-01T02:59:26.5195850Z</message></error>`

**Comment by zezha-msft** [comment]
Hi @daigok, sorry for the late reply. I have a fix for this and will push it out with our next release. Thanks for bringing this to our attention! 😃

**Comment by jofriedm-msft** [comment]
As a workaround I believe you can use the connection_string and don't pass anything in for the account_name and account_key

connection_string = "TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=="

**Comment by zezha-msft** [comment]
@daigok It has been fixed in the new release [0.35.0](https://github.com/Azure/azure-storage-python/releases/tag/v0.35.0). 😃
