### ISSUE TITLE
'QueueMessage' object has no attribute 'content'

### ISSUE THREAD

**Issue by drcrook1** [Azure/azure-storage-python#286]
Every samples follows this setup:

    queue_service = QueueService(account_name=STORAGEACCOUNT, account_key=STORAGEKEY)
    queue_service.create_queue('abc')
    while True:
        messages = queue_service.get_messages('abc')
        for message in messages:
            print(message.content)
            queue_service.delete_message('abc', message.id, message.pop_receipt)

Only thing is; it generates the error above.

**Comment by jofriedm-msft** [comment]
Hi @drcrook1, after creating the queue you will need to populate the queue with messages.

ie before the while statement you can put:
queue_service.put_message('abc', u'message1')
queue_service.put_message('abc', u'message2')
etc
