### ISSUE TITLE
Syntax error in _convert_json_to_entity(entity, property_resolver)

### ISSUE THREAD

**Issue by likel** [Azure/azure-storage-python#289]
Hi, 

I have a problem about the function:
`def _convert_json_response_to_entities(response, property_resolver, require_encryption,
                                       key_encryption_key, key_resolver):
    ''' Converts the response to tables class.
    '''
    if response is None or response.body is None:
        return None

    entities = _list()

    entities.next_marker = _get_continuation_from_response_headers(response)

    root = loads(response.body.decode('utf-8'))

    if 'value' in root:
        for entity in root['value']:
            entity = _decrypt_and_deserialize_entity(entity, property_resolver, require_encryption, 
                                           key_encryption_key, key_resolver)
            entities.append(entity)

    else:
        entities.append(_convert_json_to_entity(entity, 
                                             property_resolver))

    return entities`

in azure-storage-python/azure/storage/table/_deserialization.py. The code 
`    else:
        entities.append(_convert_json_to_entity(entity, 
                                             property_resolver))` 
try to convert a json to an entity, but I'm curious about where the `entity` comes from because my IDE reports an error here.  Thanks.

**Comment by rambo-msft** [comment]
Hi likel,
Good point. `entity` doesn't appear to be populated in the else clause path, interestingly enough this hasn't really manifested as a bug suggesting that path is rarely taken.

I can resolve this in our next release, but most IDEs typically won't block you from running this.

Thanks!

**Comment by zezha-msft** [comment]
@likel Thanks for bringing this to our attention. 😄 It has been fixed in the new release [0.35.0](https://github.com/Azure/azure-storage-python/releases/tag/v0.35.0).
