### ISSUE TITLE
Python3-pip install fails due to invalid (dos) character

### ISSUE THREAD

**Issue by brian-l-coker** [Azure/azure-storage-python#291]
Running python3-pip install azure produces this error:

Downloading/unpacking azure-storage==0.33.0 (from azure)
  Running setup.py egg_info for package azure-storage
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/tmp/pip-build-root/azure-storage/setup.py", line 1
        ﻿#!/usr/bin/env python
          ^
    SyntaxError: invalid character in identifier
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/tmp/pip-build-root/azure-storage/setup.py", line 1

    ﻿#!/usr/bin/env python

      ^

SyntaxError: invalid character in identifier

I ran a dos2unix command on the setup.py and that appears to have solved the problem

**Comment by rambo-msft** [comment]
@brian-l-coker 
Do you mind telling me your pip version? Generally this indicates a fail in parsing the BOM of this file which can happen with older versions of pip. 
I cannot repro this exactly, but glad dos2unix did the trick.

**Comment by brian-l-coker** [comment]
Hi - looks like I had a really old version of pip. This problem is resolved. Thanks for your help!
