### ISSUE TITLE
get_blob_metadata() return lower case

### ISSUE THREAD

**Issue by silencev** [Azure/azure-storage-python#296]
The metadata of blob file is case sensitive in Azure Storage Explorer, however,
using **get_blob_metadata()** will return lower key name.
after checking the code, I found [this line](https://github.com/Azure/azure-storage-python/blob/master/azure/storage/_http/httpclient.py#L120) of **httpclient.py** using **lower()**.
And makes the key I get is all lower case.

Is it for any particular purpose?

**Comment by rambo-msft** [comment]
Hi @silencev ,
It may be persistent behavior we present in our other libraries, but I see no reason why this can't be addressed in our next release (esp. if that's the behavior in Storage Explorer.) 
Will look into it further, thanks!

**Comment by zezha-msft** [comment]
Hi @silencev, this change will go out soon with the next major version release. 😃

**Comment by zezha-msft** [comment]
This was fixed in release 1.0.0 of the blob package.
