### ISSUE TITLE
Queue service cannot delete message after it has been updated

### ISSUE THREAD

**Issue by j08lue** [Azure/azure-storage-python#300]
After updating (with [`update_message`](https://github.com/Azure/azure-storage-python/blob/629ad29caf9437dc3f4f0a35ba345351ebf49298/azure/storage/queue/queueservice.py#L925)) the `visibility_timeout` of a message, I cannot delete it.

The issue is apparently not that the message to delete is invisible, because when I `get_messages` with a `visibility_timeout` and delete within that timeout, it works.

Here is a minimal working example:

**This works:**
```python
testq = 'mytestq'
queue_service.put_message(testq, u'hello')
for msg in queue_service.get_messages(testq, visibility_timeout=5):
    queue_service.delete_message(testq, msg.id, msg.pop_receipt)
```

**But this fails:**
```python
testq = 'mytestq'
queue_service.put_message(testq, u'hello')
for msg in queue_service.get_messages(testq, visibility_timeout=5):
    queue_service.update_message(testq, msg.id, msg.pop_receipt, visibility_timeout=5)
    queue_service.delete_message(testq, msg.id, msg.pop_receipt)
```
```
AzureMissingResourceHttpError: The specified message does not exist.
```

Why can't I delete a message after updating it?

**Comment by zezha-msft** [comment]
Hi @j08lue,

I apologize for the late response. Here is why your delete request is failing:

When you perform an update_message operation with a visibility_timeout, another message object is returned with a new pop_receipt. Essentially, every time you set the visibility_timeout and hide the message from others, you get a pop_receipt from the service to guarantee that yourself still have visibility to the message within the timeout. So here is what you could do:

```python
list_result1 = self.qs.get_messages(queue_name, visibility_timeout=5)
message = self.qs.update_message(queue_name,
    list_result1[0].id,
    list_result1[0].pop_receipt,
    visibility_timeout=5)
self.qs.delete_message(queue_name, list_result1[0].id, message.pop_receipt)
```

I would to point out that the new `message` object returned contains only a new pop_receipt and not the message id. Please let me know if you have any other question.

**Comment by j08lue** [comment]
Thanks for the explanation, @zezha-msft.

**Comment by abhics1002** [comment]
I am also facing this issue, however, it's doesn't happen always. I see in our production workload that for about 5% of the request it fails after updating the message. and while remaining times the delete message passed without using the new pop receipt.
