### ISSUE TITLE
Unable to authenticate with SAS token

### ISSUE THREAD

**Issue by alechewitt** [Azure/azure-storage-python#301]
Hi, 
I am having trouble authenticating with an SAS token. The code I am using looks like this:
    
    qs = QueueService(account_name='myaccount...', sas_token='?sv=2016-05-31&ss=bfq...`)
    queue_meta = qs.get_queue_metadata('myqueue')

However I keep receiving this error:
    
    azure.common.AzureHttpError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
    <?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
    RequestId:c8d45fa9-0003-0084-3d51-db564f000000
    Time:2017-06-02T03:39:10.4751869Z</Message><AuthenticationErrorDetail>sv is mandatory. Cannot be empty</AuthenticationErrorDetail></Error>

When I try the same thing with the `account_key` argument the code works fine. Just wondering if there is an issue authenticating with an SAS token or if you can see an issue with my code above.

I have verified that the sas token is correct by connecting to the queue through the Microsoft Azure Storage Explorer.

Thanks

**Comment by alechewitt** [comment]
Just figured this issue out.

The SAS token should not begin with the `?` even though this is how it is provided in the web interface.

So it should be something like: `sas_token='sv=2016-05-31&ss=bfq...'` rather than `sas_token='?sv=2016-05-31&ss=bfq...'`

**Comment by zezha-msft** [comment]
@alechewitt Thanks for solving it yourself! 👍
