### ISSUE TITLE
Returns status date for blob upload method

### ISSUE THREAD

**Issue by troydai** [Azure/azure-storage-python#303]
Relat to: https://github.com/Azure/azure-cli/issues/1566

Currently, the API for blob upload doesn't return anything after execution on the contrary to the blob download API.

**Comment by jofriedm-msft** [comment]
@troydai , thanks for pointing this out. It looks like we are being inconsistent with this and only return the etag and lmt for the create_blob() for page and append blocks. I believe we can and should be returning blob of these properties for all create_from_*() as well. I will make these changes and add some tests to verify.

**Comment by zezha-msft** [comment]
@troydai  This has been added in the new release [0.35.0](https://github.com/Azure/azure-storage-python/releases/tag/v0.35.0).
