### ISSUE TITLE
NameError: name 'block_blob_service' is not defined

### ISSUE THREAD

**Issue by arvindrajaj** [Azure/azure-storage-python#308]
I have installed the latest version of azure. My azure-storage version is 0.34.3. It shows NameError: name 'block_blob_service' is not defined. What should I do.?

**Comment by zezha-msft** [comment]
Hi @arvindrajaj, could you please provide a bit more context? 

You can also refer to this [sample](https://github.com/Azure/azure-storage-python/blob/master/samples/blob/block_blob_usage.py) which shows how to import and use the block blob service.

Please let me know if you're still encountering problems.

**Comment by zezha-msft** [comment]
Closing due to lack of response.

**Comment by arvindrajaj** [comment]
hey, it working fine. Thank you for the sample
