### ISSUE TITLE
retry of a failed chunk upload with a SAS token adds the token a second time making it invalid

### ISSUE THREAD

**Issue by bjoernmeier** [Azure/azure-storage-python#313]
Hi,

we are uploading files with a size of ~4GB with multiple connections:

    blob_service = BlockBlobService(account_name=<AZURE_ACCOUNT_NAME>, sas_token=<AZURE_SHARED_ACCESS_SIGNATURE>)
    blob_service.create_blob_from_path(container, file_name, path, max_connections=10)

During this it happens from time to time that HTTP requests are failing and then retried.
But also all retries are failing as well resulting in a failing create_blob_from_path with such an error:

    <?xml version='1.0' encoding='utf-8'?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\\nRequestId:64598a84-0001-0139-2864-e0c69d000000\\nTime:2017-06-08T14:35:08.7026769Z</Message><AuthenticationErrorDetail>sr is mandatory. Cannot be empty</AuthenticationErrorDetail></Error>

With help of the Azure support and then some debugging in https://github.com/Azure/azure-storage-python/blob/master/azure/storage/_http/httpclient.py#L105 we found that the SAS token is appended a second time to the request url. This makes the SAS token invalid and results in the authentication error.

I could identify where this happens but if this can be located the fix might be simple.

**Comment by zezha-msft** [comment]
Hi @bjoernmeier, you seem to be encountering this [issue](https://github.com/Azure/azure-storage-python/issues/297) that we have already [fixed](https://github.com/Azure/azure-storage-python/commit/2069b80b20eeda29ebd748c2fbe5a0acc10b8965) in the latest release 0.34.3. Could you please try again with the latest version? 

Please let me know if you still sees it. Thanks!

**Comment by bjoernmeier** [comment]
I am running a test for a view hours now and it looks fine with 0.34.3. It was bad luck that we deployed our service with previous version shortly before 0.34.3 was released.
Thank you

**Comment by zezha-msft** [comment]
@bjoernmeier Sounds good! I'm glad it worked out. 👍
