### ISSUE TITLE
SAS Key in Python SDK differs from C# by a leading '?'

### ISSUE THREAD

**Issue by crwilcox** [Azure/azure-storage-python#314]
`var sasToken = share.GetSharedAccessSignature(sharedAccessFilePolicy);` in c# will provide a sas token but with a '?' at the front.

The python equivalent, `sas_token = fs.generate_share_shared_access_signature(FILE_SHARE_NAME, expiry=expiry, permission=file.models.SharePermissions(read=True, write=True, delete=True, list=True))` does not.

The issue lies in that if you try to use the C# key, the python sdk fails. Simply trimming the leading '?' allows it to work.

**Comment by zezha-msft** [comment]
@crwilcox Thanks for bringing this to our attention. After discussing it with my colleagues, we concluded that the Python library actually has the correct behavior. There is no reason why a "?" needs to be added to the SAS token, besides making it easier to copy-paste. We will see how to make the .net library consistent. Thank you! 😃
