### ISSUE TITLE
create_queue example doesn't work

### ISSUE THREAD

**Issue by apengwin** [Azure/azure-storage-python#316]
I created a storage account, and executed the following code.

`queue_service = QueueService(account_name='apengwin', account_key='MY_KEY_HERE')`
queue_service.create_queue('taskqueue')`

but this threw the following exception:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/allanpeng/azure/venv/lib/python2.7/site-packages/azure/storage/queue/queueservice.py", line 524, in create_queue
    response = self._perform_request(request, parser=_return_request)
  File "/Users/allanpeng/azure/venv/lib/python2.7/site-packages/azure/storage/storageclient.py", line 279, in _perform_request
    raise ex
azure.common.AzureException: ConnectionError: HTTPSConnectionPool(host='apengwin.queue.core.windows.net', port=443): Max retries exceeded with url: /taskqueue (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107711590>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))
`

Am i missing any steps?

**Comment by zezha-msft** [comment]
@apengwin Hi, it looks like your account was not created properly, as the DNS lookup fails. 

Please verify that you have the correct account name (and key). A good way to do this is using the [Azure Storage Explorer](http://storageexplorer.com/). If you could log in and create queues in the Storage Explorer, then it should work with the Python library. If not, please let me know and I'll reopen this issue. Thanks! 😄
