### ISSUE TITLE
Putting message in queue silently fails to add content with Python 3.4

### ISSUE THREAD

**Issue by themaxx75** [Azure/azure-storage-python#32]
Using `queue_service.put_message('queue', 'message')` fails using Python 3.4
Instead, it places an empty message in the queue. 

edit:
This is using the example from: http://azure-storage.readthedocs.org/en/latest/queue.html?highlight=put_message

**Comment by emgerner-msft** [comment]
I'm not able to reproduce that with 3.4 and the code from the docs. Specifically I ran the below:
```
queue_service.create_queue('taskqueue')
queue_service.put_message('taskqueue', 'Hello World')
messages = queue_service.get_messages('taskqueue')
queue_service.delete_queue('taskqueue')
```
On Windows I used Fiddler to verify what was being sent via HTTP and I also looked at messages under the debugger. I can see the message being sent to the server and that messages[0].message_text contains 'Hello World'. How are you checking the message text?

**Comment by themaxx75** [comment]
Maybe I should have added that I get it to work by using Python 2.7, and `'Hello World'.encode('Base64')`, but only in that case. Without first encoding in Base64, it also produces an empty message. I see the messages in the queue in all cases, but its "message" is empty. I check by using Azure Storage Explorer, on an existing queue. The app that takes messages from that queue also sees nothing in what is queued when using Python 3.4. 
Any suggestion as to what I could try?

Also, this is executed under an Azure VM running Ubuntu Server 14.04

**Comment by huguesv** [comment]
When you tried Base64 encoding on Python 3.4, was it like this (which works for me):
```
from base64 import b64encode

service.create_queue('testqueue1')
encoded_msg = b64encode(b'bonjour world')
encoded_msg_txt = encoded_msg.decode()
service.put_message('testqueue1', encoded_msg_txt)
```

**Comment by themaxx75** [comment]
You just solved my issue! A big thank you for the quick help.
