### ISSUE TITLE
KeyError: accept / accept-encoding in _get_blob

### ISSUE THREAD

**Issue by dhollsten** [Azure/azure-storage-python#322]
**Traceback:**
File "/env/local/lib/python2.7/site-packages/azure/storage/blob/baseblobservice.py", line 1932, in get_blob_to_stream
_context=operation_context)
File "/env/local/lib/python2.7/site-packages/azure/storage/blob/baseblobservice.py", line 1659, in _get_blob
operation_context=_context)
File "/env/local/lib/python2.7/site-packages/azure/storage/storageclient.py", line 279, in _perform_request
raise ex

Happens infrequently with an incomplete traceback.

**pip freeze | grep azure**
azure==2.0.0
azure-batch==3.0.0
azure-common==1.1.6
azure-datalake-store==0.0.12
azure-graphrbac==0.30.0
azure-keyvault==0.3.5
azure-mgmt==1.0.0
azure-mgmt-authorization==0.30.0
azure-mgmt-batch==4.0.0
azure-mgmt-cdn==0.30.3
azure-mgmt-cognitiveservices==1.0.0
azure-mgmt-compute==1.0.0
azure-mgmt-containerregistry==0.2.1
azure-mgmt-datalake-analytics==0.1.6
azure-mgmt-datalake-nspkg==2.0.0
azure-mgmt-datalake-store==0.1.6
azure-mgmt-devtestlabs==2.0.0
azure-mgmt-dns==1.0.1
azure-mgmt-documentdb==0.1.3
azure-mgmt-iothub==0.2.2
azure-mgmt-keyvault==0.31.0
azure-mgmt-logic==2.1.0
azure-mgmt-monitor==0.2.1
azure-mgmt-network==1.0.0
azure-mgmt-nspkg==2.0.0
azure-mgmt-rdbms==0.1.0
azure-mgmt-redis==4.1.0
azure-mgmt-resource==1.1.0
azure-mgmt-scheduler==1.1.2
azure-mgmt-sql==0.5.3
azure-mgmt-storage==1.0.0
azure-mgmt-trafficmanager==0.30.0
azure-mgmt-web==0.32.0
azure-nspkg==2.0.0
azure-servicebus==0.21.1
azure-servicefabric==5.6.130
azure-servicemanagement-legacy==0.20.6
azure-storage==0.34.3

**Comment by zezha-msft** [comment]
Hi @dhollsten, thanks for bringing this to our attention. Is there any other context that you could provide us? Is there any pattern in when you encounter this error?

**Comment by dhollsten** [comment]
Hi @zezha-msft, sure!

Basically we are using a ThreadPool to call a function which download images for further processing. The function is retried using an exponential backoff policy. We have been receiving a fair amount of HTTP 503s lately which might be related.
```         
def download(container, blob):
    stream = BytesIO() 
    bs = self._get_container_access_blob_service(container)
    bs.get_blob_to_stream(
        container,
        blob,
        stream,
        max_connections=20,
        timeout=30)
    return stream

pool = ThreadPool(processes=20)
pool.imap(download, [...], chunksize=20) 
```

**Comment by zezha-msft** [comment]
Hi @dhollsten, receiving many HTTP 503s means that you are very likely making too many requests per second for the storage account, and are being throttled by the service. You could read more about this [here](https://docs.microsoft.com/en-us/azure/storage/storage-scalability-targets). You could also use [Storage Analytics](https://docs.microsoft.com/en-us/azure/storage/storage-analytics) to view the errors. 

It is somewhat hard to investigate this issue without a reliable repro. Could you please try to limit your requests/sec and see if this issue still occurs? Thank you! 😄

**Comment by zezha-msft** [comment]
@dhollsten  Any update?
