### ISSUE TITLE
[Feature request] Add container size and number of blob in the container to ContainerProperties

### ISSUE THREAD

**Issue by thanhnhut90** [Azure/azure-storage-python#326]
Hi guys,

Currently the ContainerProperties has `last_modified, etag, lease, and public_access`. For audit purpose, we would like to get the total file count and the total size of a given container. As of now, the only way to do it is to list_blobs and then manually count each blob and calculate the size. We have a good amount of blobs in a given container and also many containers. Yesterday, it took almost 200 calls to list_blobs to get all blob in the container since each call returned the maximum of 5000 records. Would it be possible to add the file count and container size to ContainerProperties for ease of access?

Thanks

**Comment by zezha-msft** [comment]
Hi @thanhnhut90, thanks for reaching out. I will bring your request to the team and keep this open to track it. 😄

**Comment by zezha-msft** [comment]
@thanhnhut90 Unfortunately it is not possible to add this feature due to backend limitations. Sorry! 😭
