### ISSUE TITLE
create_blob_from_path returns None instead of some meaningful data

### ISSUE THREAD

**Issue by troydai** [Azure/azure-storage-python#332]
From: https://github.com/Azure/azure-cli/issues/1566

In download scenario, once blob is downloaded a data structure is returned from the API, therefore, CLI can output some results in the console. However, for upload, the returned value is `None`. we hope some confirmation data is returned so as to keep download and upload pattern similar.

**Comment by zezha-msft** [comment]
Hi @troydai, we have already [fixed](https://github.com/Azure/azure-storage-python/commit/f014c982f308f738d2e2455f43e0c96f5b9bff99) this in the latest version 0.35.1. In fact, it was in response to this [issue](https://github.com/Azure/azure-storage-python/issues/303) that you created. 😃

**Comment by troydai** [comment]
Ugr... sorry for the duplication.

**Comment by zezha-msft** [comment]
@troydai No worries 😺
