### ISSUE TITLE
Feedback needed: library split!

### ISSUE THREAD

**Issue by zezha-msft** [Azure/azure-storage-python#333]
Dear community,

We are currently working on splitting the library into different services, thus 4 new packages:
- azure-storage-blob
- azure-storage-file
- azure-storage-queue
- azure-storage-table

The split allows users to install only the service that they need. Anything that was previously directly under `azure.storage` are now in the new package `azure-storage-common`, which is a requirement for the new packages mentioned above. For example, `azure.storage.CloudStorageAccount` becomes `azure.storage.common.CloudStorageAccount`. The current `azure-storage` meta-package will be deprecated after this change.

The change is sitting on this [branch](https://github.com/Azure/azure-storage-python/tree/split-library), please take a look if you are interested. Any feedback is welcome! 😄  **Note: the new packages are not published to pypi yet.**

You can do `python3 build_packages.py all` to have all the packages built and put under the directory ./dist. Please follow the readme for more detailed instructions.

**Comment by lmazuel** [comment]
Thanks for this @zezha-msft ! I take a look asap.

**Comment by lmazuel** [comment]
@zezha-msft I cloned the branch, built the wheel and LGTM :)

@derekbekoe would you like to check too?

**Comment by zezha-msft** [comment]
@lmazuel Thanks for taking a look! 😸
