### ISSUE TITLE
insert_or_replace_entity(tableservice) raise an error when the RowKey is an empty string

### ISSUE THREAD

**Issue by wellDan28** [Azure/azure-storage-python#334]
Even though it can be done. I did it before with the .net WindowsAzure.Storage nuget.
Of course this issue is related to all of the table 'insert' actions.

[https://docs.microsoft.com/en-us/rest/api/storageservices/designing-a-scalable-partitioning-strategy-for-azure-table-storage](https://docs.microsoft.com/en-us/rest/api/storageservices/designing-a-scalable-partitioning-strategy-for-azure-table-storage#yyy)

**Comment by zezha-msft** [comment]
Hi @wellDan28, thanks for reaching out! 😄 

This does appear to be an inconsistency. I'll investigate and update this thread. 👍

**Comment by zezha-msft** [comment]
@wellDan28 That'd be awesome! We definitely welcome community input. 👍 

I believe the change should be made [here](https://github.com/Azure/azure-storage-python/blob/master/azure/storage/table/_error.py#L46), please also add some tests to cover the scenarios. 😄

**Comment by wobbie** [comment]
Hi,

I don't want to step on anyone's toes but I have put forward a pull request to fix this issue as it is a blocker on the project I am currently working on.

This is my first PR so please let me know if there are any issues.

Thanks, Rob

**Comment by zezha-msft** [comment]
@wobbie Awesome! Please sign the CLA so that I can merge your PR. 😄

**Comment by wobbie** [comment]
@zezha-msft thanks for the merge. Do you know when then next release will be?

**Comment by zezha-msft** [comment]
Hi @wobbie I don't have the exact date just yet, I'll update this issue once I do.

**Comment by zezha-msft** [comment]
@wobbie  @wellDan28  This has been fixed in 0.36.0. Thank you!! 👍
