### ISSUE TITLE
blob_get_to_path fails on empty blob with storage emulator

### ISSUE THREAD

**Issue by krishnangovindraj** [Azure/azure-storage-python#335]
Hi,
I'm not sure whether this is an issue with the SDK or Windows Azure Storage Emulator ( 5.2.0.0 ) since the issue does not occur when using an actual account. But the blob is showing up when using list_blobs and the 'Microsoft Azure Storage Explorer' tool opens it fine so I'm posting here anyway.

*Issue*: `blob_service.get_blob_to_path(container_name,** blob_name, output_path)` fails when trying to download an empty blob ( 0 bytes ) *using the storage emulator*.

*Error message:*
`<?xml version="1.0" encoding="utf-8"?>
    <Error>
        <Code>BlobNotFound</Code>
        <Message>
            The specified blob does not exist.
            RequestId:cb2dd817-f163-40b0-b1a2-df5149cc7bbc
            Time:2017-08-10T04:54:34.3227512Z
        </Message>
</Error>`

*Minimal reproducible example.*

`
from azure.storage import CloudStorageAccount

CONTAINER = 'testcontainer'
EMPTYBLOB = 'emptyblob'
FULLBLOB = 'fullblob'
OUTPUTPATH = "local-testblob"

blob_service = CloudStorageAccount( is_emulated=True ).create_block_blob_service()
blob_service.create_container(CONTAINER)

try:
    blob_service.create_blob_from_text(CONTAINER, FULLBLOB, "I am full!")
    blob_service.get_blob_to_path(CONTAINER, FULLBLOB, OUTPUTPATH) # Should go boom
except Exception as e:
    print( "Full blob exception:" + str(type(e)) )

try:
    blob_service.create_blob_from_text(CONTAINER, FULLBLOB, "")
    blob_service.get_blob_to_path(CONTAINER, EMPTYBLOB, OUTPUTPATH) # Should go boom
except Exception as e:
    print( "Empty blob exception:" + str(type(e)) )
`

**Comment by zezha-msft** [comment]
Hi @krishnangovindraj, thank you so much for bringing this to our attention! 👍 

I will try to reproduce this on my end, and forward this issue to my colleagues who maintain the emulator. I'll keep this thread updated. 😸

**Comment by zezha-msft** [comment]
This was fixed in release 1.0.0.
