### ISSUE TITLE
Uploading 'empty' blocks to page blobs is wasteful.

### ISSUE THREAD

**Issue by bear454** [Azure/azure-storage-python#341]
Re: `PageBlobService#create_blob_from_stream`

When a page blob is provisioned, the content is a stream of 0s. Therefore, when uploading a page blob, any block that is all zeros does not need to be uploaded, it can simply be skipped.

Most fixed-length VHD images are _mostly_ empty blocks, so uploading all those zeros represents a huge waste of time and bandwidth.

Our optimum solution for dealing with this in [azurectl](https://github.com/SUSE/azurectl/blob/master/azurectl/storage/page_blob.py) was to load a block from `/dev/zero` and compare it to the current block in the stream. If they are equal... move along to the next block without uploading.

See https://github.com/SUSE/azurectl/blob/master/azurectl/storage/page_blob.py#L50 for example.

And, just for reference, a 30GB openSUSE Leap 42.3 image, contains < 300MB of full blocks. Uploading with the API convenience methods, or `az`, results in an upload of 29.7GB of zeros. o.0

**Comment by zezha-msft** [comment]
@bear454 Thank you so much for the suggestion! We will consider it carefully and update this issue once I have any update. 👍

**Comment by bear454** [comment]
I have a working patch( https://github.com/bear454/azure-storage-python/commit/28318b2cb41fba75d4784fb80259da5f3792966e ) but there are still some outstanding issues, maybe you can help with...

* I don't see anything in the tests that runs at a small enough scope to test the change. Suggestions on how to test?
* There seems to be a code path for patching an existing VHD, and obviously you don't want to skip blocks in that case, so we need to differentiate that code path.

**Comment by zezha-msft** [comment]
Hi @bear454, you should be patching _PageBlobChunkUploader, not _BlobChunkUploader, since we only want the change for page blobs. 

And there should be plenty of tests covering this scenario, such as [this one](https://github.com/Azure/azure-storage-python/blob/master/tests/test_page_blob.py#L609).

**Comment by zezha-msft** [comment]
Hi @bear454, I spoke to my colleagues and we'd love to have this improvement in the library. Would you be interested in submitting a PR for it? If not, I'll add this item to our backlog. Thanks! 😄

**Comment by zezha-msft** [comment]
@bear454, I have added this item to our backlog, thank you for the suggestion!

**Comment by evanrolfe** [comment]
@bear454 FYI this feature has been implemented in commit https://github.com/Azure/azure-storage-python/commit/eb9183a20ba67cdbab868df3241258e93eb3cc3f

**Comment by zezha-msft** [comment]
This was fixed in release 1.0.0 of the blob package.
