### ISSUE TITLE
Check blob upload progress?

### ISSUE THREAD

**Issue by bbirand** [Azure/azure-storage-python#344]
We are using the `azure-storage` Python package in our Django app to upload large files. I found the following documentation for showing the progress via node:
https://github.com/Azure/azure-storage-node/issues/310

What is the analog for doing the same in Python?

Thanks!

**Comment by zezha-msft** [comment]
Hi @bbirand, the [create_blob_from*](http://azure-storage.readthedocs.io/en/latest/ref/azure.storage.blob.blockblobservice.html#azure.storage.blob.blockblobservice.BlockBlobService.create_blob_from_stream) methods take in an argument called progress_callback. 

And [here](https://github.com/Azure/azure-storage-python/blob/master/samples/blob/block_blob_usage.py#L300) is a sample.
