### ISSUE TITLE
Unable to get the block_id for blob block...

### ISSUE THREAD

**Issue by Ashokcs94** [Azure/azure-storage-python#351]
I have 2 GB data.I uploaded to azure block blob storage using "**create_blob_from_path**" .
1) If you are using **create_blob_from_path** to upload large file (it will automatically chunk into 100MB blocks and it automatically set the block_ids for that blocks).

2) I have to upload daily data to block blob.So i used **put_block** method followed by **put_block_list**
with all committed block_ids.
For getting the committed block_id list, i am using **get_block_list** (to get all committed block_ids).

In **get_block_list** method i am getting block_ids ,those are upload by using **put_block** method.

I need the method for getting block_ids(for auto-generated blocks) by using the **create_blob_from_path** method.

**Comment by zezha-msft** [comment]
Hi @Ashokcs94,

1. the chunk size is set using the variable MAX_BLOCK_SIZE on BlockBlobService, by default it is 4MB. You can set it to anything under 100MB.

2. create_blob_from_path chunks up your file and upload the chunks using put_block, and then do a put_block_list to commit all the blocks. You do not need to commit the blocks yourself.

3. get_block_list returns you 2 lists:
- Committed Block List:
    - The list of blocks that have been successfully committed to a given blob with Put Block List.
- Uncommitted Block List:
    - The list of blocks that have been uploaded for a blob using Put Block, but that have not yet been committed. These blocks are stored in Azure in association with a blob, but do not yet form part of the blob.

Please refer to [the doc](http://azure-storage.readthedocs.io/en/latest/ref/azure.storage.blob.blockblobservice.html#azure.storage.blob.blockblobservice.BlockBlobService.get_block_list) for more info. 😄 

Best regards,

Ze

**Comment by Ashokcs94** [comment]
Hi @zezha-msft ,

Thanks . 
" **2.create_blob_from_path chunks up your file and upload the chunks using put_block, and then do a put_block_list to commit all the blocks. You do not need to commit the blocks yourself.** "

If i am upload a file by using **create_blob_from_path** ,  in **get_block_list**  not getting any block_id  lists.

**Comment by zezha-msft** [comment]
@Ashokcs94 What is your question? Do you want to get the committed block ids after using create_blob_from_path to upload a blob? If yes then:

```python
block_lists = self.bs.get_block_list(container_name, blob_name)
```
block_lists.committed_blocks is a list of BlobBlock objects, each with the fields id, size, and state.
