### ISSUE TITLE
Where is put_block_blob_from_path from BaseBlobService?

### ISSUE THREAD

**Issue by michelpf** [Azure/azure-storage-python#357]
Again, was changed the method to send files to new Blob in Azure Storage. I can't decode where is the new implementation. 

Someone can help me, please?

**Comment by zezha-msft** [comment]
Hi @michelpf, what do you mean by "new implementation"?

The methods to upload block blobs are in BlockBlobService, I believe the one you are looking for is [create_blob_from_path](https://github.com/Azure/azure-storage-python/blob/master/azure/storage/blob/blockblobservice.py#L325).

**Comment by michelpf** [comment]
I found it. 👍 

Third time it was changed. Nice to have new features, but not a lot and not with sensitive operations such upload and download. Brokes my code everytime I update the API.

blob_service = BlockBlobService(account_name=ACCOUNT_NAME, account_key=ACCOUNT_KEY)
blob_service.create_blob_from_path(ret["container"], blob_name, arquivo)

**Comment by michelpf** [comment]
Yes @zezha-msft, you're right. I have some codes from months ago and this implementation was changed.
That's nice. Surprised my positively your answer in speed of light! 🥇

**Comment by zezha-msft** [comment]
@michelpf Glad you found it! Btw which version are you upgrading from?

**Comment by michelpf** [comment]
@zezha-msft Since we still not put on production, every time I work with this API I get the latest version. My previous code, that I used to catch some functions probably was on 0.20.
