### ISSUE TITLE
`AccountPermissions` returns the wrong type on `__or__` and `__add__`

### ISSUE THREAD

**Issue by drosseau** [Azure/azure-storage-python#366]
version 0.37.0

Simple fix [here](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-common/azure/storage/common/models.py#L596) and [here](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-common/azure/storage/common/models.py#L599)

**Comment by zezha-msft** [comment]
@drosseau Thank you for bringing up the issue! I'll fix it ASAP.

**Comment by zezha-msft** [comment]
This has been [fixed](https://github.com/Azure/azure-storage-python/commit/6ff6ab567a8cdc20d30151d07c6f2775c24f2bea), and will go out with the next release.

**Comment by zezha-msft** [comment]
This was fixed in azure-storage-common v0.37.1.
