### ISSUE TITLE
Shared Access Signatures don't work with Premium Storage Accounts

### ISSUE THREAD

**Issue by pneumee** [Azure/azure-storage-python#37]
I'm getting the following error message when trying to copy a blob between Premium Storage accounts:

```
<?xml version="1.0" encoding="utf-8"?>
<Error><Code>CannotVerifyCopySource</Code><Message>Could not verify the copy source within the specified time.
RequestId:
Time:2015-09-02T00:14:20.1883717Z</Message></Error>
```

Using version 0.11.1 of the SDK. I've verified that the same blob copy logic works with regular Storage Accounts.

**Comment by emgerner-msft** [comment]
Could you give more info on what you're doing? 

1. Are you copying with SAS or using snapshots? Sample code would be helpful. 
2. Could you include more information on the request? For example, the date/time it was made and the request id would be helpful.

**Comment by emgerner-msft** [comment]
1. Could you include the account name and request id as well as the time? With just time we are not able to trace anything.
2. Could you include sample code? I see SAS in the title but more info like whether you're using snapshots (etc) would be helpful.

**Comment by pneumee** [comment]
Hello emgerner-msft!

The blob I'm currently trying to copy is for an OS Image, which doesn't appear to be a limitation of blob copy operations on Premium Storage accounts based on the link provided. Not using snapshots in this case.

I can't provide a request ID because I'm not getting one back from the API, it errors on this statement in copy_blob:

```
response = self._perform_request(request)
```

As you can see from the exception above, the Request ID is empty. 

Sample pseudocode:

```
source_image_url = generate_sas_for_image(image)
copy_blob(source_image_url, 'vhds-data', 'test-target-blob-name')

###################################################################
def copy_blob(self, source_url, destination_container_name, destination_blob_name):
	
	resp = blob_service.copy_blob(destination_container_name, destination_blob_name, source_url)

	## imagine code to wait for async operation here (error generated on call to copy_blob above anyways)
		
###################################################################
def generate_sas_for_image(self, image_name):

	blob = _get_blob_for_image(image_name)
	return self.generate_sas_for_blob(blob)

###################################################################
def generate_sas_for_blob(self, blob):

	source_container_name, source_blob_name = _get_container_and_blob_names_from_media_link(blob)
	
	sap = self._get_shared_access_policy(azure.storage.BlobSharedAccessPermissions.READ)

	signature = blob_service.generate_shared_access_signature(
		container_name=source_container_name, blob_name=source_blob_name,
		shared_access_policy=sap, sas_version=azure.storage.X_MS_VERSION)

	return blob_service.make_blob_url(source_container_name, source_blob_name, sas_token=signature)
	
###################################################################
@staticmethod
def _get_shared_access_policy(permission):
	date_format = "%Y-%m-%dT%H:%M:%SZ"
	start = datetime.utcnow() - timedelta(minutes=1)
	expiry = start + timedelta(days=1)
	return azure.storage.SharedAccessPolicy(
		azure.storage.AccessPolicy(
			start.strftime(date_format),
			expiry.strftime(date_format),
			permission
		)
	)
```

**Comment by emgerner-msft** [comment]
Looking at the code nothing sticks out to me as a problem at the moment. OS Images shouldn't be an issue but I'm still wondering if there's something going on there. If you could give:
1. an exact date and time (or within 1-2 min range) of when you made a failing request. This should be from within the last day or two.
2. the full URL or account name/container name/blob name 
I can try to check stuff out server side even without request id. This will help us determine where to look next for the problem. If you're uncomfortable posting this here, feel free to email me at emgerner at microsoft dot com, substituting the correct chars for at and dot. 

PS: We are planning on making request id easier to get, for future reference

**Comment by pneumee** [comment]
Hi emgerner-msft,

If you're tracking the internal issue too, I'll stop posting updates here. Thanks!

**Comment by emgerner-msft** [comment]
Latest release (0.20.2) should address this issue. Please give it a try!
