### ISSUE TITLE
Unable to install in Azure Function due to Invalid environment marker: python version < '3'

### ISSUE THREAD

**Issue by jschweda** [Azure/azure-storage-python#370]
Hi There,
I'm trying to install azure-storage-blob in a Function. The readme says 2.7 is supported. The Function is executing 2.7.8 by default.

This is the console output:

> D:\home>D:\Python27\Scripts\pip.exe install azure-storage-blob
> Downloading/unpacking azure-storage-blob
> Downloading/unpacking futures (from azure-storage-blob)
> Downloading futures-3.1.1-py2-none-any.whl
> Downloading/unpacking requests (from azure-storage-blob)
> Downloading/unpacking azure-common>=1.1.5 (from azure-storage-blob)
>   Downloading azure_common-1.1.8-py2.py3-none-any.whl
> Downloading/unpacking python-dateutil (from azure-storage-blob)
> Downloading/unpacking azure-storage-nspkg>=2.0.0 (from azure-storage-blob)
>   Downloading azure_storage_nspkg-2.0.0-py2.py3-none-any.whl
> Downloading/unpacking azure-storage-common>=0.37.0,<0.38.0 (from azure-storage-blob)
> Downloading/unpacking cryptography (from azure-storage-blob)
>   Running setup.py (path:d:\local\temp\pip_build_RD0003FF597869$\cryptography\setup.py) egg_info for package cryptography
>     error in cryptography setup command: Invalid environment marker: python_version < '3'
>     Complete output from command python setup.py egg_info:
>     error in cryptography setup command: Invalid environment marker: python_version < '3'
> 
> ----------------------------------------
> 
> Cleaning up...
> 
> Command python setup.py egg_info failed with error code 1 in d:\local\temp\pip_build_RD0003FF597869$\cryptography
> Storing debug log for failure in D:\home\pip\pip.log

**Comment by zezha-msft** [comment]
Hi @jschweda, this is not a problem with the storage package, please update setuptools and try again. Unfortunately I have no knowledge of the Function, so I could not provide any instruction. Hope you'll fix it! :)

**Comment by lmazuel** [comment]
@jschweda This might help as well:
https://stackoverflow.com/questions/43970307/azure-functions-installing-python-modules-and-extensions-on-consumption-plan/43984890#43984890
