### ISSUE TITLE
Cannot import name 'BaseBlobService'

### ISSUE THREAD

**Issue by mat178** [Azure/azure-storage-python#373]
Hi,

I have a problem importing the class BaseBlobService.
When I try:

`from azure.storage.blob import BaseBlobService`

I get the error:
 `ImportError: cannot import name 'BaseBlobService'`

Other classes, e.g. BlockBlobService work just fine.
However with BaseBlobService I have to import the file baseblobservice.py first and then access the class using baseblobservice.BaseBlobService.

`>>> platform.python_version()
'3.6.2'`
- azure                     2.0.0                     <pip>
- azure-batch               3.0.0                     <pip>
- azure-common              1.1.8                     <pip>
- azure-datalake-store      0.0.17                    <pip>
- azure-graphrbac           0.30.0                    <pip>
- azure-keyvault            0.3.7                     <pip>
- azure-mgmt                1.0.0                     <pip>
- azure-mgmt-authorization  0.30.0                    <pip>
- azure-mgmt-batch          4.0.0                     <pip>
- azure-mgmt-cdn            0.30.3                    <pip>
- azure-mgmt-cognitiveservices 1.0.0                     <pip>
- azure-mgmt-compute        1.0.0                     <pip>
- azure-mgmt-containerregistry 0.2.1                     <pip>
- azure-mgmt-datalake-analytics 0.1.6                     <pip>
- azure-mgmt-datalake-nspkg 2.0.0                     <pip>
- azure-mgmt-datalake-store 0.1.6                     <pip>
- azure-mgmt-devtestlabs    2.0.0                     <pip>
- azure-mgmt-dns            1.0.1                     <pip>
- azure-mgmt-documentdb     0.1.3                     <pip>
- azure-mgmt-iothub         0.2.2                     <pip>
- azure-mgmt-keyvault       0.31.0                    <pip>
- azure-mgmt-logic          2.1.0                     <pip>
- azure-mgmt-monitor        0.2.1                     <pip>
- azure-mgmt-network        1.0.0                     <pip>
- azure-mgmt-nspkg          2.0.0                     <pip>
- azure-mgmt-rdbms          0.1.0                     <pip>
- azure-mgmt-redis          4.1.0                     <pip>
- azure-mgmt-resource       1.1.0                     <pip>
- azure-mgmt-scheduler      1.1.3                     <pip>
- azure-mgmt-sql            0.5.3                     <pip>
- azure-mgmt-storage        1.0.0                     <pip>
- azure-mgmt-trafficmanager 0.30.0                    <pip>
- azure-mgmt-web            0.32.0                    <pip>
- azure-nspkg               2.0.0                     <pip>
- azure-servicebus          0.21.1                    <pip>
- azure-servicefabric       5.6.130                   <pip>
- azure-servicemanagement-legacy 0.20.6                    <pip>
- azure-storage             0.34.3                    <pip>
- azure-storage-blob        0.37.0                    <pip>
- azure-storage-common      0.37.0                    <pip>
- azure-storage-nspkg       2.0.0                     <pip>

**Comment by zezha-msft** [comment]
Hi @mat178, that is the expected behavior since you do not need to use BaseBlobService directly, as BlockBlobService, PageBlobService, and AppendBlobService all inherits from BaseBlobService the common functionalities. 

Please let me know if you have any question. 😃

**Comment by mat178** [comment]
Hi @zezha-msft, thanks for the clarification. 
I ran into an error when using the BlockBlobService.get_blob_to_text() method. That's why I thought I had to use BaseBlobService directly. However, I now realized that the error was caused by a different return value of the method compared to prior the split:

https://github.com/Azure/azure-storage-python/blob/5bd96771065c460b37c7b71554f2ee20e238fe2b/azure-storage-blob/azure/storage/blob/baseblobservice.py#L2251

The method returns the blob object itself instead of the content. 
Is that intended behavior, or should I open another issue because of this?

**Comment by zezha-msft** [comment]
Hi @mat178, that behavior has not change in 2 years, please refer to the [git blame](https://github.com/Azure/azure-storage-python/blame/5bd96771065c460b37c7b71554f2ee20e238fe2b/azure-storage-blob/azure/storage/blob/baseblobservice.py#L2251).

**Comment by mat178** [comment]
Yeah sorry, I was using version 0.20.1 before. 
But I still think that a method that is called "to_text" should return the text and not the object, shouldn't it?

**Comment by zezha-msft** [comment]
Hi @mat178, I agree with you that it is unfortunately counter-intuitive, since what is returned is indeed not what someone reading the method signature expects. But we also want to return the blob properties while getting the content, and the [documentation](https://azure-storage.readthedocs.io/en/latest/ref/azure.storage.blob.baseblobservice.html#azure.storage.blob.baseblobservice.BaseBlobService.get_blob_to_text) makes that part clear.

**Comment by bardiaborhani** [comment]
I imported using the line "from azure.storage.blob import baseblobservice" and in my code I wrote "baseblobservice.BaseBlobService(...)" and it worked.
