### ISSUE TITLE
Azure Blob Access via Proxy using Python

### ISSUE THREAD

**Issue by Balachandar-R** [Azure/azure-storage-python#383]
Hi Team,

1.I just want to know, how to declare and use azure-storage client with proxy settings?
2. Is there any other way to access the contents of the files available in BLOBS via Python SDK or REST API.

Please provide the details.

Thanks,
Balachandar Raju

**Comment by zezha-msft** [comment]
Hi @Balachandar-R, please refer to the [sample](https://github.com/Azure/azure-storage-python/blob/master/samples/advanced/client.py#L114) on how to use proxy.

As for your question about accessing blobs, what are you trying to do exactly? There are several tools that use the SDK to retrieve blobs, one example is [Azure CLI](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest). If you are thinking more about mounting a local drive backed by Azure Storage, there's the [FUSE driver](https://github.com/Azure/azure-storage-fuse). If you could elaborate a bit on your use case, I can perhaps answer this question a bit better. :)

**Comment by zezha-msft** [comment]
@Balachandar-R, ok then, please refer to the [samples](https://github.com/Azure/azure-storage-python/blob/master/samples/blob/block_blob_usage.py#L259) on how to use the SDK for your tasks.
