### ISSUE TITLE
get_blob_to_text() and get_blob_to_bytes()

### ISSUE THREAD

**Issue by Balachandar-R** [Azure/azure-storage-python#387]
Hi team,

I have stored some objects(.txt,docx,.ppt etc) into the blob containers. I am in need of accessing the contents of each files(.txt,.docx,.ppt) using get_blob_to_text() and get_blob_to_bytes() using python.

Using get_blob_to_bytes() 
=================
I can access the text contents as it is from the files and for other files i can access contents is bytes like the following:

![image](https://user-images.githubusercontent.com/8731707/32877435-898aeaa8-cac7-11e7-8a00-fcdc83ad7b9b.png)

Using get_blob_to_text()
==================
If i go with this method to access any files ,i have got the following error.

![image](https://user-images.githubusercontent.com/8731707/32877508-e31b496e-cac7-11e7-9ea2-1f8b71799ef0.png)

Please help us to resolve this issue and suggest me the ways how to access the content as text.

Regards,
Balachandar Raju

**Comment by zezha-msft** [comment]
Hi @Balachandar-R, you need to provide the right encoding when calling get_blob_to_text, please refer to the [sample](https://github.com/Azure/azure-storage-python/blob/master/samples/blob/block_blob_usage.py#L390). This error happens because your data cannot be decoded as 'utf-8'.

**Comment by Balachandar-R** [comment]
Thanks @zezha-msft :)

**Comment by Balachandar-R** [comment]
Hi @zezha-msft ,

Could you please help to give an example in python to access the content of word file available in the azure blob using either get_blob_to_text() or get_blob_to_bytes()?

No idea about what encoding schemes do i need to use to get back the contents of the file available in the BLOBS.

Error Details (While accessing the docx file available in the Blob)
=========================================
Traceback (most recent call last):
  File "TestBlobAccess.py", line 60, in <module>
    blob1 = block_blob_service.get_blob_to_text(CONTAINER_NAME, blob.name)
  File "C:\Anaconda2\lib\site-packages\azure\storage\blob\baseblobservice.py", line 2250, in get_blob_to_text
    blob.content = blob.content.decode(encoding)
  File "C:\Anaconda2\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xb5 in position 11: invalid start byte

It would be great if you are able to help me out to resolve this encoding issue or any suggestion also fine.

Thanks
Balachandar Raju
