### ISSUE TITLE
cannot import name 'BlockBlobService'

### ISSUE THREAD

**Issue by melzoghbi** [Azure/azure-storage-python#389]
Hi,

I have azure-storage-blob version 0.37.1 and still i get an error when i import BlockBlobService.

`from azure.storage.blob import BlockBlobService # import azure sdk packages
`

Error message:
ImportError: cannot import name 'BlockBlobService'

Here is a list of existing azure storage packages in my current virtual environment:

azure-storage-blob==0.37.1
azure-storage-common==0.37.1
azure-storage-nspkg==2.0.0

How can i fix this? 

Thanks.

**Comment by zezha-msft** [comment]
Hi @melzoghbi, that seems very odd, could you please do a `pip freeze`?

Normally you should see the following azure packages:
```
azure-common==1.1.8
azure-nspkg==2.0.0
azure-storage-blob==0.37.1
azure-storage-common==0.37.1
azure-storage-nspkg==2.0.0
```

Which version of python are you using?

**Comment by melzoghbi** [comment]
This is what i got when i executed pip freeze:

azure-common==1.1.8
azure-nspkg==2.0.0
azure-storage-blob==0.37.1
azure-storage-common==0.37.1
azure-storage-nspkg==2.0.0

**Comment by zezha-msft** [comment]
@melzoghbi which version of Python are you using?

**Comment by melzoghbi** [comment]
3.6.3 This is the Python version i am running on my notebook.

**Comment by zezha-msft** [comment]
Hi @melzoghbi, I'm unable to reproduce this problem. It does not seem to be a problem with the storage package. Could you please try again with a different virtual environment? Thanks!

**Comment by manuyareshimi** [comment]
I get the same error with Python 2.7.12

**Comment by andreacassioli** [comment]
Got the same on 3.6.4

**Comment by irisava** [comment]
got the same error on Python 3.6.5

**Comment by Fra-nk** [comment]
Works perfectly fine for me:
```bash
virtualenv venv
source venv/bin/activate
pip install azure-storage-blob==0.37.1
python
```
```python
from azure.storage.blob import BlockBlobService
```

`pip freeze` output
```
asn1crypto==0.24.0
azure-common==1.1.16
azure-nspkg==3.0.2
azure-storage-blob==0.37.1
azure-storage-common==0.37.1
azure-storage-nspkg==3.0.0
certifi==2018.10.15
cffi==1.11.5
chardet==3.0.4
cryptography==2.3.1
enum34==1.1.6
futures==3.2.0
idna==2.7
ipaddress==1.0.22
pycparser==2.19
python-dateutil==2.7.3
requests==2.19.1
six==1.11.0
urllib3==1.23
```
`python --version` output
```
Python 2.7.10
```

---

I'd suggest updating to a newer version and improving the verbosity. As @zezha-msft said, it sounds like something with your overall system setup isn't correct...

**Comment by yangsiyu007** [comment]
@zezha-msft can you please reopen this issue?

Steps to reproduce:

Environment and Python version:
```
conda create -n myenv python=3.5 azure
```
Output of pip freeze:
```
azure==3.0.0
azure-common==1.1.18
azure-mgmt==0.20.1
azure-mgmt-common==0.20.0
azure-mgmt-compute==0.20.1
azure-mgmt-network==0.20.1
azure-mgmt-nspkg==2.0.0
azure-mgmt-resource==0.20.1
azure-mgmt-storage==0.20.0
azure-nspkg==3.0.2
azure-servicebus==0.20.1
azure-servicemanagement-legacy==0.20.1
azure-storage==0.20.3
```

Error (note that only the second import statement throws an error):
```
>>> import azure.storage.blob
>>> from azure.storage.blob import BlockBlobService
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'BlockBlobService'
```

**Comment by marcjimz** [comment]
Still getting this error.

**Comment by 9antriksh** [comment]
Your code might still be using the legacy Python BlobSDK (https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python-legacy)
But you might have update the library to the latest version.
Use this SDK now for updated code https://docs.microsoft.com/en-us/azure/storage/blobs/storage-quickstart-blobs-python

**Comment by courtenayparserr** [comment]
That didn't work for me. Still getting this issue.

![image](https://user-images.githubusercontent.com/24819057/68641533-38ba8000-055f-11ea-9cd4-a6299d989f70.png)

How do we move past this?

**Comment by xiafu-msft** [comment]
Hi @courtenayparserr 
probably you are using the most recent package？
If the package version is 12.0.0 then try to create a new virtual environment and do:
pip install azure-storage-blob==2.1.0
You will be able to import BlockBlobService

**Comment by xiafu-msft** [comment]
Hi @courtenayparserr 
Would you like to provide the pip freeze outcome？

**Comment by courtenayparserr** [comment]
azure-common==1.1.23
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
certifi==2019.9.11
cffi==1.13.2
chardet==3.0.4
cryptography==2.8
idna==2.8
pycparser==2.19
python-dateutil==2.8.1
requests==2.22.0
six==1.13.0
urllib3==1.25.7

**Comment by courtenayparserr** [comment]
Hi @xiafu-msft 

Any progress here?

**Comment by xiafu-msft** [comment]
Hi @courtenayparserr 
Your pip freeze result is exactly the same as mine....
![Capture](https://user-images.githubusercontent.com/49707495/68834485-c9ca4d80-066a-11ea-9ccb-c862a06dc29e.PNG)

**Comment by dejan-shuki** [comment]
For me it worked after I installed azure package:
pip install azure

I noticed that it uninstalls latest version of azure-storage-blob

Now I have these:
pip freeze
adal==1.2.2
azure==4.0.0
azure-applicationinsights==0.1.0
azure-batch==4.1.3
azure-common==1.1.23
azure-core==1.0.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-datalake-store==0.0.48
azure-eventgrid==1.3.0
azure-graphrbac==0.40.0
azure-keyvault==1.1.0
azure-loganalytics==0.1.0
azure-mgmt==4.0.0
azure-mgmt-advisor==1.0.1
azure-mgmt-applicationinsights==0.1.1
azure-mgmt-authorization==0.50.0
azure-mgmt-batch==5.0.1
azure-mgmt-batchai==2.0.0
azure-mgmt-billing==0.2.0
azure-mgmt-cdn==3.1.0
azure-mgmt-cognitiveservices==3.0.0
azure-mgmt-commerce==1.0.1
azure-mgmt-compute==4.6.2
azure-mgmt-consumption==2.0.0
azure-mgmt-containerinstance==1.5.0
azure-mgmt-containerregistry==2.8.0
azure-mgmt-containerservice==4.4.0
azure-mgmt-cosmosdb==0.4.1
azure-mgmt-datafactory==0.6.0
azure-mgmt-datalake-analytics==0.6.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-datamigration==1.0.0
azure-mgmt-devspaces==0.1.0
azure-mgmt-devtestlabs==2.2.0
azure-mgmt-dns==2.1.0
azure-mgmt-eventgrid==1.0.0
azure-mgmt-eventhub==2.6.0
azure-mgmt-hanaonazure==0.1.1
azure-mgmt-iotcentral==0.1.0
azure-mgmt-iothub==0.5.0
azure-mgmt-iothubprovisioningservices==0.2.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-loganalytics==0.2.0
azure-mgmt-logic==3.0.0
azure-mgmt-machinelearningcompute==0.4.1
azure-mgmt-managementgroups==0.1.0
azure-mgmt-managementpartner==0.1.1
azure-mgmt-maps==0.1.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-media==1.0.0
azure-mgmt-monitor==0.5.2
azure-mgmt-msi==0.2.0
azure-mgmt-network==2.7.0
azure-mgmt-notificationhubs==2.1.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==0.1.0
azure-mgmt-powerbiembedded==2.0.0
azure-mgmt-rdbms==1.9.0
azure-mgmt-recoveryservices==0.3.0
azure-mgmt-recoveryservicesbackup==0.3.0
azure-mgmt-redis==5.0.0
azure-mgmt-relay==0.1.0
azure-mgmt-reservations==0.2.1
azure-mgmt-resource==2.2.0
azure-mgmt-scheduler==2.0.0
azure-mgmt-search==2.1.0
azure-mgmt-servicebus==0.5.3
azure-mgmt-servicefabric==0.2.0
azure-mgmt-signalr==0.1.1
azure-mgmt-sql==0.9.1
azure-mgmt-storage==2.0.0
azure-mgmt-subscription==0.2.0
azure-mgmt-trafficmanager==0.50.0
azure-mgmt-web==0.35.0
azure-nspkg==3.0.2
azure-servicebus==0.21.1
azure-servicefabric==6.3.0.0
azure-servicemanagement-legacy==0.20.6
**azure-storage-blob==1.5.0**
azure-storage-common==1.4.2
azure-storage-file==1.4.0
azure-storage-queue==1.4.0
certifi==2019.9.11
cffi==1.13.2
chardet==3.0.4
cryptography==2.8
idna==2.8
isodate==0.6.0
msrest==0.6.10
msrestazure==0.6.2
oauthlib==3.1.0
pycparser==2.19
PyJWT==1.7.1
python-dateutil==2.8.1
requests==2.22.0
requests-oauthlib==1.3.0
six==1.13.0
urllib3==1.25.7

**Comment by harmonyliu** [comment]
Hi I am having problem importing BlockBlobService using both azure-storage-blob==2.1.0 and azure-storage-blob==12.0.0 under Python 3.7.6.

**Comment by harmonyliu** [comment]
I think there is some dependency bug in the source code  (version  azure-storage-blob==2.1.0 )  of blockblobservice.py and __init__.py under site-packages/azure/storage/blob/  directory.  Because when I type in 
`from azure.storage.blob.blockblobservice import BlockBlobService` 
it worked.

**Comment by xiafu-msft** [comment]
Hi @harmonyliu 
to use BlockBlobService  in azure-storage-blob==2.1.0
make sure you have a clean virtual environment(It's highly recommended to create a new one)
and just do `pip install azure-storage-blob==2.1.0` 
No extra command is needed.

Let me know if it's still not working

**Comment by yashpatel7025** [comment]
This works for me 

pip install azure-storage --upgrade
pip install azure-storage-blob --upgrade
pip install azure --upgrade

after this pip freeze gives 

azure==4.0.0
azure-storage==0.36.0
azure-storage-blob==1.5.0

**Comment by anthonyawuley** [comment]
This worked for me

azure-batch==6.0.0
azure-storage-blob==1.4.0

**Comment by SeaDude** [comment]
This is very confusing... 
- Per @lmazuel in [this thread two days ago](https://github.com/Azure/azure-sdk-for-python/issues/10914#issuecomment-616818532), _**"`azure-storage` is an incompatible old version of `azure-storage-blob`. You cannot install them at the same time, and that will create terrible conflicts."**_
- This directly conflicts with @yashpatel7025 's "solution" above. 
- As outlined in the thread with @lmazuel, I could NOT install `BlobServiceClient`.
  - To get it working, I had to uninstall `azure-storage` then `!pip install -U azure-storage-blob` to fix the problem. 
- NOW, I can't install `BlockBlobService` which exhibits nearly the same error as I had with `BlobServiceClient` from the other day!
- I'm trying to use the elegant code found [here](https://stackoverflow.com/a/53184293/5976033) to directly download large binary files from the web straight to a blob.
- I'm using Azure Notebooks and Azure Databricks so **no**, I can't complicate things with using `venv's`. These are basically *hosted* Jupyter notebooks without access to the OS which hosts them.
```
import os, uuid, json
from azure.identity import ClientSecretCredential
from azure.common.credentials import ServicePrincipalCredentials
from azure.storage.blob import BlobServiceClient, BlobClient, ContainerClient, BlockBlobService
from azure.mgmt.resource import ResourceManagementClient
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-63-d1e5e411e620> in <module>
      2 from azure.identity import ClientSecretCredential
      3 from azure.common.credentials import ServicePrincipalCredentials
----> 4 from azure.storage.blob import BlobServiceClient, BlobClient, ContainerClient, BlockBlobService
      5 from azure.mgmt.resource import ResourceManagementClient

ImportError: cannot import name 'BlockBlobService'
```
- **`!pip freeze` azure packages:**
```
azure==4.0.0
azure-applicationinsights==0.1.0
azure-batch==4.1.3
azure-cli-core==2.0.54
azure-cli-nspkg==3.0.4
azure-cli-telemetry==1.0.4
azure-common==1.1.23
azure-core==1.4.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-datalake-store==0.0.48
azure-eventgrid==1.3.0
azure-graphrbac==0.40.0
azure-identity==1.3.1
azure-keyvault==1.1.0
azure-kusto-data==0.0.38
azure-kusto-ingest==0.0.38
azure-loganalytics==0.1.0
azure-mgmt==4.0.0
azure-mgmt-advisor==1.0.1
azure-mgmt-applicationinsights==0.1.1
azure-mgmt-authorization==0.50.0
azure-mgmt-batch==5.0.1
azure-mgmt-batchai==2.0.0
azure-mgmt-billing==0.2.0
azure-mgmt-cdn==3.1.0
azure-mgmt-cognitiveservices==3.0.0
azure-mgmt-commerce==1.0.1
azure-mgmt-compute==4.6.2
azure-mgmt-consumption==2.0.0
azure-mgmt-containerinstance==1.5.0
azure-mgmt-containerregistry==2.8.0
azure-mgmt-containerservice==4.4.0
azure-mgmt-cosmosdb==0.4.1
azure-mgmt-datafactory==0.6.0
azure-mgmt-datalake-analytics==0.6.0
azure-mgmt-datalake-nspkg==3.0.1
azure-mgmt-datalake-store==0.5.0
azure-mgmt-datamigration==1.0.0
azure-mgmt-devspaces==0.1.0
azure-mgmt-devtestlabs==2.2.0
azure-mgmt-dns==2.1.0
azure-mgmt-eventgrid==1.0.0
azure-mgmt-eventhub==2.6.0
azure-mgmt-hanaonazure==0.1.1
azure-mgmt-iotcentral==0.1.0
azure-mgmt-iothub==0.5.0
azure-mgmt-iothubprovisioningservices==0.2.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-loganalytics==0.2.0
azure-mgmt-logic==3.0.0
azure-mgmt-machinelearningcompute==0.4.1
azure-mgmt-managementgroups==0.1.0
azure-mgmt-managementpartner==0.1.1
azure-mgmt-maps==0.1.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-media==1.0.0
azure-mgmt-monitor==0.5.2
azure-mgmt-msi==0.2.0
azure-mgmt-network==2.7.0
azure-mgmt-notificationhubs==2.1.0
azure-mgmt-nspkg==3.0.2
azure-mgmt-policyinsights==0.1.0
azure-mgmt-powerbiembedded==2.0.0
azure-mgmt-rdbms==1.9.0
azure-mgmt-recoveryservices==0.3.0
azure-mgmt-recoveryservicesbackup==0.3.0
azure-mgmt-redis==5.0.0
azure-mgmt-relay==0.1.0
azure-mgmt-reservations==0.2.1
azure-mgmt-resource==2.0.0
azure-mgmt-scheduler==2.0.0
azure-mgmt-search==2.1.0
azure-mgmt-servicebus==0.5.3
azure-mgmt-servicefabric==0.2.0
azure-mgmt-signalr==0.1.1
azure-mgmt-sql==0.9.1
azure-mgmt-storage==2.0.0
azure-mgmt-subscription==0.2.0
azure-mgmt-trafficmanager==0.50.0
azure-mgmt-web==0.35.0
azure-nspkg==3.0.2
azure-servicebus==0.21.1
azure-servicefabric==6.3.0.0
azure-servicemanagement-legacy==0.20.6
azure-storage-blob==12.3.0
azure-storage-common==2.1.0
azure-storage-file==1.4.0
azure-storage-queue==2.1.0
azureml-automl-core==1.0.72.1
azureml-contrib-notebook==1.0.72
azureml-core==1.0.72
azureml-dataprep==1.1.30
azureml-dataprep-native==13.1.0
azureml-defaults==1.0.72
azureml-explain-model==1.0.72
azureml-interpret==1.0.72.1
azureml-model-management-sdk==1.0.1b6.post1
azureml-opendatasets==1.0.72.1
azureml-pipeline==1.0.72
azureml-pipeline-core==1.0.72
azureml-pipeline-steps==1.0.72
azureml-sdk==1.0.72
azureml-telemetry==1.0.72
azureml-train==1.0.72
azureml-train-automl==1.0.72
azureml-train-core==1.0.72
azureml-train-restclients-hyperdrive==1.0.72
```
- There is a new message when trying to download `!pip install azure` saying something to the effect of "After vX.0 of `azure`, downloading all packages at once is deprecated. Please download packages individually", we really need these dependencies fixed.
- One of the goals of using python within notebooks is the concept of reproducability. Its evident from this string and others around the web that simply importing azure modules at this time is not reproducable.
- Lets get this fixed once and for all. What can I do to help test?

**Comment by SeaDude** [comment]
Ok. I've been able to figure out how to get `BlobServiceClient` and `BlockBlobService` running in Azure Notebooks (thanks in part to @harmonyliu!):
- `!pip uninstall azure -y`
- `!pip install azure==4.0.0`
- `from azure.storage.blob.blockblobservice import BlockBlobService`
- `from azure.storage.blob import BlobServiceClient`
Hope this helps

**Comment by prakharcode** [comment]
@SeaDude I think that solution doesn't work anymore, I've tried quite a few times with every possible solution.

I need to know if anyone is able to run `BlobServiceClient` and `BlockBlobService` together.

**Comment by xiafu-msft** [comment]
Hi @prakharcode 
You cannot import BlobServiceClient(in package version 12.*.*) and BlockBlobService(package version <= 2.1.0) at the same time by pip install. because they are sharing the same namespace azure.storage.blob but the code for these two versions are totally different.

While it seems azure CLI has a multi version api package, and if you really want to use v12 and v2.1.0 together, let's see if they can help

**Comment by vipulgupta2048** [comment]
@xiafu-msft In the same situation as @prakharcode, not sure what your solution entails we do. Should we test it out with multiple version of the Azure CLI?

**Comment by prakharcode** [comment]
@vipulgupta2048 I just left the old version (v2.1) altogether and implemented everything on (v12.0) :)

**Comment by dxkaufman** [comment]
I am trying to move from azure-storage-blob==1.5.0 to 12.3.2, but I can't figure out for the life of me how to import BlockBlobService in the new version!

With 1.5.0, I import and use as follows:

```
import azure.storage.blob as azureblob
...
self.configFile = json.loads(azureblob.BlockBlobService(account_name = '****', account_key='*****==').get_blob_to_text('config',configFileName).content)
```

When I do that, though, I get the << Module 'azure.storage.blob' has no 'BlockBlobService' member >> error on the attempt to connect to the blob.

I've tried a bunch of different ways to import the blockblobservice object, but just can't seem to come up with anything that works.

**Comment by xiafu-msft** [comment]
Hi @dxkaufman 
Thanks for reaching out. There's no BlockBlobService in version>=12.0.0. Please see the wiki https://github.com/Azure/azure-storage-python/wiki#frequently-encountered-problem-no-module-named-azurestorageblob

To get text content of blob in v12.3.2, you should do the following thing
```
        bsc = BlobServiceClient(
            self.account_url(storage_account, "blob"),
            credential=account_key)

        blob_client = bsc.get_blob_client(your_container_name, your_blob_name)

        blob_client.upload_blob(text_data)

        # Act
        stream = blob_client.download_blob(max_concurrency=2, encoding='UTF-8')
        content = stream.readall()  # this will give you the text content
```

**Comment by dxkaufman** [comment]
Hi @xiafu-msft 
Thanks for the quick response. I was starting to get that idea, although I was looking at SDK documentation that seemed to indicate it was still part of the model. I think the docs aren't super clear about what version they relate to.

I appreciate the sample. All the samples I was looking at last night seem to create a container before accessing it, even when the description is just for reading a blob. I found that a little confusing, though I surmised that the assumption was that the container didn't exist yet, and your example seems to make that clearer.

Dylan

**Comment by Ather23** [comment]
I was getting a similar issue. The following post got me thinking


> I think there is some dependency bug in the source code (version azure-storage-blob==2.1.0 ) of blockblobservice.py and **init**.py under site-packages/azure/storage/blob/ directory. Because when I type in
> `from azure.storage.blob.blockblobservice import BlockBlobService`
> it worked.

I changed the import statement to
`import azure.storage.blob._blob_service_client`
and it worked

**Comment by ericthomas1** [comment]
@xiafu-msft, 

Thank you for the example of how to use `BlobServiceClient` to get a `BlobClient`. I now see this option listed in [the SDK docs here](https://azuresdkdocs.blob.core.windows.net/$web/python/azure-storage-blob/12.0.0b5/index.html#clients). 

An alternative is to instantiate a separate `BlobClient` using a SAS. Not sure if its any easier, but the way I did it was:

```
blob_client = BlobClient.from_blob_url(blob_url = sas_token)

with open("./sampleFile.txt", "rb") as data:
    blob_client.upload_blob(data)
```

**Comment by emafra** [comment]
> Acho que há algum bug de dependência no código-fonte (versão azure-storage-blob == 2.1.0) de blockblobservice.py e **init** .py em site-packages / azure / storage / blob / directory. Porque quando eu digito
> `from azure.storage.blob.blockblobservice import BlockBlobService`
> funcionou.

Thakns harmonyliu, its work for me. U save my day!!!!

**Comment by flogrammer** [comment]
For me it was just

pip install azure-storage-blob==2.1.0

**Comment by dangerousHobo** [comment]
I'm seeing this error and have yet to find a solution that works is 2021.
Python version: 3.8.5

```
File "data_functions.py", line 35, in <module>
    from azure.storage.blob import BlobClient
ImportError: cannot import name 'BlobClient' from 'azure.storage.blob' (/tmp/_MEIXh7p9M/azure/storage/blob/__init__.pyc)
```

pip freeze
```
azure==4.0.0
azure-common==1.1.24
azure-core==1.15.0
azure-storage-blob==12.8.1
azure-storage-common==1.4.0
azure-storage-file==1.4.0
azure-storage-file-datalake==12.0.0b7
azure-storage-file-share==12.0.1
azure-storage-queue==1.4.0
```

How can I get this code to run?

**Comment by frank-fischer-by** [comment]
You seem to have far too much (& incompatible) stuff installed.

Do not **mix** this repo and similar storage libraries with [azure-sdk-for-python](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage) libraries.


```shell
$ python --version
> Python 3.8.10

$ pip install azure-storage-blob
> ...

$ pip freeze
> azure-core==1.15.0
> azure-storage-blob==12.8.1
> certifi==2021.5.30
> cffi==1.14.5
> chardet==4.0.0
> cryptography==3.4.7
> idna==2.10
> isodate==0.6.0
> msrest==0.6.21
> oauthlib==3.1.1
> pycparser==2.20
> requests==2.25.1
> requests-oauthlib==1.3.0
> six==1.16.0
> urllib3==1.26.5

$ python -c "from azure.storage.blob import BlobClient" && echo $?
> 0
```

I suggest to use [`pip-tools`](https://pypi.org/project/pip-tools/) (or [`pipenv`](https://pypi.org/project/pipenv/) or [`poetry`](https://pypi.org/project/poetry/)) to clean up your virtual environment.
Or completely delete it and rebuild it properly.

**Comment by rajacsp** [comment]
> Hi @harmonyliu to use BlockBlobService in azure-storage-blob==2.1.0 make sure you have a clean virtual environment(It's highly recommended to create a new one) and just do `pip install azure-storage-blob==2.1.0` No extra command is needed.
> 
> Let me know if it's still not working

this worked for me when I was dealing with BlockBlobService import issues

**Comment by abhijit-z** [comment]
Hi 
I wanna write xlsx file directly into azure blob. I am trying the following but getting error:
from azure.storage.blob import (
    BlockBlobService
)
![image](https://user-images.githubusercontent.com/66016483/158714603-38ee33d4-b7e0-46a6-8ae8-9c34f92f6265.png)

Pls suggest any better method if possible
Thanks

**Comment by abhijit-z** [comment]
Hi @[xiafu-msft](https://github.com/xiafu-msft) Any suggestions on the above please :)

**Comment by Crimsonabyss** [comment]
> This works for me
> 
> pip install azure-storage --upgrade pip install azure-storage-blob --upgrade pip install azure --upgrade
> 
> after this pip freeze gives
> 
> azure==4.0.0 azure-storage==0.36.0 azure-storage-blob==1.5.0
> 
> now I am able to run following from azure.storage.blob import BlockBlobService, PublicAccess

you are a legend, worked for me. thanks!
