### ISSUE TITLE
set_blob_metadata() replaces the existing properties

### ISSUE THREAD

**Issue by Balachandar-R** [Azure/azure-storage-python#390]
Hi Team,

if i use the set_blob_meta() to update my new metadata properties, this will replaces all the previous metadata properties.
set_blob_metadata() replaces the existing properties of the blob files.
How to add  additional metadata properties in addition to the already available metadata properties. 

Kindly help on this issue.

Thanks
Balachandar R

**Comment by zezha-msft** [comment]
Hi @Balachandar-R, you can do a get_blob_metadata first, add new value to the dict, and then call set_blob_metadata.

**Comment by Balachandar-R** [comment]
Hi @zezha-msft ,

I had already followed the same steps but if we are trying to add new metadata using dictionary, it replaced the existing meta as well.

How to merge my metadata to the existing one?

Thanks
Balachandar R
