### ISSUE TITLE
Git merge mark was submitted in dev branch and leaked into released package.

### ISSUE THREAD

**Issue by troydai** [Azure/azure-storage-python#391]
https://github.com/Azure/azure-storage-python/blob/59c99dd6cc6f57e29aef0c6693bc42bc830e47a9/azure-storage-file/azure/storage/file/models.py#L39

**Comment by zezha-msft** [comment]
Sorry @troydai, I fixed it [already](https://github.com/Azure/azure-storage-python/commit/5edbf5ba6611d45f5ce4fe4048d0315938557806) but I've been waiting for the next file package release.
