### ISSUE TITLE
How to keep the MetaData key names case as like Service Headers

### ISSUE THREAD

**Issue by Balachandar-R** [Azure/azure-storage-python#393]
Hi,

It seems that the azure storage python sdk libraries force lowercase metadata keys when storing metadata. 

Some incompatibility seems to be built in since metadata is set through headers and the HTTP specs say,
     "Category": "Value1",
     "SubCategory": "Value-sub-1"

When I access via get_blob_metadata() function, it give me key values in lower case. 
How do I keep the key string case as it is available in JSON response in the REST call.?

Thanks,
Balachandar Raju

**Comment by zezha-msft** [comment]
Hi @Balachandar-R, this was [fixed](https://github.com/Azure/azure-storage-python/issues/296) but not released yet. I'll pick it up for the next release. Thanks!
