### ISSUE TITLE
Azure CLI 2.0 loses "table" service in generated account SAS

### ISSUE THREAD

**Issue by vkovalchuk** [Azure/azure-storage-python#394]
After having set proper AZURE_STORAGE_ACCOUNT, AZURE_STORAGE_KEY I run
> az storage account generate-sas --services bt --resource-types co --permissions wucla --expiry "2018-12-31"

and it prints

> "ss=b&sp=wlacu&sv=2017-04-17&sig=w7_etcetc_Y%3D&srt=co&se=2018-12-31"

Note there is no 't' in 'ss=' part and then Azure LinuxDiagnostics fails to collect metrics with this token into some JsonBlob. Major part of functionality in a major tool is broken.

I am using azure-cli (2.0.21) and the bug is still here. I have tried to put a fix PR in [Azure/azure-multiapi-storage-python repo](https://github.com/Azure/azure-multiapi-storage-python/pull/10#issuecomment-347278512) but was told to report here. My local fix solved my problem and the token has "ss=bt" and works. The problem is purely in option-parsing model.py, no server changes are needed.

I don't feel my fix totally matches with this module; while multiapi-storage makes it clear there are "cross-services", this azure.storage.common has no idea that table service exists. So it's easy to add 2 lines but hard to properly document.

**Comment by zezha-msft** [comment]
Hi @vkovalchuk, I apologize for the inconvenience.

The table service was recently [split-off](https://github.com/Azure/azure-storage-python/issues/361) from this SDK, and consequently we removed all references of table. I realize that we perhaps shouldn't have removed this part of the logic. I'll make sure to fix this.

Thanks for bringing this to our attention!

**Comment by zezha-msft** [comment]
It is [fixed](https://github.com/Azure/azure-storage-python/commit/d6d989a621ce3591078150edd9e32480813f9593) and will go out with the next release. I apologize for the inconvenience.

**Comment by zezha-msft** [comment]
This was fixed in release 1.0.0.
