### ISSUE TITLE
Update Metadata of blobs using REST API

### ISSUE THREAD

**Issue by Balachandar-R** [Azure/azure-storage-python#396]
Hello Team,

I need your help to update the metadata for all the blob files using REST API.
I have followed the instruction given in the official document and able to list out the blobs with HAMC SHA256.

But i am not able to access or update metadata using REST API. Can you given me an example.

Thanks,
Balachandar-R

**Comment by zezha-msft** [comment]
Hi @Balachandar-R, please refer to this [page](https://docs.microsoft.com/en-us/rest/api/storageservices/set-blob-metadata).
