### ISSUE TITLE
Max Block Blob size 4.75 TB but in library it is still 195 GB

### ISSUE THREAD

**Issue by sauravmndl** [Azure/azure-storage-python#397]
Max block size is now 100MB, so as per documentation if max 50000 blocks can be uploaded then, max block blob size becomes 100 MB x 50000 ~= 4.75 TiB . See [here](https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits)

But in library it is still approax 195 GB (4 MiB x 50000). See [here](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-blob/azure/storage/blob/blockblobservice.py#L102)

**Comment by zezha-msft** [comment]
Hi @sauravmndl, the max block size is [configurable](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-blob/azure/storage/blob/blockblobservice.py#L89) by the user. 

I'll update the comment [here](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-blob/azure/storage/blob/blockblobservice.py#L79). Thanks for bringing this up!

**Comment by sauravmndl** [comment]
@zezha-msft Can you please suggest me how to use `create_blob_from_path` function when my file size is 300 GB?

**Comment by zezha-msft** [comment]
Hi @sauravmndl, please refer to the [sample](https://github.com/Azure/azure-storage-python/blob/master/samples/blob/block_blob_usage.py#L333) on how to use the method. As for the block size, I would suggest to set it to 100MB (100 * 1024 * 1024).
