### ISSUE TITLE
Block Blobs Limitation in Documentation

### ISSUE THREAD

**Issue by aluong** [Azure/azure-storage-python#400]
According to the block blob [documentation](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-blob/azure/storage/blob/blockblobservice.py) it says:
```
Each block in an append blob can be a different size, up to a maximum of 4 MB,
    and an append blob can include up to 50,000 blocks. The maximum size of an
    append blob is therefore slightly more than 195 GB (4 MB X 50,000 blocks).
```

However, the latest Microsoft [documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs) says:
```
The maximum size of a block blob is therefore slightly more than 4.75 TB (100 MB X 50,000 blocks).
For REST versions before 2016-05-31, the maximum size of a block blob is a little more than 195 GB (4 MB X 50,000 blocks).
```

Which REST version is the Python Storage SDK using and can we update the documentation if applicable?

**Comment by zezha-msft** [comment]
Hi @aluong, thanks for bringing up the issue! The doc was already [fixed](https://github.com/Azure/azure-storage-python/commit/0f001c75702ef9f3bc40550a1313880a60d2bd3d).

The Python SDK currently targets the service version ['2017-04-17'](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-blob/azure/storage/blob/_constants.py#L20).
