### ISSUE TITLE
Customize pool_maxsize of requests, urllib3 connection pool

### ISSUE THREAD

**Issue by carsonip** [Azure/azure-storage-python#413]
This is a similar feature request like https://github.com/boto/botocore/issues/766

This feature would be useful since I am always getting  

> WARNING:requests.packages.urllib3.connectionpool:Connection pool is full, discarding connection: ****.blob.core.windows.net

Thanks.

**Comment by zezha-msft** [comment]
Hi @carsonip, you can solve this problem by passing in a request_session to the [constructor of any service](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-blob/azure/storage/blob/blockblobservice.py#L137). Please refer to this [link](https://stackoverflow.com/questions/18466079/can-i-change-the-connection-pool-size-for-pythons-requests-module) on how to create a session and override the pool_maxsize. 

Please let me know if you have any other question.

**Comment by MaxTranced** [comment]
Permalink to the `request_session` parameter in the [constructor of any service](https://github.com/Azure/azure-storage-python/blob/4306898850dd21617644fc537a57d025e833db74/azure-storage-blob/azure/storage/blob/blockblobservice.py#L132).

**Comment by MaxTranced** [comment]
For the new https://github.com/Azure/azure-sdk-for-python/ maybe this helps? https://stackoverflow.com/a/22253656/
