### ISSUE TITLE
How to select multiple coluimns on a table storage

### ISSUE THREAD

**Issue by Rahulnigam28** [Azure/azure-storage-python#414]
I am using this command 
query = table_service.query_entities(table, select='"column1" and "column2" ')

I have a table storage with 6 columns and I want to query only column1 and column2 

This command is not working for me

**Comment by zezha-msft** [comment]
Hi @Rahulnigam28, please post questions about the table service in [this repo](https://github.com/Azure/azure-cosmosdb-python).
