### ISSUE TITLE
Problems running test suite locally

### ISSUE THREAD

**Issue by evanrolfe** [Azure/azure-storage-python#415]
Hi, I'm trying to write tests for the patch given in issue https://github.com/Azure/azure-storage-python/issues/341 so a proper pull request can be submitted for that change, however I'm having trouble testing changes to the code. I'm new to python so perhaps I'm missing something obvious, sorry in advance if I am!

I've followed the steps under [CONTRIBUTING.md#install](https://github.com/Azure/azure-storage-python/blob/master/CONTRIBUTING.md#install) however it seems that the tests are testing the installed azure-storage-blob package as opposed to the files in the repo i cloned. For example if I run this test: `tests.blob.test_page_blob.StoragePageBlobTest.test_create_blob_from_stream` then it passes. But if I then delete all of the code thats inside `azure-storage-blob/azure/storage/blob/pageblobservice.py` and run that same test again, the test still passes. I would expect it to fail since that test uses code from `pageblobservice.py`. Am I missing something?

Also one more thing to note is that CONTRIBUTING.md says to `run "python setup.py install" from the azure-storage-python folder` but that file no longer exists since there are now setup.py's in each of the three sub directories.

Any help would be much appreciated, thanks.

**Comment by zezha-msft** [comment]
Hi @evanrolfe, I really apologize for the outdated CONTRIBUTING doc. I have recently updated it but it is still in review. I will publish it as soon as possible.

FYI, the issue #341 was [fixed](https://github.com/Azure/azure-storage-python/commit/eb9183a20ba67cdbab868df3241258e93eb3cc3f), it will go out with the next release.

**Comment by evanrolfe** [comment]
@zezha-msft no problem. thanks for letting me now about that fix!

**Comment by zezha-msft** [comment]
Hi @evanrolfe, the contributing doc has been updated, please let me know if you have any question!

**Comment by evanrolfe** [comment]
Can I just ask if you have an ETA For when a new version of this package will be released which includes this change? Thanks

**Comment by evanrolfe** [comment]
Great thank you!
