### ISSUE TITLE
Ability to set blob tier

### ISSUE THREAD

**Issue by Bidek56** [Azure/azure-storage-python#420]
### Which service(blob, file, queue) does this issue concern?
Blob

### What problem was encountered?
Does this library has a function to set the blob tier level (hot, cool, archive)?
Thanks

**Comment by zezha-msft** [comment]
Hi @Bidek56, yes! Please refer to our [API doc](https://docs.microsoft.com/en-us/python/api/azure.storage.blob.blockblobservice.blockblobservice?view=azure-python#azure_storage_blob_blockblobservice_BlockBlobService_set_standard_blob_tier) for the details.

**Comment by haulmer-fguerra** [comment]
@zezha-msft nowadays the link [API doc](https://docs.microsoft.com/en-us/python/api/azure.storage.blob.blockblobservice.blockblobservice?view=azure-python#azure_storage_blob_blockblobservice_BlockBlobService_set_standard_blob_tier) than you refer is missing, this return 404.

**Comment by zezha-msft** [comment]
Hi @haulmer-fguerra, please refer to the [README](https://github.com/Azure/azure-storage-python#microsoft-azure-storage-sdk-for-python) for the latest link, which points to [here](https://docs.microsoft.com/en-us/python/api/overview/azure/storage/client?view=azure-python).

**Comment by codegrafix** [comment]
All links are not working -> 404 - Page not found
