### ISSUE TITLE
How do we get an exception of timeout from BlockBlobService?

### ISSUE THREAD

**Issue by MatsumotoHiroko** [Azure/azure-storage-python#421]
### Which service(blob, file, queue) does this issue concern?
blob

### What problem was encountered?
I use BLOB Storage in Microsoft Azure by Python thourgh module of BlockBlobService.
If Blob require a long time to be able to connect, I would like to take an exception of timeout. 
`block_blob_service = BlockBlobService(account_name=blob_account_name, account_key=blob_account_key, socket_timeout=1)`

But It wasn't successful.

Athoug I gave BlockBlobService an argument of "socket_timeout", it doesn't stop to contact Blob.
I seem that it continue trying to access to Blob over and over.

Do you know how to get an exception of timeout when we start to create BlockBlobService?

I show my log on flask.

`Client-Request-ID=------ Retry policy did not allow for a retry: , HTTP status code=Unknown, Exception=HTTPSConnectionPool(host='-----.net', port=443): Max retries exceeded with url: /xxxxxxx?restype=container&comp=list (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at xxxxxxxx>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)).`

### Have you found a mitigation/solution?
Yes.
I saw a module document.
https://github.com/Azure/azure-storage-python/blob/e8472835df490d5bdb035de1a9b424a407a658f5/azure-storage-common/azure/storage/common/_http/httpclient.py#L77
https://github.com/Azure/azure-storage-python/blob/master/azure-storage-common/azure/storage/common/storageclient.py#L355

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by zezha-msft** [comment]
Hi @MatsumotoHiroko, here are some clarifications concerning timeouts:

First, there are 2 kinds of timeout:
- socket timeout, which you have tried already. It governs how long the client(SDK) waits for the server to send data before declaring this try as failed.
- server timeout, which is passed to each method that makes a network call (for example put_block). This one governs how long the server waits for the operation to complete before responding to the client saying the request has timed out/failed.

If either timeout occurs, retries would be made by the SDK. By default, it would retry 3 times, and each time wait for a longer amount of time. Please take a look at the [sample](https://github.com/Azure/azure-storage-python/blob/master/samples/advanced/client.py#L42) if you are interested in configuring your own retry policy. 

If all retries fail, an AzureException would be thrown like this:
`HTTPSConnectionPool(host='your_account.blob.core.windows.net', port=443): Read timed out. (read timeout=[your timeout])`

From your question, I think socket timeout is indeed the one you should use, however 1 second seems a bit too short. Please let me know if you have any other question.
