### ISSUE TITLE
Method create_blob still overrides the blob even when if_match='*' is used

### ISSUE THREAD

**Issue by vcanaa** [Azure/azure-storage-python#422]
### Which service(blob, file, queue) does this issue concern?
Blob

### What problem was encountered?
Documentation in https://github.com/Azure/azure-storage-python/blob/master/azure-storage-blob/azure/storage/blob/appendblobservice.py says :

>  Creates a blob or overrides an existing blob. Use if_match=* to
>         prevent overriding an existing blob. 

However, the blob is still overwritten with the if_match='\*'.
I get a conflict when using if_none_match='\*'.

> azure.common.AzureConflictHttpError: The specified blob already exists.

Either documentation or behavior is wrong.

### Have you found a mitigation/solution?

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by zezha-msft** [comment]
Hi @vcanaa, thanks for bringing up the issue, the documentation is wrong in this case. To clarify:
- if_match=* means "if etag matches anything", which basically translates to "if blob exists"
- if_none_match=* means "if etag does not match anything", which is "if blob does not exist". So to make sure you are not overriding an existing blob, you should use if_none_match=*.

I will update the documentation. Thank you!

**Comment by zezha-msft** [comment]
This was fixed in version 1.1.0 of the blob package.
