### ISSUE TITLE
How to handle errors?

### ISSUE THREAD

**Issue by arv1989** [Azure/azure-storage-python#43]
How to efficiently handle error from this sdk? which are the common Exceptions this sdk may raise. the docs doesn't have any information on this. Please advice.

**Comment by arv1989** [comment]
I am trying to implement a job which reads from Azure Queue and writes into db. occasionally some errors are raised from the Azure server such as timeout, server busy etc. How to handle such errors in the code, I tried ti run the code in a try catch loop but, I am not able to identify Azure errors? 
I triedn to import WindowsAzureError from azure , but it doesn't work (no such module to import)?

Which is a good way to handle errors in this case?

**Comment by emgerner-msft** [comment]
If you're using 0.20+ we've consolidated all errors that occur after we make the request to the service to extend from AzureException. AzureException can be found in the azure.common package that we take a dependency on. Errors which are thrown if invalid args are passed to a method (ex None for the queue name) might not extend from this and will be standard Python exception like ValueError.

**Comment by arv1989** [comment]
Thanks, that was what I was looking for , I got the issue resolved now . Thank you 



Regards,
Ameen Rashad 
+919961161277


—
