### ISSUE TITLE
Header Parsing Error

### ISSUE THREAD

**Issue by dagrooms52** [Azure/azure-storage-python#430]
**Operation**
Azure BlockBlobService save operation

**Expected Result**
Operation completed with no errors

**Actual Result**
Sometimes a HeaderParsingError is raised

**Versions**
Running in docker container image `python:3.6.3-jessie`
```
pip freeze
azure==2.0.0
azure-storage==0.34.3
azure-storage-blob==1.0.0
```

**Relevant Information**

Running the following code:
```
from azure.storage.blob import BlockBlobService
service = BlockBlobService(account_name, account_key)
...
self.service.create_blob_from_bytes(self.container_name,
    blob_name=ref_id, blob=compressed_data, metadata=metadata)
```

Sometimes produces this error:
```
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", 
        line 398, in _make_request
    assert_header_parsing(httplib_response.msg)
File "/usr/local/lib/python3.6/site-packages/requests/packages/urllib3/util/response.py", 
        line 66, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
    requests.packages.urllib3.exceptions.HeaderParsingError: [
        StartBoundaryNotFoundDefect(), 
        MultipartInvariantViolationDefect()], unparsed data: ''
```

Relevant header info:

```
Receiving Response: Server-Timestamp=Thu, 08 Feb 2018 20:43:09 GMT, 
Server-Request-ID=*guid*, HTTP Status Code=201, Message=Created, 
Headers={
    'x-ms-blob-type': 'BlockBlob',
    'x-ms-lease-id': None, 
    'If-Modified-Since': None, 
    'If-Unmodified-Since': None, 
    'If-Match': None, 
    'If-None-Match': None, 
    'x-ms-meta-encoding': 'application/json', 
    'x-ms-meta-compression': 'gzip', 
    'Content-Length': '547', 
    'x-ms-version': '2017-04-17', 
    'User-Agent': 'Azure-Storage/1.0.0-1.0.0 
        (Python CPython 3.6.3; Linux 4.9.60-linuxkit-aufs)', 
    'x-ms-client-request-id': '*guid*', 
    'x-ms-date': 'Thu, 08 Feb 2018 20:43:09 GMT', 
    'Authorization': 'SharedKey myusername:mykey'}
```

For now, I have a try/except block around the creation catching HeaderParsingError to ignore it. Is this safe to do? Is there a way to prevent the error at all?

**Comment by zezha-msft** [comment]
Hi @dagrooms52, that is indeed a strange issue.

I see from your `pip freeze` that you have the deprecated monolithic package `azure-storage==0.34.3` installed alongside the newest split version `azure-storage-blob==1.0.0`. That might be causing some kind of inconsistency, could you please uninstall the deprecated `azure-storage`? `azure-storage-common` also seems to be missing, do you mind giving me a full `pip freeze`? Thanks!

**Comment by dagrooms52** [comment]
Interesting. I'll try that. I got all of these installations from the standard Python SDK docs, maybe they need an update?

```
pip freeze

azure==2.0.0
azure-batch==3.0.0
azure-common==1.1.8
azure-datalake-store==0.0.18
azure-graphrbac==0.30.0
azure-keyvault==0.3.7
azure-mgmt==1.0.0
azure-mgmt-authorization==0.30.0
azure-mgmt-batch==4.0.0
azure-mgmt-cdn==0.30.3
azure-mgmt-cognitiveservices==1.0.0
azure-mgmt-compute==1.0.0
azure-mgmt-containerregistry==0.2.1
azure-mgmt-datalake-analytics==0.1.6
azure-mgmt-datalake-nspkg==2.0.0
azure-mgmt-datalake-store==0.1.6
azure-mgmt-devtestlabs==2.0.0
azure-mgmt-dns==1.0.1
azure-mgmt-documentdb==0.1.3
azure-mgmt-iothub==0.2.2
azure-mgmt-keyvault==0.31.0
azure-mgmt-logic==2.1.0
azure-mgmt-monitor==0.2.1
azure-mgmt-network==1.0.0
azure-mgmt-nspkg==2.0.0
azure-mgmt-rdbms==0.1.0
azure-mgmt-redis==4.1.1
azure-mgmt-resource==1.1.0
azure-mgmt-scheduler==1.1.3
azure-mgmt-sql==0.5.3
azure-mgmt-storage==1.0.0
azure-mgmt-trafficmanager==0.30.0
azure-mgmt-web==0.32.0
azure-nspkg==2.0.0
azure-servicebus==0.21.1
azure-servicefabric==5.6.130
azure-servicemanagement-legacy==0.20.6
azure-storage==0.34.3
azure-storage-blob==1.0.0
azure-storage-common==1.0.0
azure-storage-nspkg==3.0.0
```

**Comment by dagrooms52** [comment]
I'm only running `pip install azure==2.0.0 azure-storage-blob == 1.0.0` - one of these packages is pulling in the deprecated package.

**Comment by dagrooms52** [comment]
It seems that `pip install azure-storage-blob` pulled in the `azure-storage-common` package, and its version is up to 1.1.0, not the 1.0.0 I was binding.

How do I install the table storage package from this point? I was getting it through the monolithic package `azure==2.0.0`, but it is not registered on pip under `azure-storage-table`.

**Comment by dagrooms52** [comment]
I now get this error instead with the `requirements.txt` above:

```
from azure.storage.blob import BlockBlobService
File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/__init__.py", line 6, in <module>
from .appendblobservice import AppendBlobService
File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/appendblobservice.py", line 30, in <module>
from ._deserialization import (
File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/_deserialization.py", line 18, in <module>
from azure.storage.common._deserialization import (
ImportError: cannot import name '_to_int'
```

**Comment by dagrooms52** [comment]
I'm now getting an error when importing both the TableService and the BlobService in the same file (I don't actually do this, I import both of the wrappers I've made for these services, which in turn import the services, but I'm not doing `import *`).

```
File "myapp/api/wsgi.py", line 2, in <module>
  from myapp.api import application
File "/myapp/myapp/api/application.py", line 9, in <module>
  from myapp.api import views
File "/myapp/myapp/api/views.py", line 6, in <module>
  from myapp.api import view_wrappers
File "/myapp/myapp/api/view_wrappers.py", line 4, in <module>
  from myapp.implementation import backend
File "/myapp/myapp/implementation/backend.py", line 19, in <module>
  from myapp.implementation.utilities.auditing.storage_accounts import blob_storage, table_storage
File "/myapp/myapp/implementation/utilities/auditing/storage_accounts.py", line 3, in <module>
  from myapp.implementation.utilities.azure_storage.blob_storage import BlockBlobUtility
File "/myapp/myapp/implementation/utilities/azure_storage/blob_storage.py", line 5, in <module>
  from azure.storage.blob import BlockBlobService
File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/__init__.py", line 6, in <module>
  from .appendblobservice import AppendBlobService
File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/appendblobservice.py", line 30, in <module>
  from ._deserialization import (
File "/usr/local/lib/python3.6/site-packages/azure/storage/blob/_deserialization.py", line 18, in <module>
  from azure.storage.common._deserialization import (
ImportError: cannot import name '_to_int'
```

It appears that the name `_to_int` is imported into the scope by both of these modules, and they are stepping on each other.

**Comment by zezha-msft** [comment]
Hi @dagrooms52, I really apologize for the confusion and inconvenience. The `azure` mega-package is installing the old deprecated `azure-storage`, so I've created a [PR](https://github.com/Azure/azure-sdk-for-python/pull/1978) to fix that. Thanks for raising the issue here.

As for the table service, you should definitely use azure-cosmosdb-table. As for the import error `ImportError: cannot import name '_to_int'`, I think that it is because azure-cosmosdb-table is depending on an [older version](https://github.com/Azure/azure-cosmosdb-python/blob/master/azure-cosmosdb-table/setup.py#L71) of azure-storage-common, and when you installed azure-cosmosdb-table it overwrote the new/correct azure-storage-common (1.1.0). I've created an [issue](https://github.com/Azure/azure-cosmosdb-python/issues/19) on their repo to fix this problem.

Thanks to your issue I realized that it was not a very nice experience installing/using the storage packages along with other azure packages. I'll be more mindful in the future. Thank you!

Please let me know if you are still encountering problems.
