### ISSUE TITLE
Progress callback enhancements

### ISSUE THREAD

**Issue by ascobie** [Azure/azure-storage-python#431]
### Which service(blob, file, queue) does this issue concern?
Blob

### What problem was encountered?
create_blob_from_stream :: progress_callback

### Issue

progress callback is currently defined as: **progress_callback(progress, total)**

I would like to add the blob name to this as well. The issue is that if we are asynchronously calling the Batch CLI with a number of files, the callback will only contain the progress and the total to upload. We need the file/blob name in there as well in order to report progress back to the user.

Current data throughput in KB/s would also be super helpful and go a great deal forwards in diagnosing customer issues.

The new signature would be: **progress_callback(progress, total, blob_name, current_throughput)**. adding optional parameters to the end would not affect existing implementations.

**Comment by zezha-msft** [comment]
Hi @ascobie, thanks for reaching out!

For the blob name, you can easily encapsulate that information with closure. For example, every time you make an upload request, you can generate a new progress_callback function with a closure that contains the blob name, so you can use it when the progress_callback is called. Please let me know if you would like some sample code on this.

As for the throughput counter, I'll need to discuss with my team and get back to you. Thanks for raising the feature request!

**Comment by ascobie** [comment]
Hi, 

Thanks for your response. The closure idea sounds interesting. We have a Electron/Angular application that has an encapsulated python RPC server in order to pass off commands to the Batch CLI. Part of this allows users to upload files into a storage container, the python controller for this action is here: 

https://github.com/Azure/BatchLabs/blob/master/python/controllers/create_file_group_controller.py

You can see our __uploadCallback defined and it currently only reports once the file has been completely uploaded. This is OK for small files, but for larger files the UI can sit there for a while without reporting any progress to the user. One of the more popular suggestions is to provide per file progress as well as a general throughput indicator so the users can see how fast data is being injected into storage.

If you could share with me some suggestions about how to do a "generate a new progress_callback function with a closure".

Thanks for your help,
Andrew

**Comment by zezha-msft** [comment]
Hi @ascobie, what I meant is something like this:

```python
def generate_progress_callback(blob_name):
    def progress_callback(current, total):
        print('({}, {}, {})'.format(blob_name, current, total))
    return progress_callback
```

Then you can use it like this:
```python
service.get_blob_to_bytes(container_name, blob_name, progress_callback=generate_progress_callback(blob_name))
```

**Comment by zezha-msft** [comment]
Hi @ascobie, while chatting with my colleague, I realized that you could easily implement the throughput counter using the same closure technique. You will need to keep track of two variables:

- The last byte count, in other words, the previous "current"
- A timestamp for when the last byte count was reported

This way, you can calculate the throughput by using: (current-previous)/time since last byte count.

I will close this for now, please let me know if you have any other question. Thanks!

**Comment by ascobie** [comment]
Hi There, 

Sorry, i have just figured out that we cannot create a closure with the blob name as we only pass the directory to the CLI for it to be uploaded like so: 

"D:\Azure\assets\ocr\**\*"

So the Batch CLI will then gather up the files and pass them to your create_blob_from_stream method. Maybe i can get the CLI to create the closure.
