### ISSUE TITLE
Getting error in azure notebooks while deploying : ImportError: No module named azure.storage.blob 

### ISSUE THREAD

**Issue by adarsha04** [Azure/azure-storage-python#432]
### Which service(blob, file, queue) does this issue concern?
azure.storage.blob

### What problem was encountered?
we are usign azure ml stodio workspace and trying to deploy model using azure notebooks present in ml studio.

imported azure-storage using below code. 
!pip install azure-storage==0.36.0

its working when i run normally but when its deployed, its giving us this error:

{u'error': {u'message': u'Module execution encountered an error.', u'code': u'ModuleExecutionError', u'details': [{u'message': u'Error 0085: The following error occurred during script evaluation, please view the output log for more information:\r\n---------- Start of error message from Python interpreter ----------\r\nCaught exception while executing function: Traceback (most recent call last):\n  File "\\server\\InvokePy.py", line 120, in executeScript\n    outframe = mod.azureml_main(*inframes)\n  File "\\temp\\1450604638.py", line 1094, in azureml_main\n    results.append(__user_function(client_code))\n  File "<ipython-input-29-476b9842e001>", line 17, in final_model\n  File "<ipython-input-28-aa41894a859e>", line 5, in data_input\nImportError: No module named azure.storage.blob\n\r\n\r\n---------- End of error message from Python  interpreter  ----------', u'code': u'85', u'target': u'Execute Python Script RRS'}]}}

### Have you found a mitigation/solution?

No

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by zezha-msft** [comment]
Hi @adarsha04, could you please try again with the [latest versions](https://github.com/Azure/azure-storage-python#option-1-via-pypi)? The previews ones are now deprecated. 

This does not look like an issue related to the storage SDK, since the error says "No module named azure.storage.blob", which implies it's just missing the dependency. 

Do you have other libraries that you use in your environment? Do they work when you deploy the application?

**Comment by adarsha04** [comment]
Hi,

thanks a lot for the reply.

I am facing issue in importing that package in studio workspace itself. Any other package for that matter. I am not sure how to do that.

I am using basic packages like pandas and all which should be already there in deploying environment. But how to install packages which is not there in storage workspace. Thats why its failing when i deploy.

**Comment by zezha-msft** [comment]
Hi @adarsha04, if you are having problem importing any package, then it is most likely not a storage SDK problem.

I have no knowledge of the ML studio, I would suggest to research about whether external libraries are even supported. If the answer is yes but you are not able to import anything, I would suggest to contact Azure support team at that point. Thanks!
