### ISSUE TITLE
BlockBlobService size limits are outdated

### ISSUE THREAD

**Issue by crepererum** [Azure/azure-storage-python#435]
### Which service(blob, file, queue) does this issue concern?
blob

### What problem was encountered?
[These constants](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-blob/azure/storage/blob/blockblobservice.py#L93) are too low for the current version (which is [`2017-07-29`](https://github.com/Azure/azure-storage-python/blob/8d35972169035b5be96b90f659b11f725a2738bf/azure-storage-blob/azure/storage/blob/_constants.py#L11))

### Have you found a mitigation/solution?
The constants should be changed to the following:

- `MAX_SINGLE_PUT_SIZE = 256 * 1024 *1024` ([ref](https://docs.microsoft.com/en-us/rest/api/storageservices/put-blob#remarks))
- `MAX_BLOCK_SIZE = 100 * 1024 * 1024` ([ref](https://docs.microsoft.com/en-us/rest/api/storageservices/put-block))
- `MIN_LARGE_BLOCK_UPLOAD_THRESHOLD = 100 * 1024 * 1024 + 1` to match `MAX_BLOCK_SIZE`

**Comment by zezha-msft** [comment]
Hi @crepererum, thanks for reaching out!

It is true that these default values can be set higher, but smaller blobs may be more common than larger ones, so a block size of 100MB and single put size of 256MB might lead to worse performance for a lot of cases. In general, it is preferred to let the users of the SDK adjust these numbers to whatever that makes the most sense for their file sizes and network conditions.

Thank you for the suggestion!

**Comment by smarlowucf** [comment]
> In general, it is preferred to let the users of the SDK adjust these numbers to whatever that makes the most sense for their file sizes and network conditions.

I have this problem as well, however there's no way to adjust these numbers. Attempting to upload a page blob instead of a block blob but both have the same problem. In that the max block size is not configurable.

https://github.com/Azure/azure-storage-python/blob/master/azure-storage-blob/azure/storage/blob/pageblobservice.py#L1003

Is this an option that can be added to the create_blob_from_stream and create_blob_from_path methods?

**Comment by zezha-msft** [comment]
Hi @smarlowucf, could you please clarify why you couldn't adjust these numbers?

Please see an example in [our tests](https://github.com/Azure/azure-storage-python/blob/master/tests/blob/test_block_blob.py#L46).

**Comment by smarlowucf** [comment]
@zezha-msft Ah, I was only looking at the parameters. This should work then. Thank you.

**Comment by smarlowucf** [comment]
@zezha-msft I did a quick test with 32mb size and unfortunately it yields an error. `</Message><MaxLimit>4194304</MaxLimit></Error>`. So it seems like 4mb is a hard limit.

**Comment by smarlowucf** [comment]
Okay, thanks.
