### ISSUE TITLE
ListGenerator

### ISSUE THREAD

**Issue by douglasmacdonald** [Azure/azure-storage-python#439]
### Which service(blob, file, queue) does this issue concern?

https://github.com/Azure/azure-storage-python/blob/2709a0bb5b1647803fc25ee1292c6fc43782ed89/azure-storage-common/azure/storage/common/models.py#L53

### What problem was encountered?

The `ListGenerator` does not stop/reset cleanly. To be honest, I am not even sure that it is working as documented.

e.g.

`data_gen = table_service.query_entities(table_name)`

Then repeatedly calling....

`list(data_gen)`

... will give you a large list of data then on subsequent calls a never ending smaller block. 

Expectation. After the first call to `list(data_gen)` then either subsequent calls it is either reset and  the same data is returned or if you consider it exhausted then return [] or None  

### Have you found a mitigation/solution?

This is a guess. I do not know enough about the way this is being used. Otherwise, write a `ListGerator` for the purpose.

Try following the 

`__iter__` and `__next__` pattern where the `__iter__` sets/resets and `__next__` does the work.

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by zezha-msft** [comment]
Hi @douglasmacdonald, please take a look at the [sample](https://github.com/Azure/azure-cosmosdb-python/blob/master/azure-cosmosdb-table/samples/table/table_usage.py#L118) to understand how `table_service.query_entities` should be used. 

In short, when you write `list(table_service.query_entities(table_name))`, all the entities are returned as a list, meaning that the iterator follows the marker until there is no more items or the max number of results is reached. The ListGenerator returned by `query_entities` at this point should not be reused.   

Please let me know if this is clear now. Thanks!

**Comment by douglasmacdonald** [comment]
Thank you. I understand.

> "The ListGenerator returned by query_entities at this point should not be reused." 

But this was not the point I was making.

If you are happy with this behaviour that is fine.  I was only making the point that, generally, in python generators do get called again. A user using `list(...)` on a generator where the underlying data has not changed might expect the same thing to happen when they call `list` on it again. If not, it should be either clearly returned empty [] or `StopIteration` or new data.  Even if you do not want it used again, **Returning a blob of data form the end is confusing.** If you don't want it to be used again then a `StopIteration` seems like the best answer for you.

The code sample I gave you shows that a class is not necessary to get the behaviour I'd expect.

Thank you for the Python interface.
