### ISSUE TITLE
Azure Germany Subscription blob copy url error

### ISSUE THREAD

**Issue by mcanerim** [Azure/azure-storage-python#442]
I'm trying to use the copy_blob method from azure.storage.blob. The problem here is that, it send a HttpPost request to Azure global. Where in my case my blob is stored inside a container on Azure Germany. My problem is that, I couldn't find a way to provide the copy_blob method a method. While creating a BlobService, shouldn't we be able to provide this or even the BlobService class should understand by itself that the account he tries to connect is on Azure Germany.

**Comment by zezha-msft** [comment]
Hi @mcanerim, please refer to the [samples](https://github.com/Azure/azure-storage-python/blob/master/samples/advanced/client.py#L73). Thanks!
