### ISSUE TITLE
Error message when calling baseblobservice.exists

### ISSUE THREAD

**Issue by rems75** [Azure/azure-storage-python#444]
### Which service(blob, file, queue) does this issue concern?

I'm using blob.

### What problem was encountered?

Calling the exists method of the azure.storage.blob.baseblobservice prints an error message when the container already exists which pollutes logs. Nothing should be printed as I'm specifically trying to see whether the container exists...

### Have you found a mitigation/solution?

Changing my log level to critical right before the call and restoring it after masks the message, but it's not a very clean solution.

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by zezha-msft** [comment]
Hi @rems75, thanks for reaching out. This is a known issue being tracked [here](https://github.com/Azure/azure-storage-python/issues/437).
