### ISSUE TITLE
 Retry policy did not allow for a retry

### ISSUE THREAD

**Issue by MomoHsieh** [Azure/azure-storage-python#446]
### Which service(blob, file, queue) does this issue concern?
I am trying to upload a file to a blob using azure.storage.blob.

### What problem was encountered?
I can't upload big file(>1Mb) from embedded system which connect to Internet by LTE.
But I can 
1. Upload big file(>1Mb) from my computer which connect to Internet by WiFi.
2. Upload small file (like 20Kb) from embedded system which connect to Internet by LTE.
**Running python2.7.9 on armv7l GNU/Linux**
```
import os, uuid, sys
from azure.storage.blob import BlockBlobService, ContentSettings
import logging
logging.basicConfig()
def run_sample():
    try:
        # Create the BlockBlockService that is used to call the Blob service for the storage account
        block_blob_service = BlockBlobService(account_name='compaliotdemo',account_key='***')

        local_file_name = 'test.mp4'
        full_path_to_file =os.path.join(os.getcwd(), local_file_name)

        print("Temp file = " + full_path_to_file)
        print("\nUploading to Blob storage as blob: " + local_file_name)

        # Upload the created file, use local_file_name for the blob name
        block_blob_service.create_blob_from_path('compaldemo', local_file_name, full_path_to_file, content_settings=ContentSettings(content_type='video/mp4'))

    except Exception as e:
        print(e)


if __name__ == '__main__':
    run_sample()
```

```

pip freeze 
PyYAML==3.12
argparse==1.2.1
azure-common==1.1.9
azure-nspkg==2.0.0
azure-storage-blob==1.1.0
azure-storage-common==1.1.0
azure-storage-nspkg==3.0.0
cffi==0.8.6
chardet==2.3.0
colorama==0.3.2
cryptography==0.6.1
enum34==1.1.6
futures==3.2.0
html5lib==0.999
ndg-httpsclient==0.3.2
paramiko==2.0.0
peewee==2.8.1
ply==3.4
pyOpenSSL==0.14
pyasn1==0.1.7
pycparser==2.10
pyserial==2.6
pysftp==0.2.8
python-dateutil==2.7.2
python-onedrive==15.10.5
pytz==2018.4
requests==2.4.3
six==1.8.0
urllib3==1.9.1
wheel==0.24.0
wsgiref==0.1.2
```

I got error below
```
ERROR:azure.storage.common.storageclient:Client-Request-ID=848347e4-4150-11e8-8ba3-00e04c3618b2 Retry policy did not allow for a retry: , HTTP status code=Unknown, Exception=WantWriteError: .
WantWriteError:
```

**Comment by zezha-msft** [comment]
Hi @MomoHsieh, thanks for reaching out!

If you can upload smaller files but not larger ones, I would suspect that your network may not be very stable. Could you please try to increase the number of retries like shown [here](https://github.com/Azure/azure-storage-python/blob/master/samples/advanced/client.py#L33) and see if that solves the problem? Thanks!

**Comment by MomoHsieh** [comment]
Hi @zezha-msft 
I add this code 
```
from azure.storage.common.retry import (
    LinearRetry,
    ExponentialRetry
)

block_blob_service.retry = ExponentialRetry(initial_backoff=30, increment_base=2, max_attempts=20).retry
block_blob_service.create_blob_from_path('compaldemo', local_file_name, full_path_to_file, content_settings=ContentSettings(content_type='video/mp4'))
```
But can't upload file too. 

```
Uploading to Blob storage as blob: testfff.mp4
WantWriteError:
```

But if I change to python3 and this problem disappear, also upload file successfully in 10 seconds .

**Comment by MomoHsieh** [comment]
@zezha-msft 
I found the issue about the python package version different.
When I use requests==2.18.4 can work, but requests==2.4.3 can't.
Maybe you can update the requests version required when use 
```
pip install azure-storage-blob 
```
This setting is work!
asn1crypto==0.24.0
azure-common==1.1.9
azure-nspkg==2.0.0
azure-storage-blob==1.1.0
azure-storage-common==1.1.0
azure-storage-nspkg==3.0.0
certifi==2018.4.16
cffi==1.11.5
chardet==3.0.4
cryptography==2.2.2
enum34==1.1.6
futures==3.2.0
idna==2.6
ipaddress==1.0.22
pycparser==2.18
python-dateutil==2.7.2
requests==2.18.4
six==1.11.0
urllib3==1.22

**Comment by zezha-msft** [comment]
Hi @MomoHsieh, I'm glad that you found the issue!

We do not put any bound on the `requests` [module](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-common/setup.py#L79). Thank you for letting us know the fix to your problem! This will be helpful to others who encounter similar problems.

**Comment by mallik3006** [comment]
Hello,

I'm getting similar issue:
```python
blob_file = os.path.basename(destination)
get_gen = block_blob_service.list_blobs(container)
for blob in get_gen:
      if os.path.basename(blob.name) == blob_file:
           block_blob_service.get_blob_to_path(container, blob, download_path)
```

Appears like, 2nd request to get the blob is giving the error. Only operation (here list_blobs)
at a time in a  request is only being allowed. 
I tried adding the Linear and exponential retries but it did not solve the issue.
Please could you provide a resolution?

**Comment by bhprasad** [comment]
Very useful. I encountered the same error and after updating requests package to 2.20+ the WantWriteError exception disappeared.

**Comment by holms** [comment]
I'm still getting this error in 2021... 
```
$ DATE=$(date -ud yesterday '+%Y-%m-%dT%H:%MZ')
$ az storage blob upload-batch -d "assets" -s /builds/cloud-dev-setupad/prebid_assets --if-modified-since ${DATE} --pattern '[!.git]*' --connection-string $AZURE_STORAGE_CONNECTION_STRING
```
```9:49:42.8374786Z</Message></Error>.
ERROR: Client-Request-ID=a603408a-e3bf-11eb-ab4f-0242ac110002 Retry policy did not allow for a retry: Server-Timestamp=Tue, 13 Jul 2021 09:49:42 GMT, Server-Request-ID=32d6d27f-d01e-000f-43cc-7789fb000000, HTTP status code=412, Exception=The condition specified using HTTP conditional header(s) is not met. ErrorCode: ConditionNotMet<?xml version="1.0" encoding="utf-8"?><Error><Code>ConditionNotMet</Code><Message>The condition specified using HTTP conditional header(s) is not met.RequestId:32d6d27f-d01e-000f-43cc-7789fb000000Time:2021-07-13T09:49:42.8885133Z</Message></Error>.
```

**Comment by zezha-msft** [comment]
Hi @holms, it's not the same error. Your error is:

    HTTP status code=412, Exception=The condition specified using HTTP conditional header(s) is not met

It looks like you specified --if-modified-since ${DATE} which is sending conditions on the write requests to Storage. Is this intentional? 

Please investigate on your end first, it doesn't look like an SDK issue.

**Comment by holms** [comment]
Well yeah only files which been modified per 24 hours should be uploaded. What does headers has to do with anything in here. Removing this condition everything starts to work, but it uploads lots of files whos modification date is wrong, and I'm not sure why modification date differs from the one which is in git repo:)

**Comment by zezha-msft** [comment]
@holms the --if-modified-since flag is for the destination blobs, not the source files. Perhaps the cli doc is not clear, could you please raise an issue in the az cli repo if you feel the same?
