### ISSUE TITLE
Support for Block level CSE

### ISSUE THREAD

**Issue by reeshabhraj1** [Azure/azure-storage-python#454]
We need to transfer some large files(>100GB) along with small files from our internal storage service to Azure blob storage. Currently, using python SDK, we need to download the whole file from our internal storage system and then call create_blob_from_path() which does internal chunking and encryption. What we need is to make calls at block level with encrypted block level data without having to download full file, which is currently not supported by SDK without having to use protected functions from the SDK(To do this, we have to use some protected encryption functions and models). Please provide us a solution for how to upload a mix of small and large files by giving us a call at Block level with CSE and other block level tasks.

**Comment by zezha-msft** [comment]
Hi @reeshabhraj1, thanks for reaching out.

It seems that we intentionally did not support CSE on the block level, as you can see on this [line](https://github.com/Azure/azure-storage-python/blob/master/azure-storage-blob/azure/storage/blob/blockblobservice.py#L173). I will investigate this and update you shortly.

**Comment by zezha-msft** [comment]
Hi @reeshabhraj1, here is an update on why we do not support CSE on the block level:

The algorithm that we are using to perform client-side encryption is AES256 in Cipher Block Chaining(CBC) mode, which was chosen for its security. In short, using CBC means that to encrypt a block of plaintext, it is mandatory to first encrypt all the previous blocks. Please refer to this link for more information on CBC: [here](https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Cipher_Block_Chaining_(CBC)). Thus, to make the implementation manageable, our CSE encrypts the entire blob. If blocks were encrypted individually, then decryption would be much harder: we'd have to keep track of where each individually encrypted block breaks off (with padding or not). So unfortunately, block-level CSE is not supported in any of the Storage SDKs.

If you absolutely need encryption, there are two options that I can think of:

1. stick with the SDK's CSE, and make download faster by increasing concurrency
2. implement your own custom encryption algorithm to encrypt at a block level
 

Please let me know if you have any other question.
