### ISSUE TITLE
set_container_acl erase the current container access policies.

### ISSUE THREAD

**Issue by Epoxboy** [Azure/azure-storage-python#460]
### Which service(blob, file, queue) does this issue concern?
blob.
I'm trying to generate 2 tokens, Read-only and Read-Write, for the container.

### What problem was encountered?
when using set_container_acl() to set a stored access policy to container, it always clear all the existing container access policies first, then set the new policy.

here is my code:
----------------------------------------------------------------------------------------------
def generate_SAS():

        service = BlockBlobService(account_name=account_name, account_key=account_key)
        
        service.create_container(container_name)
        
        # Set access policy on container
        
        access_policy = AccessPolicy(permission=container_permissions, expiry=datetime.utcnow() + timedelta(days=+days_until_expiry))
        
        identifiers = {id_number: access_policy}
        
        acl = service.set_container_acl(container_name, signed_identifiers=identifiers)
       
        # Wait 30 seconds for acl to propagate
        time.sleep(30)
       
        # Indicates to use the access policy set on the container
        token = service.generate_container_shared_access_signature(container_name,id=id_number)  
       
        print('READ TOKEN IS :')
        print(token)
       
if __name__ == '__main__':
    account_name   =os.environ['STORAGE_ACCOUNT_NAME']
    account_key    =os.environ['STORAGE_ACCOUNT_KEY']
    container_name =os.environ['STORAGE_CONTAINER_NAME']
    days_until_expiry = 365*5
    id_number = 'id1'
    container_permissions = ContainerPermissions.READ
    
    generate_SAS()
-------------------------------------------------------------------------

### Have you found a mitigation/solution?
you need to create access policies in the Azure portal, and in the script, just using token generation part to pass in the policy id to associate with it. It's not a solution, it's a work around.

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by zezha-msft** [comment]
Hi @Epoxboy, thanks for reaching out!

This is expected behavior, please refer to this [sample](https://github.com/Azure/azure-storage-python/blob/master/samples/blob/sas_usage.py#L168).

**Comment by Epoxboy** [comment]
thank you for the sample and I figured it out that in my case, if I want to generate two tokens at the same time, I should use identifiers = {id_ro: access_policy_ro, id_rw: access_policy_rw} to make access policies instead of using loop to generate policy one by one.

**Comment by zezha-msft** [comment]
@Epoxboy sounds good! Thanks for sharing. 👍
