### ISSUE TITLE
Irrespective of an assigned role, a service principle has same privileges as an owner 

### ISSUE THREAD

**Issue by VJalili** [Azure/azure-storage-python#461]
### Which service(blob, file, queue) does this issue concern?
azure-storage-blob v1.2.0rc1

### What problem was encountered?
I have a web server, which I want to give it _read_ access to my Azure blob storage. Additionally, I want the web server to have independent permissions from mine (i.e., my user account). I think using the new features added to Azure (e.g., [Added support for OAuth authentication for HTTPS requests](https://github.com/Azure/azure-storage-python/commit/1917cb8d20aa89eac953f51fdfa2a60ddf6ed188)) I can leverage OAuth2.0 access tokens and Azure AD roles for this purpose. Therefore, I followed [this](https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-app) documentation, and created a service principal and assigned _Azure Storage_ permission to it. Then in the Azure portal, under __Storage -> Access Control (IAM)__, I defined `Storage Blob Data Reader (Preview)` role and assigned it to my service principal. 

So, I implemented a logic similar to [this](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/f48ab57a91e9c3b29e4580e9c66510ee9e29d531/sample/website_sample.py#L112-L118) to acquire access token, then I use the token to read the blob. However, I get an error saying that I am not allowed to access the blob. Then I assign myself the `Storage Blob Data Reader (Preview)` role, and then I'm able to read the blob. So, the service principal's role is not effective, i.e., I cannot assign myself a `Contributor` (read/write) and give the service principal the `Reader` role. 

Am I missing some important setting here? 

### Have you found a mitigation/solution?
No.

## Update 1:
Following is a summary of the different combinations I tried and their resulted outcome: 

| xyz@hotmail.com Role | Service Principal Role** | Read/Write Result | Expected Outcome |
| :--- | :--- | :--- | :--- |
| Contributor* | Contributor* | Successful (i.e., can read and write) | Successful |
| Contributor* | None | Successful (i.e., can read and write) | Fail | 
| None | Contributor* | <Code>AuthorizationFailure</Code> This request is not authorized to perform this operation. RequestId:509428ef-901e-00f3-4b93-051b26000000 | Successful |

*Contributor = STORAGE BLOB DATA CONTRIBUTOR (PREVIEW)
**Service Principal ID: `58ad99f1-19e9-4b08-8121-c372e1f14653`

## Update 2:
In the request for the an OIDC/OAuth2.0 access token, I set the `client_id` attribute is to the service principal ID.

**Comment by zezha-msft** [comment]
Hi @VJalili, thanks for reaching out!

It seems that your issue is more about the setting rather than the SDK. I'll try to find the right person to help you. I'll get back to you shortly.

**Comment by VJalili** [comment]
@zezha-msft Thank you.

**Comment by lakasa** [comment]
Thanks for reaching out with this issue. Can you please email lakasa@microsoft.com with your storage account name so we can investigate more?

**Comment by zezha-msft** [comment]
Hi @VJalili, please close the issue after your problem is solved offline, and feel free to share the insights here as well.

**Comment by VJalili** [comment]
@zezha-msft first of all, thanks for putting me in contact with @lakasa.  As you recommended I'll close this issue once the problem is resolved and will share the solution here as well.

**Comment by yaxia** [comment]
@VJalili I don't see any missing step in your settings. Do you mind share a request ID of a failed request with the service principal ID? I can take a look. Thanks.

**Comment by VJalili** [comment]
@yaxia please see the Update on the first post.

**Comment by yaxia** [comment]
@VJalili I guess your service principal is created by a native application in the AAD and you are using this flow:![flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/media/active-directory-authentication-scenarios/native_app_to_web_api.png)

This means you are authenticated as the user you login (i.e.: xyz@hotmail.com). So you might expect the result according to the user role assignment, which matches the outcome in the first post.

If you'd like to authenticate with the service principal, could you please try to create an application with type: Web App /API and create a secret for it. See steps [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-integrating-applications).

When this is setup, you might want to do the same role assignment to this service principal for the storage account. 

Then you can [require access token with the application's Id and secret](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/f48ab57a91e9c3b29e4580e9c66510ee9e29d531/sample/client_credentials_sample.py#L50-L59) to get an access token for this application and read the blobs under the account.

**Comment by VJalili** [comment]
@yaxia Thank you. The issue is resolved; I was using the flow you highlighted (i.e., I was using [`acquire_token_with_authorization_code`](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/f48ab57a91e9c3b29e4580e9c66510ee9e29d531/sample/website_sample.py#L112-L118)). However, my client application was correctly registered as a __Web App / API__. 

Just out of curiosity, after the user gives the consent, I still receive __authorization code__, although I am not using it to request tokens, however it remains a mystery what is the application of this code in your recommend flow.

**Comment by yaxia** [comment]
@VJalili Glad to hear you resolved the issue.
The authorization code flow is described in this [document](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-oauth-code). 

You might also want to see this document for [the implicit grant](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-dev-understanding-oauth2-implicit-grant) flow.

**Comment by VJalili** [comment]
@yaxia Thanks.
