### ISSUE TITLE
SDK currently does not address the scenario where a large file needs to be downloaded serially to a non-seekable stream

### ISSUE THREAD

**Issue by williexu** [Azure/azure-storage-python#464]
### Which service(blob, file, queue) does this issue concern?
blob/file

### What problem was encountered?
referencing with some edits: https://github.com/Azure/azure-cli/issues/6608:

Currently the `max_connections=1` arguments for downloads will only attempt to pull the larger files in one piece. When the file it is trying to download is larger than the memory on the workstation running the task the process consumes the workstation's entire memory and swap file then fails.

Looking to get the download methods to treat the `max_connections=1` like it does when the max connections is set to 2 or more. That is to handle files larger than the memory of the workstation by breaking the file into multiple peices and make multiple requests to get the full file to download.

The Customer needs to download the blob to a named pipe so they must be able to use a single download connection to prevent seek operations on the pipe

**Comment by zezha-msft** [comment]
Hi @williexu, thanks for creating the issue.

I'll update this thread once this work is scheduled on our end.

**Comment by v-tisheg** [comment]
Has this been published?  
Does the customer need to download a new version of the Azure CLI?
He tested the command and got the same results.

**Comment by zezha-msft** [comment]
No @v-tisheg, this work will be scheduled soon.

**Comment by zezha-msft** [comment]
Hi @williexu and @v-tisheg, this issue has been fixed in 1.3.1.
