### ISSUE TITLE
Add LICENSE(.txt) to wheels

### ISSUE THREAD

**Issue by xhochy** [Azure/azure-storage-python#477]
Currently the LICENSE is only part of the repository but not contained in the released Python packages. It would be very helpful to ship it in the wheel and sdist tarballs.

**Comment by xhochy** [comment]
As an example, `conda-forge` packages that are built from the sdist currently need to sideload the license file: https://github.com/conda-forge/staged-recipes/pull/5433

**Comment by zezha-msft** [comment]
Hi @xhochy, thanks for reaching out!

I'll let our packaging expert @lmazuel comment on how should we proceed.

**Comment by lmazuel** [comment]
Wheel is not supposed to have the LICENCE file, as long as each file contains the licence in the header (which is the case).
sdist *could* indeed, and that doesn't hurt. @zezha-msft copy the LICENCE.txt at the root of the repo into each package folder, and update the MANIFEST.in file of each package with `include LICENCE.txt`

**Comment by zezha-msft** [comment]
@lmazuel sounds good! I'll do this work as part of the next release.

**Comment by zezha-msft** [comment]
Fixed in 1.4.0.
