### ISSUE TITLE
az storage blob generate-sas fails to produce correct sas token

### ISSUE THREAD

**Issue by nicolaibaralmueller** [Azure/azure-storage-python#485]
### Which service(blob, file, queue) does this issue concern?
Blob
az storage blob generate-sas --account-name name--account-key key --container-name cname --name file --permissions r --https-only

### Which version of the SDK was used? Please provide the output of `pip freeze`.
azure-cli 2.0.43
Python 3.6.5

adal==0.5.0
adium-theme-ubuntu==0.3.4
ansible==2.6.2
applicationinsights==0.11.1
argcomplete==1.9.4
asn1crypto==0.24.0
azure-cli-core==2.0.27
azure-cli-nspkg==3.0.1
azure-common==1.1.8
azure-mgmt-batch==4.1.0
azure-mgmt-compute==2.1.0
azure-mgmt-containerservice==1.0.0
azure-mgmt-dns==1.2.0
azure-mgmt-keyvault==0.40.0
azure-mgmt-network==1.7.1
azure-mgmt-nspkg==2.0.0
azure-mgmt-resource==1.2.2
azure-mgmt-sql==0.7.1
azure-mgmt-storage==1.5.0
azure-mgmt-web==0.32.0
azure-nspkg==2.0.0
azure-storage==0.35.1
backports.ssl-match-hostname==3.5.0.1
beautifulsoup4==4.4.1
certifi==2018.1.18
cffi==1.11.4
chardet==3.0.4
colorama==0.3.9
cryptography==2.1.4
docker-py==1.10.6
docker-pycreds==0.3.0
ecdsa==0.13
enum34==1.1.2
futures==3.2.0
html5lib==0.999
httplib2==0.9.1
humanfriendly==4.8
idna==2.6
ipaddress==1.0.16
isodate==0.6.0
Jinja2==2.8
jmespath==0.9.0
keyring==11.0.0
knack==0.3.1
lxml==3.5.0
MarkupSafe==0.23
monotonic==1.4
msrest==0.4.26
msrestazure==0.4.21
ntlm-auth==1.0.6
oauthlib==2.0.6
packaging==16.8
paramiko==1.16.0
pyasn1==0.1.9
pycparser==2.18
pycrypto==2.6.1
Pygments==2.2.0
PyJWT==1.5.3
pymssql==2.1.3
pync==1.6.1
pyOpenSSL==17.5.0
pyparsing==2.2.0
pysphere==0.1.7
python-dateutil==2.6.1
pyvmomi==6.7.0
pywinrm==0.3.0
PyYAML==3.11
requests==2.18.4
requests-ntlm==1.1.0
requests-oauthlib==0.8.0
SecretStorage==2.3.1
six==1.11.0
tabulate==0.7.7
unity-lens-photos==1.0
urllib3==1.22
websocket-client==0.48.0
xmltodict==0.11.0

### What problem was encountered?
sas tokens do not work anymore

### Have you found a mitigation/solution?
No
Respons: HTTP Error 404: The specified blob does not exist.
The file exists and I can download manually and have cross checked the link.
When leaving out the parameters start and expire the result is this:
`<Error>
<Code>AuthenticationFailed</Code>
<Message>
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:3014a2ed-c01e-005d-44e5-2fd752000000 Time:2018-08-09T13:33:45.8073475Z
</Message>
<AuthenticationErrorDetail>se is mandatory. Cannot be empty</AuthenticationErrorDetail>
</Error>`

Also, my Ubuntu server has correct datetime.

**Comment by zezha-msft** [comment]
Hi @nicolaibaralmueller, thanks for reaching out!

I've created an issue on the [CLI](https://github.com/Azure/azure-cli/issues)'s page for you. It is possible, but very unlikely to be an issue in the SDK itself.

**Comment by nicolaibaralmueller** [comment]
This was resolved. User error :-/
