### ISSUE TITLE
FeatureRequest: ability to set retry option in storage 

### ISSUE THREAD

**Issue by janhaviagrawal** [Azure/azure-storage-python#489]
### Which service(blob, file, queue) does this issue concern?
queue

### Which version of the SDK was used? Please provide the output of `pip freeze`.
azure-storage==0.36.0

### What problem was encountered?
No option to set the RetryOptions for QueueService object.
QueueService inherits from StorageClient class which has retry set to default ExponentialRetry in its init.
In pydocumentdb, we can set RetryOptions as property of client's connection policy. It would be great if that could be unified across storage service as well.

### Have you found a mitigation/solution?
No.

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by zezha-msft** [comment]
Hi @janhaviagrawal, thanks for reaching out!

Please refer to this [sample](https://github.com/Azure/azure-storage-python/blob/master/samples/advanced/client.py#L33) on how to set retry policies.

I see that you are using a deprecated monolithic version of the Storage SDK. I would like to suggest you to upgrade to the latest `azure-storage-queue` package.
