### ISSUE TITLE
Minor: Add endpoint_suffix argument to CloudStorageAccount object for use when constructing services

### ISSUE THREAD

**Issue by bgklein** [Azure/azure-storage-python#490]
### Which service(blob, file, queue) does this issue concern?
CloudStorageAccount

### Which version of the SDK was used? Please provide the output of `pip freeze`.
latest

### What problem was encountered?
Soveign Cloud users need to specify this to get the appropriate endpoints.

### Have you found a mitigation/solution?
Manually creating services but probably nice to add for convienence

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by zezha-msft** [comment]
Hi @bgklein, thanks for reaching out!

It sounds like a reasonable change, would you like to submit a PR for it?

**Comment by zezha-msft** [comment]
@bgklein sounds great!
