### ISSUE TITLE
How to get the blob url from the BlobProperties? 

### ISSUE THREAD

**Issue by priyaananthasankar** [Azure/azure-storage-python#501]
Can url be constructed within the BlobProperties of the Azure Blob object?

**Comment by priyaananthasankar** [comment]
Can url be constructed within the BlobProperties?

**Comment by zezha-msft** [comment]
Please refer to the [documentation](https://azure-storage.readthedocs.io/ref/azure.storage.blob.baseblobservice.html#azure.storage.blob.baseblobservice.BaseBlobService.make_blob_url) on how to generate a blob URL.

**Comment by doronAtuar** [comment]
and what about in v12?

**Comment by zhanwenchen** [comment]
How to get there from a container:

```python
        dicty = {}
        container_client = self.container_client
        for blob_properties in container_client.walk_blobs():
            blob_client = container_client.get_blob_client(blob_properties)
            dicty[blob_client.blob_name] =  blob_client.url
        return dicty
```
