### ISSUE TITLE
blob_service.list_blobs returns blobs with no metadata

### ISSUE THREAD

**Issue by aatkinson** [Azure/azure-storage-python#508]
### Which service(blob, file, queue) does this issue concern?
Blob

### Which version of the SDK was used? Please provide the output of `pip freeze`.
1.3.1

```
$ pip freeze | grep "azure"
azure-common==1.1.16
azure-nspkg==3.0.2
azure-storage-blob==1.3.1
azure-storage-common==1.3.0
azure-storage-nspkg==3.0.0
```

### What problem was encountered?

`azure.storage.blob.BlockBlobService.list_blobs(..)` returns a list of Blob objects that have `metadata` member as `None` - even though some of the blobs have metadata in the blob storage container.

### Have you found a mitigation/solution?

Call `get_metadata` on each blob, but this is time consuming and presumably consists of multiple requests.
Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by zezha-msft** [comment]
Hi @aatkinson, please refer to the [sample](https://github.com/Azure/azure-storage-python/blob/master/samples/blob/container_usage.py#L232) on how to list blobs with metadata.
