### ISSUE TITLE
What is the plane of 0.37.0 release?

### ISSUE THREAD

**Issue by smtakeda** [Azure/azure-storage-python#510]
### Which service(blob, file, queue) does this issue concern?
azure-storage package

### Which version of the SDK was used? Please provide the output of `pip freeze`.
0.36.0

### What problem was encountered?
Python logging is missing.  It appeared 0.37.0 has it. We would like to enable it for https://github.com/snowflakedb/snowflake-connector-python

### Have you found a mitigation/solution?
none other than reading code.

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by Fra-nk** [comment]
See https://github.com/Azure/azure-storage-python#getting-started

> prior to and including version 0.36.0, there used to be a single package (azure-storage) containing all services. It is no longer supported, and users should install the 3 before-mentioned service packages individually, depending on the need.

**Comment by zezha-msft** [comment]
Hi @smtakeda, thanks for reaching out!

The previews versions are now deprecated. Please upgrade to the latest version, there are instructions on the Readme page. Also please refer to [here](https://github.com/Azure/azure-storage-python#logging) on how to set up the logging.
