### ISSUE TITLE
How to add permission to builtin role in storage account?

### ISSUE THREAD

**Issue by himanshu219** [Azure/azure-storage-python#513]
I have a storage account and I want to give permission to one of my App Service in "Storage Account Key Operator Service Role".
Similar to the below action in Azure portal.

![IAM Permission](https://user-images.githubusercontent.com/3620468/46846740-a517fc80-cdfe-11e8-876f-6ed24b3f2d0b.png)

**Comment by zezha-msft** [comment]
Hi @himanshu219, thanks for reaching out!

Please refer to this [guide](https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac).

**Comment by himanshu219** [comment]
Thanks for the answer but I have already looked into that. This feature is under preview and is not for production use.

**Comment by zezha-msft** [comment]
@himanshu219 does the guide answer your question?

**Comment by zezha-msft** [comment]
HI @himanshu219, are you looking for a sample like [this one](https://github.com/Azure/azure-storage-python/blob/master/samples/advanced/oauth.py)?

**Comment by himanshu219** [comment]
Thanks I found the api and answered the question here https://stackoverflow.com/questions/52771941/how-to-add-permission-to-builtin-role-in-storage-account-using-azure-python-sdk/52773467?noredirect=1#comment92594352_52773467
