### ISSUE TITLE
Azure Authentication Error for large files(around 1k files each >500MB) Transfer

### ISSUE THREAD

**Issue by rajreeshabh** [Azure/azure-storage-python#523]
### Which service(blob, file, queue) does this issue concern?
The issue is with Blob service while uploading large files of around 500MB-1GB

### Which version of the SDK was used? Please provide the output of `pip freeze`.
azure-storage==0.34.3
azure-storage-blob==1.1.0
azure-storage-common==1.1.0
azure-storage-file==1.1.0
azure-storage-nspkg==3.0.0
azure-storage-queue==1.1.0

### What problem was encountered?
We are getting Authentication Error from the SDK but the analytic log says that the error is ServerTimeOut error for the same request. We are getting these errors daily since September last week when this data set was first transferred.

App Log: 
`Error:Encounted one or more errors during task. \n process:24709 error:Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.ErrorCode: AuthenticationFailed\n<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:8fa5963c-001e-001c-2ee5-69a595000000\nTime:2018-10-22T09:02:36.0454236Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request 'k8eDiPEXtO3nxexR3lx2WzIBydvTrg/FPa4CdG997DE=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:2cd02b34-d5d9-11e8-8497-02010a20377e\nx-ms-date:Mon, 22 Oct 2018 09:02:35 GMT\nx-ms-version:2017-07-29\n/XXXX/d620b62-fk-sp-slm-libertalia-store-backup/fk-sp-slm-libertalia-store-backup/Full/1082802__elasticsearch__2018-10-22__12-55-00__full/indices/hHvoKSWBSIeuhA1zCXvDVg/4/__5z.part0\nblockid:TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQTJOekV3T0RnMk5EQSUzRA==\ncomp:block\ntimeout:600'.</AuthenticationErrorDetail></Error> : Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.ErrorCode: AuthenticationFailed\n<?xml version=\"1.0\" encoding=\"utf-8\"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:8fa5963c-001e-001c-2ee5-69a595000000\nTime:2018-10-22T09:02:36.0454236Z</Message><AuthenticationErrorDetail>The MAC signature found in the HTTP request 'k8eDiPEXtO3nxexR3lx2WzIBydvTrg/FPa4CdG997DE=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n\n\n\n\n\n\n\n\n\nx-ms-client-request-id:2cd02b34-d5d9-11e8-8497-02010a20377e\nx-ms-date:Mon, 22 Oct 2018 09:02:35 GMT\nx-ms-version:2017-07-29\n/XXXX/d620b62-fk-sp-slm-libertalia-store-backup/fk-sp-slm-libertalia-store-backup/Full/1082802__elasticsearch__2018-10-22__12-55-00__full/indices/hHvoKSWBSIeuhA1zCXvDVg/4/__5z.part0\nblockid:TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQTJOekV3T0RnMk5EQSUzRA==\ncomp:block\ntimeout:600'.</AuthenticationErrorDetail></Error>`

Analytic Log:
`0900/000000.log:1.0;2018-10-22T09:02:17.2404977Z;PutBlock;ServerTimeoutError;500;429;259;authenticated;fkdr;fkdr;blob;"https://XXXXX.blob.core.windows.net/d620b62-fk-sp-slm-libertalia-store-backup/fk-sp-slm-libertalia-store-backup/Full/1082802__elasticsearch__2018-10-22__12-55-00__full/indices/hHvoKSWBSIeuhA1zCXvDVg/4/__5z.part0?comp=block&amp;blockid=TURBd01EQXdNREF3TURBd01EQXdNREF3TURBd01EQTJOekV3T0RnMk5EQSUzRA==&amp;timeout=600";"/XXXX/d620b62-fk-sp-slm-libertalia-store-backup/fk-sp-slm-libertalia-store-backup/Full/1082802__elasticsearch__2018-10-22__12-55-00__full/indices/hHvoKSWBSIeuhA1zCXvDVg/4/__5z.part0";dea307a8-101e-0047-23e5-69a2e9000000;0;103.4.254.20:15436;2017-07-29;660;8388608;177;245;67108864;;;;;;"Azure-Storage/1.1.0-1.1.0 (Python CPython 2.7.13; Linux 4.9.0-4-amd64)";;"2cd02b34-d5d9-11e8-8497-02010a20377e"`

We are not seeing any other request failure for this in analytic logs. We are already following up with Azure Premier Support for the issue. Our queries:
1. Why is ServerTimeOutError not coming to the SDK and not being communicated to the client?
2.  Why are there 2 errors (ServerTimeOut and Authentication Error) in the backend when we are sending only one request from our end? Is the first error we send being retried and if yes, how can we make sure that is the case? 
3. If it is caused due to partioning(as informed by Storage team by Support ticket), why is this happening on every backup and what limits are we hitting that is causing this so many times?

I am sharing the issue details with the support ticket. Can this be followed up internally. Please ask the support ticket or myself in case you require any more information.

### Have you found a mitigation/solution?
No, The error happens daily on file transfer for these types of data set.

**Comment by zezha-msft** [comment]
Hi @rajreeshabh, thanks for reaching out!

I noticed that you have the legacy version of the SDK (`azure-storage==0.34.3`) installed alongside the version 1.1.0 of the current SDKs. This is very likely to cause problems. Please uninstall all Storage packages, and re-install only the latest version 1.3.1 to verify whether your problem persists.

As for your questions:

1. The same client request ID is used across all retries, so that we can track the individual requests. However, authentication errors are not retried.
2. From the logs you posted, I have a hard time telling whether the same request triggered ServerTimeOutError on the service side, as it is challenging to read without the right formatting and context. Perhaps the support team can help with this question. 
3. I do not think you are hitting any throttling, please clean up your environment and give it another try. Thanks!

**Comment by zezha-msft** [comment]
Closing due to lack of response. Please let me know if you need any further assistance.
