### ISSUE TITLE
get_blob_properties doesn't return HTTP headers

### ISSUE THREAD

**Issue by coderall** [Azure/azure-storage-python#530]
### Which service(blob, file, queue) does this issue concern?

blob
### What problem was encountered?
get_blob_properties interface doesn't return the HTTP response headers like Content-Type,Content-Encoding

### Have you found a mitigation/solution?
no

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by rickle-msft** [comment]
Hi, @coderall. Thanks for asking this question! get_blob_properties returns a Blob type, which has a BlobProperties object as a field. BlobProperties contains a ContentSettings field, which has the information you're looking for. If you have more trouble from there, please let me know!
