### ISSUE TITLE
All of the rows can be fetched even if without continuation token

### ISSUE THREAD

**Issue by imeya** [Azure/azure-storage-python#531]
as per this [link](https://docs.microsoft.com/en-us/rest/api/storageservices/Query-Entities?redirectedfrom=MSDN#remarks), only 1000 rows can be fetched if without continuation token.
But even if I just use this line of code(without continuation token):

```
count=0
entities = table_service.query_entities(table,filter='PartitionKey eq 'xxx' '')
for entity in entities:
      count = count +1

print(count)

```
I can fetch all of the rows (more than 10000 rows), so I wonder if this is expected(without continuation token)? or I misunderstand it?

**Comment by rickle-msft** [comment]
Hi, @imeya. Per our issue template, please go here for all table related questions: https://github.com/Azure/azure-cosmosdb-python.
