### ISSUE TITLE
Re-definition of _StorageSharedKeyAuthentication breaks mypy

### ISSUE THREAD

**Issue by andrey-snowflake** [Azure/azure-storage-python#539]
### Which service(blob, file, queue) does this issue concern?

storage

### Which version of the SDK was used? Please provide the output of `pip freeze`.

azure-common==1.1.14
azure-nspkg==2.0.0
azure-storage==0.36.0

### What problem was encountered?

mypy stops with a "Cycle in inheritance hierarchy" when trying to scan package

### Have you found a mitigation/solution?

yes, remove these two lines — https://github.com/Azure/azure-storage-python/blob/master/azure-storage-common/azure/storage/common/_auth.py#L77-L78

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by zezha-msft** [comment]
Hi @andrey-snowflake, thanks for your feedback! We can fix this in the next release.

Btw I see that you are using an outdated version of the SDK (0.36.0 which is now deprecated). Would you like to upgrade to the [latest version](https://github.com/Azure/azure-storage-python#option-1-via-pypi)?

**Comment by xiafu-msft** [comment]
Hi @andrey-snowflake 
The release by this Friday(7/12/2019) should be able to fix the problem you met!
Close the issue currently, feel free to reopen that is you have further questions!

Thanks again for pointing this out and providing a solution!
