### ISSUE TITLE
Default retry time span too short for exponential retry

### ISSUE THREAD

**Issue by amerkel2** [Azure/azure-storage-python#541]
### Which service(blob, file, queue) does this issue concern?
blob

### Which version of the SDK was used? Please provide the output of `pip freeze`.
azure-common==1.1.16
azure-nspkg==3.0.2
azure-storage-blob==1.4.0
azure-storage-common==1.4.0
azure-storage-nspkg==3.1.0

### What problem was encountered?
we have observed failures because of temporary DNS errors like
```
IOError: ConnectionError: HTTPSConnectionPool(host='<REMOVED>.blob.core.windows.net', port=443):
   Max retries exceeded with url: <REMOVED> (Caused by NewConnectionError('<urllib3.connection.VerifiredHTTPSConnection object at 0x7fa60114eb10>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```
We suspect this is because of live reconfigurations of the network fabric, which seem to take up to 120s, a time span which is not covered with the default of three retries of the exponential backoff policy, which is applied by default for block blob service.

### Have you found a mitigation/solution?
We recommend to increase the default to five retries (this will result in retries after 15, 33, 57, 99, and 196 seconds).

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by zezha-msft** [comment]
Hi @amerkel2, thanks for reaching out!

Could you please clarify what you meant by "live reconfigurations of the network fabric"? Is this something inside Azure or your own environment?

**Comment by amerkel2** [comment]
Hi,

this is something inside Azure. We notice from time to time that the blob service's name cannot be resolved for up to two minutes. So we assume that some component of the network is being reconfigured on the Azure side.

**Comment by zezha-msft** [comment]
@amerkel2 thanks for the explanation! To clarify, is your code running on a VM in the same region as the Storage Account?

@mirobers is this a normal behavior?

**Comment by mirobers** [comment]
There's nothing on the Azure Storage side that would cause DNS resolution of a storage account endpoint to temporarily fail. I'd dig into the source of these issues as two minutes is a rather long time for such an event.

**Comment by zezha-msft** [comment]
@amerkel2 please reach out to Azure Support if this problem persists.

**Comment by amerkel2** [comment]
OK, will do, thanks for checking!
