### ISSUE TITLE
Queue Message Encoding Issue

### ISSUE THREAD

**Issue by plooploops** [Azure/azure-storage-python#544]
We're looking to use the Azure Queue Service and wanted to see if it's possible to turn off the encoding in the queue service (either through portal or Python SDK).

This is how the messages are packed and placed into the queue.

def pack(message):
    dumped = utils.dumps(message)
    compressed = zlib.compress(dumped.encode('utf8'))
    b64encoded = base64.b64encode(compressed)
    return b64encoded.decode('ascii')

We'd like to unpack the messages.  When we try to decode this to ascii, we get an error that looks like this:

'ascii' codec can't encode characters in position 1-2: ordinal not in range(128)

So the data looks like this in the queue.

x��\iW۸��_���\ɖ�ӄ@��h��9m&^�e��9�߯dgeBC

![image](https://user-images.githubusercontent.com/2498998/51356865-16f08980-1a71-11e9-8e6e-5ce421a647be.png)

Is there a way to stop the queue from performing additional encoding?

+@priyaananthasankar

**Comment by zezha-msft** [comment]
Hi @plooploops, to my understanding, this issue has been resolved offline, is that correct?

If yes, please summarize the solution if you'd like to share it with others, and close this issue.

**Comment by rickle-msft** [comment]
I believe this issue was resolved offline. Setting the encoding function on the queueservice (queueservice.encoding_function = my_encoding_function) seems to do the trick. I'll close it as I believe it is resolved, but @plooploops should feel free to reopen it if there are further difficulties.
