### ISSUE TITLE
remnants of azure.storage.table

### ISSUE THREAD

**Issue by kwhitehall** [Azure/azure-storage-python#555]
### Which service(blob, file, queue) does this issue concern?
N/A

### Which version of the SDK was used? Please provide the output of `pip freeze`.
0.36.0

### What problem was encountered?
In azure.storage.__version__=0.36.0 
the remnants of dir(azure.storage.table)=['AzureBatchOperationError', 'AzureBatchValidationError', 'EdmType', 'Entity', 'EntityProperty', 'Table', 'TableBatch', 'TablePayloadFormat', 'TablePermissions', 'TableService', '__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__', '_deserialization', '_encryption', '_error', '_request', '_serialization', 'models', 'tablebatch', 'tableservice']
even though this functionality isn't available

### Have you found a mitigation/solution?
N/A

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by zezha-msft** [comment]
Hi @kwhitehall, thanks for reaching out! Could you please clarify your question?

Btw 0.36.0 is the legacy monolithic version of the Storage SDK that still included the table service. Please refer to the [instructions](https://github.com/Azure/azure-storage-python#option-1-via-pypi) on how to install the latest versions.

**Comment by kwhitehall** [comment]
Ack'ed @zezha-msft.Looks like I was trigger happy with opening the issue then as there is no issue that the table service is included in 0.36.0. Many apologies! I'll go ahead and close the issue.

**Comment by zezha-msft** [comment]
@kwhitehall no worries! 😄
