### ISSUE TITLE
Support for Python 3.6 and Python 3.7

### ISSUE THREAD

**Issue by polarapfel** [Azure/azure-storage-python#560]
Hi,

In the [documentation](https://azure-storage.readthedocs.io/), it states the SDK only supports Python up to 3.5. Is this still accurate?

If it's still accurate, I would urge to include support for Python 3.6 and 3.7 ASAP, as Azure Functions for Python only supports Python 3.6 in preview currently and is working to supporting Python 3.7. Python 3.6.8 is the current release in 3.6 and the last release to receive bug-fix updates.

thanks,

Tobias W.

**Comment by zezha-msft** [comment]
Hi @polarapfel, sorry I forgot to update that part. It'n our [README](https://github.com/Azure/azure-storage-python#minimum-requirements). I'll update it in the next release.

**Comment by polarapfel** [comment]
> Hi @polarapfel, sorry I forgot to update that part. It'n our [README](https://github.com/Azure/azure-storage-python#minimum-requirements). I'll update it in the next release.

Thanks!

**Comment by heya-msft** [comment]
My script stopped working after upgrading python to 3.7.0.  How do I downgrade python back to 3.6 on Mac?

**Comment by polarapfel** [comment]
> My script stopped working after upgrading python to 3.7.0. How do I downgrade python back to 3.6 on Mac?

How did you install Python on Mac? Using the binary installer from Python.org?

You should be able to install the binary installer from the 3.6 branch over the 3.7 branch and it should replace it.

**Comment by zezha-msft** [comment]
Hi @heya-msft, what was the failure? Was it related to the Storage SDK?

**Comment by heya-msft** [comment]
Yes, when I upgraded Python to 3.7, my python script stopped working using Storage SDK.
It gave me an exception.  I don’t have the stack trace anymore.
Same for Python 3.6.  Finally, I reverted it back to Python 2.7 (my original version), everything works fine.

When will the Azure Python SDK support Python 3.7?

Thanks,
Helen

**Comment by zezha-msft** [comment]
@heya-msft it already does.

Please verify your script, as the jump from Python 2.7 -> 3.* can be disruptive.

**Comment by heya-msft** [comment]
The exception is from one of the azure storage packages.  I don’t think it’s Python3.7 ready.  There is an open issue for adding support for 3.7 on GitHub.  I think right now it supports up to Python3.6.

Please update your README if it’s supporting 3.7.  There is nowhere said otherwise.

I will try it again later for 3.7.  Pretty sure it didn’t work for me.

**Comment by zezha-msft** [comment]
Hi @heya-msft, we have [CI coverage including Python 3.6-3.7](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4922).

Which issue are you referring to? This one?

> an open issue for adding support for 3.7 on GitHub

I updated the [README](https://github.com/Azure/azure-storage-python#minimum-requirements) to include 3.7. Thanks.

**Comment by heya-msft** [comment]
Nice, I will try Python 3.7 again using Storage SDK.
If I run into exception, I will send you the stack trace.

I need Python 2.7 today for running my python script for a build release.

Thank you,
Helen
