### ISSUE TITLE
FileService object in azure.storage.file has SSL 'certificate verify failed' error 

### ISSUE THREAD

**Issue by utadamai** [Azure/azure-storage-python#567]
just updated on one setup to the latest azure python sdk, then when trying to create a file share in storage account, it's giving 'certificate verify failed':

azure.common.AzureException: HTTPSConnectionPool(host='smallflowesa.file.core.windows.net', port=443): Max retries exceeded with url: /hett?restype=share (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

on the other setup with older version of python sdk, everything works fine. 
my code:

from azure.storage.file import FileService

file_service = FileService(account_name='**',account_key='**',endpoint_suffix='core.windows.net')

file_service.create_share('***')

**Comment by zezha-msft** [comment]
Hi @utadamai, thanks for reaching out!

It's most likely not a problem in the SDK itself. Please refer to this relevant [post](https://stackoverflow.com/a/42334357/4179859).

**Comment by championbally** [comment]
Hello @zezha-msft I need your help. I am trying to create an Azure file share but I am getting a HTTPSCONNECTIONPOOL error. What could be the problem? Please help me on urgent basis as I have the certification exam in 3 days. Thank you!

**Comment by xiafu-msft** [comment]
Hi @championbally 

Did you you see the relevant post https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error/42334357#42334357 zezha referred to?

**Comment by championbally** [comment]
Hi @xiafu-msft 
Thanks for your reply, I read that post but that post seems  to not answer to my specific problem. I have an HTTPs problemand I use Windows but that post talks about Python certificate for MacOS

**Comment by xiafu-msft** [comment]
Hi @championbally 

Did you try some suggested way and see if it can be resolved? eg. https://answers.microsoft.com/en-us/windows/forum/all/ssl-error-preventing-connection-in-windows-10/192436e5-e37b-4b4c-a4e0-c4ec744b0f5c

**Comment by championbally** [comment]
Hi @xiafu-msft 

Thanks for your time. I think the SSL configuration helped me a little bit because before I was getting the HTTPSCONNECTIONPOOL error along with the port 443 error but now I am getting only the HTTPSCONNECTIONPOOL error only. Kindly find attached a screenshot of the error I am getting along with the command I am getting error on.
![HTTPSCONNECTIONPOOL ERROR SCREENSHOT2](https://user-images.githubusercontent.com/32218799/82534871-90b3ee00-9b63-11ea-83b3-c817b328e1cc.PNG)

**Comment by championbally** [comment]
Also can you explain what this HTTPSCONNECTIONPOOL error is all about? I think if I understand the error itself I can be able to solve the issue. Thank you so much
