### ISSUE TITLE
PUBLIC NOTICE: Azure Storage Python Revamp

### ISSUE THREAD

**Issue by emgerner-msft** [Azure/azure-storage-python#57]
The Azure Storage team is taking ownership of the storage runtime library which is present in this repository and released as the azure-storage package on pypi. As promised in the [package change announcement](https://github.com/Azure/azure-sdk-for-python/issues/440), there will be many new storage features coming soon.

The first round of changes will be the largest and will bring the library up to the newest service version. As it currently stands, the library supports very few features which were released after 2012. To best support all the new features released on the service in the past 3 years, we will be making breaking changes to bring the Python storage library up to date. Some of these changes include append blob support, file service support, table batch refactors, replacing AtomPub with JSON in table, account SAS, improved response parsing and many other small features and API updates. 

All of this is being done in the dev branch and we will be maintaining ChangeLog and BreakingChanges files so you can see a summary of what’s happening. Note that this branch should not be considered stable!

After bringing the library up to the latest version we will do a preview release. Then we will begin adding additional improvements. These may include items such as built-in MD5 calculation, automatically following continuation tokens on list APIs, improved queue message encoding support, and many others, in addition to improvements the community suggests. 

We’d love to hear from you!

Thanks,
The Azure Storage Team

**Comment by jehine-MSFT** [comment]
Closing this announcement as we have now released the 0.30 version. #132
