### ISSUE TITLE
_common_serialization.py missing import of DEV_ACCOUNT_NAME

### ISSUE THREAD

**Issue by DinoV** [Azure/azure-storage-python#58]
It should have a:
```python
from .constants import DEV_ACCOUNT_NAME
```

so that _update_request_uri_query_local_storage works against the storage emulator.

**Comment by emgerner-msft** [comment]
Merged the suggested fix. A build with this will go out with the next bug fix release. Thanks!

**Comment by jehine-MSFT** [comment]
Hello @DinoV,

We have released the 0.30 version (#132) which addressed this feature request. If you have issues with the new version in regards to this issue, please reopen it and continue the discussion.

Thanks!
