### ISSUE TITLE
unable to install azure packages when azure publish - cannot install cryptography-2.6.1 dependency:

### ISSUE THREAD

**Issue by vksantoshsunny** [Azure/azure-storage-python#585]
### Which service(blob, file, queue) does this issue concern?
blob

### Which version of the SDK was used? Please provide the output of `pip freeze`.
1.5.0

### What problem was encountered?
cannot install cryptography-2.6.1 dependency: binary dependencies without wheels are not supported.  Use the --build-native-deps option to automatically build and configure the dependencies using a Docker container. More information at https://aka.ms/func-python-publish

### Have you found a mitigation/solution?
No

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by vksantoshsunny** [comment]
this is my requirements.txt

# Minimum packages for azure functions
azure-functions
azure-functions-worker
grpcio==1.14.1
grpcio-tools==1.14.1
protobuf==3.6.1
six==1.11.0
azure-storage-blob


# Additional packages
numpy==1.15.4   
python-dateutil
ruamel.yaml
pytz
requests

When I remove azure-storage-blob the dependency error goes away. So it is something to do with the azure-storage-blob python package.

**Comment by zezha-msft** [comment]
Hi @vksantoshsunny, thanks for reaching out. Have you tried the recommended workaround in the error message?

**Comment by vksantoshsunny** [comment]
Hi @zezha-msft  due to security reasons we I am not allowed to use docker in my case. So this issue is still pending for me. Thank you.

**Comment by zezha-msft** [comment]
@vksantoshsunny ah I see.

@lmazuel any advice on this issue?

**Comment by lmazuel** [comment]
I would suggest to move it to the function worker repo, it's not a storage or Python issue:
https://github.com/Azure/azure-functions-python-worker
