### ISSUE TITLE
Allow 'UseDevelopmentStorage=true' in the storage connection string

### ISSUE THREAD

**Issue by crwilcox** [Azure/azure-storage-python#6]
### Description:
Right now the only way to run in storage emulator is to pass None for both account key/name, and set the EMULATED env variable.  We should allow setting that in the connection string, like node.js storage sdk.

**Comment by jehine-MSFT** [comment]
Thanks for the feature request! We are working on fully supporting the storage emulator like we do in other libraries for our next major release.

Thanks!

**Comment by jehine-MSFT** [comment]
Hello @crwilcox ,

We have released the 0.30 version (#132) which addressed this feature request. Now to enable emulator support, all you need to do is pass the is_emulated=True bool when creating your Storage service. If you have issues with the new version in regards to this issue, please reopen it and continue the discussion.

Thanks!
