### ISSUE TITLE
Sample code for using azure-storage-blob

### ISSUE THREAD

**Issue by SG-Gank** [Azure/azure-storage-python#607]
### Which version of the SDK was used? Please provide the output of `pip freeze`.
azure-storage-blob

### What problem was encountered?

Can someone provide sample code on this package - azure-storage-blob
Specifically, how to "update" a blob within a blob container?

### Have you found a mitigation/solution?

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by zezha-msft** [comment]
Hi, please refer to the samples [here](https://github.com/Azure/azure-storage-python/blob/master/samples/blob/block_blob_usage.py#L315).
