### ISSUE TITLE
Unintuitive behaviour: forward slash in the end of container name creates unnamed folder

### ISSUE THREAD

**Issue by pavithraks** [Azure/azure-storage-python#618]
### Which service(blob, file, queue) does this issue concern?
blob

### Which version of the SDK was used? Please provide the output of `pip freeze`.
1.4.0

### What problem was encountered?
If container name has a forward slash in the end, the function call `create_blob_from_path` creates an unnamed folder in azure storage and then places the file/blob in there. It seems counterintuitive that a forward slash in the end implies creating a new folder. 

### Have you found a mitigation/solution?
Well, I just don't use the forward slash. A small note in the documentation on this will really help. It took me a while to debug this. 

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by xiafu-msft** [comment]
Hi @pavithraks,

Thanks a lot for reaching out! 

The container name may only contain lowercase letters, numbers, and hyphens, and must begin with a letter or a number. Each hyphen must be preceded and followed by a non-hyphen character. The name must also be between 3 and 63 characters long.

We will update the doc to make it more clear! Thanks.

**Comment by xiafu-msft** [comment]
Hi @pavithraks 

The pull request to update create_container doc has been updated and should be able to get released by the end of this week. Close this issue for now, feel free to reopen it if you need further help!

Thanks
