### ISSUE TITLE
X-MS-VERSION header incorrect value

### ISSUE THREAD

**Issue by konradsitarz** [Azure/azure-storage-python#631]
I use azure-storage-blob to send file to blob storage.

SDK versions:
```
azure-common==1.1.23
azure-storage-blob==2.1.0
azure-storage-common==2.1.0
```

When I try to send file I got error that the value of the X-MS-VERSION header has wrong value.
```
Exception=The value for one of the HTTP headers is not in the correct format. ErrorCode: InvalidHeaderValue<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidHeaderValue</Code><Message>The value for one of the HTTP headers is not in the correct format.RequestId:c0e6b190-201e-0062-4390-59222d000000Time:2019-08-23T08:57:32.0999355Z</Message><HeaderName>x-ms-version</HeaderName><HeaderValue>2019-02-02</HeaderValue></Error>.
```

What should be the value of the header and how to change it to be able to use it in code?

I managed to change the value manually inside the **azure/storage/blob/_constants.py**
X_MS_VERSION but I don't know what should be working value.

**UPDATE:**
I replaced the 
`X_MS_VERSION= '2019-02-02'`
with previous version I know about versions from [here](https://docs.microsoft.com/en-us/rest/api/storageservices/previous-azure-storage-service-versions).
`X_MS_VERSION = '2018-11-09'`

and it worked.

**HACK SOLUTION**
While creating blobService i replace the _X_MS_VERSION parameter with working one.
It's not much of a clear hack but it works.

```
blobService = BlockBlobService(connection_string=connection_string)

blobService._X_MS_VERSION = '2018-11-09'
```

**Comment by zezha-msft** [comment]
Hi @konradsitarz, thanks for reaching out!

You are not using public Azure, right? The latest service version may not be deployed in your platform.

**Comment by zezha-msft** [comment]
@konradsitarz it appears that this might be a configuration problem. My colleagues are working on resolving it. I'll update this thread shortly.

**Comment by zezha-msft** [comment]
@konradsitarz it's fixed! Please let us know if you have any other issue.

**Comment by SSUS31** [comment]
Facing same issue

**Comment by zezha-msft** [comment]
@SSUS31 please try the latest SDK version 12. Thanks!
