### ISSUE TITLE
Unable to download files from azure file share locally when using SDK shows : A portion of the specified file is locked by an SMB client

### ISSUE THREAD

**Issue by c2c-engg-20170111** [Azure/azure-storage-python#638]
### Which service(blob, file, queue) does this issue concern?
File service

### Which version of the SDK was used? Please provide the output of `pip freeze`.
azure-storage-file==2.1.0

### What problem was encountered?
while downloading file share data locally it shows bellow error:
![image](https://user-images.githubusercontent.com/50101798/66896061-ce6ef800-f011-11e9-90b2-e61a96cb8cc2.png)

### Have you found a mitigation/solution?
no

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by zezha-msft** [comment]
Hi @c2c-engg-20170111, it appears that the file share is mounted and being used at the same time.

We cannot do much on the SDK side unfortunately. Please lift the lock and try again.
