### ISSUE TITLE
Databricks No matching distribution found for Azure-blob-storage

### ISSUE THREAD

**Issue by ryanwrationalcx** [Azure/azure-storage-python#643]
### Which version of the SDK was used? Please provide the output of `pip freeze`.
Azure Blob storage == 2.0.1

### What problem was encountered? It with trying to import the library into the blob storage. Here is the message - java.lang.RuntimeException: ManagedLibraryInstallFailed: org.apache.spark.SparkException: Process List(/databricks/python/bin/pip, install, Azure-blob-storage, --index-url, https://pypi.org/project/azure-storage-blob/, --disable-pip-version-check) exited with code 1.   ERROR: Could not find a version that satisfies the requirement Azure-blob-storage (from versions: none)
ERROR: No matching distribution found for Azure-blob-storage
 for library:PythonPyPiPkgId(Azure-blob-storage,None,Some(https://pypi.org/project/azure-storage-blob/),List()),isSharedLibrary=false

### Have you found a mitigation/solution? no

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by ryanwrationalcx** [comment]
Is there a PyPI url I can point my databricks library to for this update? I point to the current one and it comes up with 12.0.0, which my program says is out of date. https://pypi.org/project/azure-storage-blob/

**Comment by xiafu-msft** [comment]
Hi @ryanwrationalcx 
are you asking this https://pypi.org/project/azure-storage-blob/2.1.0/ 
BTW you can find all releases by clicking “History” from the link you provided 😊

**Comment by xiafu-msft** [comment]
Hi @ryanwrationalcx  
I'll close this issue for now, feel free to reopen it if you need other help! ^_^
