### ISSUE TITLE
How can I remove the error output?

### ISSUE THREAD

**Issue by DEADSEC-SECURITY** [Azure/azure-storage-python#645]
### Which service(blob, file, queue) does this issue concern?
I'm using azure.storage.file

### Which version of the SDK was used? Please provide the output of `pip freeze`.
azure.storage.file==2.1.0

### What problem was encountered?
Is there a way to remove the output from the DirectoryNotEmpty error? I made a way to handle this error and I would like to remove its output so it doesn't show.

The output I would like to remove:
`Client-Request-ID=0210a318-1540-11ea-b30c-74e5f9368f17 Retry policy did not allow for a retry: Server-Timestamp=Mon, 02 Dec 2019 20:12:04 GMT, Server-Request-ID=06b43dd9-601a-0058-584c-a907c7000000, HTTP status code=409, Exception=The specified directory is not empty. ErrorCode: DirectoryNotEmpty<?xml version="1.0" encoding="utf-8"?><Error><Code>DirectoryNotEmpty</Code><Message>The specified directory is not empty.RequestId:06b43dd9-601a-0058-584c-a907c7000000Time:2019-12-02T20:12:04.6902303Z</Message></Error>.`

### Have you found a mitigation/solution?

**Comment by xiafu-msft** [comment]
Hi @DEADSEC-SECURITY 

Thanks for reaching out!
I don't think you could disable logging the info only for this specific error message currently. But if you want to disable logging [here is the link](https://github.com/Azure/azure-storage-python#logging)

Feel free to let me know if doesn't help!
