### ISSUE TITLE
Support multiple clouds on vendor package

### ISSUE THREAD

**Issue by grgarcia-ms** [Azure/azure-storage-python#646]
### Which service(blob, file, queue) does this issue concern?
storage

### Which version of the SDK was used? Please provide the output of `pip freeze`.
py3:0.11.9

### What problem was encountered?
hardcoded constant to blob.core.windows.net, this does not work in other clouds

### Have you found a mitigation/solution?
https://github.com/Azure/azure-storage-python/blob/master/azure-storage-common/azure/storage/common/_constants.py#L24

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by xiafu-msft** [comment]
Hi @grgarcia-ms 

Thanks for reaching out!
It's not hardcoded, you could set `custom_domain` when your endpoint is not in this format
`{account_name}.{service}.{endpoint_suffix}`
if your endpoint is in that format, you can set `endpoint_suffix` when you create a service instance.
In addition, set `connection_string` will also take your customized endpoint if your customized endpoint is in the connection string.

For example:
`service_client = AppendBlobService(account_name, account_key, endpoint_suffix='core.chinacloudapi.cn')`
code link: https://github.com/Azure/azure-storage-python/blob/master/azure-storage-blob/azure/storage/blob/appendblobservice.py#L73-L110

**Comment by xiafu-msft** [comment]
Close this for now, if your problem is not addressed feel free to reopen it! ^_^
