### ISSUE TITLE
BlobService.get_page_ranges should support timeout parameter

### ISSUE THREAD

**Issue by pneumee** [Azure/azure-storage-python#65]
https://msdn.microsoft.com/en-us/library/azure/ee691973.aspx

A timeout parameter is supported by the API, but not implemented in the SDK. The default seems very short (~ 25 seconds).

**Comment by emgerner-msft** [comment]
Right now the library supports setting a service-wide timeout by specifying the timeout parameter in the blob service initialization. This is then sent for all the APIs (for example get page ranges). You can set it higher than the default if desired, but note [the limitations](https://msdn.microsoft.com/en-us/library/azure/dd179431.aspx).

The current plan for the [future version of the library](https://github.com/Azure/azure-storage-python/issues/57) is to not set a default on the service. We will then look at adding timeout to some (the more timeout sensitive) or all APIs. We're still considering exact design, so if you have in mind what you'd like to see ideally we're happy to chat.

**Comment by pneumee** [comment]
Setting that timeout doesn't seem to have any affect. I had it set to 300, it still timed out after 25 seconds. Seems like the service-wide setting when creating a BlobService object is client-side, while the timeout setting passed to the API is server-side?

**Comment by emgerner-msft** [comment]
Yes, this is correct. The older library sets the timeout you specify on the underlying Python session request (ie, client side). The server timeout will not be set meaning the service defaults I linked to above will be applied on the service. I'll modify the above response to make that clearer.

In the newer version we will set both the server timeout (sent in the query) and a client side timeout on the request (like currently). Sending a server timeout isn't very helpful if the connection is lost for some reason, so the client side timeout is good to have in addition. How these interplay is an interesting design point, and how we want to expose this well is a discussion we're currently having.

**Comment by emgerner-msft** [comment]
We have released the 0.30 version (#132) which addresses this feature request.

The timeout parameter supported by the REST API is now exposed for every method in the SDK which makes service calls. Client side timeout is not out yet (still being designed), but my understanding of this initial question is just for server timeout. If you have issues with the new version in regards to this issue, please reopen it and continue the discussion.
