### ISSUE TITLE
Adding delete_blob feature of deleting folders

### ISSUE THREAD

**Issue by JavierHernandezMontes** [Azure/azure-storage-python#659]
### Which service(blob, file, queue) does this issue concern?
blob

### Which version of the SDK was used? Please provide the output of `pip freeze`.
azure-storage-blob==1.5.0

### What problem was encountered?
It's not possible to delete a blob that is a folder without deleting all its elements first, I think it's a needed feature

### Have you found a mitigation/solution?

Note: for table service, please post the issue here instead: https://github.com/Azure/azure-cosmosdb-python.

**Comment by xiafu-msft** [comment]
Hi @JavierHernandezMontes 

Thanks for reaching out!
Currently the service doesn't have plan to delete folders for blob, while you can create a HNS enabled account and delete the folder. azure-storage-file-datalake is the SDK for HNS enabled account https://azuresdkdocs.blob.core.windows.net/$web/python/azure-storage-file-datalake/12.0.0/index.html.
