### ISSUE TITLE
I got some warnings about SyntaxWarning on Python 3.8.3

### ISSUE THREAD

**Issue by AliYmn** [Azure/azure-storage-python#664]
### Which service(blob, file, queue) does this issue concern?
- Blob

### Which version of the SDK was used?

azure-common==1.1.16
azure-nspkg==3.0.2
azure-storage==0.36.0
azure-storage-blob==2.1.0
azure-storage-common==2.1.0

### What problem was encountered?
When i push my project on heroku, i got some warnings about Syntax Warning.
<center><img src="https://i.ibb.co/6HjHyFy/Screenshot-from-2020-05-31-02-52-11.png"></center>

### Have you found a mitigation/solution?
No.

**Comment by xiafu-msft** [comment]
Hi @AliYmn 
Thanks for reporting this, there is a discussion about whether to have a new release of this package to suppress the warning message

**Comment by logachev** [comment]
@xiafu-msft are there any updates?

**Comment by stefangordon** [comment]
Is this issue being prioritized appropriately?  Is there an update on when we can expect a fix?
