### ISSUE TITLE
Import errors with BlockBlobService

### ISSUE THREAD

**Issue by kmair** [Azure/azure-storage-python#666]
### Which service(blob, file, queue) does this issue concern?
Only the BlockBlobService importing issue. Rest are being correctly imported

### Which version of the SDK was used? Please provide the output of `pip freeze`.
azure-core==1.6.0
azure-storage-blob==12.3.1

### What problem was encountered?
On trying to run:
from azure.storage.blob import BlockBlobService

Results in:
ImportError: cannot import name 'BlockBlobService' from 'azure.storage.blob' (C:\Users\..\azure\storage\blob\__init__.py)

### Have you found a mitigation/solution?
Can't solve the import error

**Comment by xiafu-msft** [comment]
Hi @kmair 
you are looking at a wrong repo. https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/storage/azure-storage-blob is the correct repo

**Comment by xiafu-msft** [comment]
please refer to the wiki https://github.com/Azure/azure-storage-python/wiki#frequently-encountered-problem-no-module-named-azurestorageblob 

I'll close this issue for now, if you still have the problem please feel free to reopen it!
