### ISSUE TITLE
ModuleNotFoundError: No module named 'azure.storage.blob'

### ISSUE THREAD

**Issue by planetmarshall** [Azure/azure-storage-python#667]
### Which version of the SDK was used? Please provide the output of `pip freeze`.

```
azure-common==1.1.25
azure-core==1.6.0
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.6
azure-devops==6.0.0b2
azure-nspkg==3.0.2
azure-storage-blob==12.3.1
azure-storage-common==2.1.0
azure-storage-file==2.1.0
```

### What problem was encountered?

Received the following error: `ModuleNotFoundError: No module named 'azure.storage.blob'` when executing the following line in a Python script

`from azure.storage.blob import BlobServiceClient, BlobClient, ContainerClient`

The script is executing on a hosted Microsoft VM on Azure Pipelines with Python 3.8.1

### Have you found a mitigation/solution?

No.

**Comment by xiafu-msft** [comment]
Hi @planetmarshall 
Thanks for reaching out! please see https://github.com/Azure/azure-storage-python/wiki

**Comment by xiafu-msft** [comment]
Feel free to reopen it if you still have the problem!
