### ISSUE TITLE
RowKey with ~ fails with error message for a bad auth header

### ISSUE THREAD

**Issue by crwilcox** [Azure/azure-storage-python#76]
`table_service.insert_or_replace_entity('table', 'partition', 'row~key')` fails.

The issue is that row keys cannot have a `~` (U+007E) character.

I am unsure where to report the issue with the documentation but ~ is not called out as a character limitation in the list restricted for row keys: https://msdn.microsoft.com/library/azure/dd179338.aspx

This is the error that is provided and is misleading:
```
azure\storage\_common_error.py", line 82, in _general_error_handler
    raise AzureHttpError(message, http_error.status)
azure.common.AzureHttpError: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>AuthenticationFailed</m:code><m:message xml:lang="en-US">Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:3fc9641b-0002-0104-2e2a-26f9c9000000
Time:2015-11-23T20:07:19.6220380Z</m:message></m:error>
```

**Comment by jehine-MSFT** [comment]
Do you have a consistent repro for this? It looks like this is an auth failure so that character might still be valid. How you are getting an auth failure is worth taking a look at.

**Comment by jehine-MSFT** [comment]
Hello @crwilcox,

I tried making the following API call using the most up to date version and didn't have any issues:
    self.ts.insert_or_replace_entity(self.table_name, {'PartitionKey': 'partition', 'RowKey': 'row~key'})

Can you try your code on the most recent version of the lib and see if you get the same error?

Thanks!

**Comment by emgerner-msft** [comment]
Closing this issue as I haven't heard anything in a few months. If you have any other questions or concerns in relation to this issue, please reopen it and we'll continue the discussion!
