### ISSUE TITLE
Upload large files (>195 GB)

### ISSUE THREAD

**Issue by jmlero** [Azure/azure-storage-python#77]
Hi all,

According to the documentation:
https://msdn.microsoft.com/en-us/library/azure/ee691964.aspx
The maximum size of a blob is 195GB, my question is:
What should be the approach if we need to upload files bigger than 195GB

Thanks,

**Comment by emgerner-msft** [comment]
1. Split your blob until multiple pieces. Upload those to different blobs and when you download, reassemble. If you need some way of tracking on the blob where the next piece is, metadata would be one option.
2. Page blobs. The maximum size for a page blob is 1 TB.

**Comment by jmlero** [comment]
Ok, thanks. So this should be managed before execute our scripts and call the framework.

Offtopic question: Do you know if this limitation was documented time ago? I started working with azure storage and blobs at the beginning of the year and I didn't see before this limitation on the official azure storage documentation.

**Comment by emgerner-msft** [comment]
Yes, this is has been in those docs for a very long time and the limitations have not changed in a very long time. Other docs such as [this one](https://azure.microsoft.com/en-us/documentation/articles/storage-scalability-targets/) also contain that data and one can actually verify the history of modification on public GitHub. Sorry if there was any confusion!
