### ISSUE TITLE
Documentation on ReadTheDocs is missing all the module and method reference information

### ISSUE THREAD

**Issue by adamnovak** [Azure/azure-storage-python#78]
The table service `query_entities` method is defined here:

https://github.com/Azure/azure-storage-python/blob/09e9f186740407672777d6cb6646c33a2273e1a8/azure/storage/table/tableservice.py#L385

However, it does not show up in the ReadTheDocs documentation, either when doing a search:

http://azure-storage.readthedocs.org/en/latest/search.html?q=query_entities&check_keywords=yes&area=default

Or when looking at the page about the tables:

http://azure-storage.readthedocs.org/en/latest/table.html

Or when looking at the module page in the index:

http://azure-storage.readthedocs.org/en/latest/ref/azure.storage.table.tableservice.html

In fact, it seems like all the module pages, which are presumably the official API reference for what each method does and what each argument means, are blank. Presumably this isn't intentional.

**Comment by emgerner-msft** [comment]
Hmmm, taking a look now. Looks like a publishing process issue. We're in the process of moving our docs from a custom format to the ReStructured text supported best by Sphinx, so I'm guessing something got messed up there.

**Comment by emgerner-msft** [comment]
ReadTheDocs is still having build issues for us, so we've temporarily (or however long it takes to resolve these issues) moved to a [GitHub.io](http://azure.github.io/azure-storage-python/) page.

**Comment by clarkbreyman-yammer** [comment]
@emgerner-msft - Can you elaborate on the build issues you are seeing? It would be nice to get the RTD in a similar state to azure-sdk-for-python
