### ISSUE TITLE
listing a "folder" under container

### ISSUE THREAD

**Issue by chanansh** [Azure/azure-storage-python#79]
How can I list files under a specific regex expression?
If not possible how can I at least get the names of just one level of name (e.g. if path is CONTAINER/top1/bottom, CONTAINER/top2/bottom I would like to get only top1 and top2 rather than listing all the blobs under the container).
I know I can give a prefix to list_blobs but than won't do for what I need above, wouldn't it?!

**Comment by emgerner-msft** [comment]
There is no support for regex expressions in blob listing. If you wanted to get top1 and top2 in the above example, you can make two listing requests -- one with prefix top1 and one with prefix top2. If you know there are no other top* or very few others, you can just use top and filter out any extras.

**Comment by huguesv** [comment]
You can use the 'delimiter' parameter to restrict the results to just the level that you want.  See the test here, where `resp.blobs` contains the files, and `resp.prefixes` contains the folders: https://github.com/Azure/azure-storage-python/blob/master/tests/test_storage_blob.py#L1339

**Comment by emgerner-msft** [comment]
I didn't understand the question originally I think. :) If I'm understanding correctly now, Hugues has it right. Delimiter is the right way to go. I'll delete my original response.

**Comment by chanansh** [comment]
Thanks guys. This is not exactly what I was looking for.  Separating the path from the prefix is just string processing post query. I have a container with hundreds of thousands of blobs. Let me please explain further; I want to list the top hierarchy without having to wait for a long query to return all the blobs. Then,  when a user selects a prefix,  I would like to query just the prefix below the selected one. CloudBerry has implemented something similar so I guess there is an API to do so.

**Comment by emgerner-msft** [comment]
I guess maybe we're not clear on what you want. From the original question it seems like delimiter does what you want -- it gives you back top1 and top2. It doesn't return all blobs. Could you provide an explicit example of what you want vs what delimiter does?

**Comment by AbsoluteMSTR** [comment]
Assuming I have a structure like
`
folder/a/file.dat
folder/b/file.dat
`
I am having a similar issue where
`blob_service.list_blobs('container', 'folder/', delimiter='/').prefixes`
it does not produce `['a', 'b']` for me

**Comment by emgerner-msft** [comment]
What does it produce? How many other blobs do you have in your container?

**Comment by AbsoluteMSTR** [comment]
I figured it out, it creates a next_marker which I have call again and brings up a list of prefixes

**Comment by emgerner-msft** [comment]
Great! Closing this issue as resolved.

**Comment by rakeshkumartiwari** [comment]
I want to get all directory, subdirectory and fles from cntainer (Azure) in c# and I want to show that thig as atree view . Help me...

**Comment by steven123com** [comment]
@AnkurDedania
how could you solve you problem? could you tell the detail? now, I have the same requirements that just want to list all the folders without blobs.

**Comment by AnkurDedania** [comment]
@steven123com
This is so long ago, but basing this from memory and not code. I used the `next_marker` to traverse and find a list of folders.

**Comment by zezha-msft** [comment]
Hi @steven123com, please refer to this [sample](https://github.com/Azure/azure-storage-python/blob/master/samples/blob/container_usage.py#L225) to list using a delimiter.

**Comment by mcsf13m036** [comment]
use walk_blobs function instead to list folders and to list blobs inside specific folder.
name_starts_with will be empty or None to list all folders in first call.

```
def walk_blobs(self, container_name, name_starts_with):
        returnObj = []
        # Instantiate a ContainerClient
        container_client = self.blob_service_client.get_container_client(
            container_name)
        for blob in container_client.walk_blobs(name_starts_with=name_starts_with):
            returnObj.append(blob)

        return returnObj
```
