### ISSUE TITLE
Support for blob type 'Append'

### ISSUE THREAD

**Issue by crwilcox** [Azure/azure-storage-python#8]
### Description:
See http://blogs.msdn.com/b/windowsazurestorage/archive/2015/04/13/introducing-azure-storage-append-blob.aspx

**Comment by jehine-MSFT** [comment]
We have added full support for the Azure Storage AppendBlob service. It will be released in our next major release.

**Comment by huangcd** [comment]
Hi @jehine-MSFT , do you have a estimate time for the next release?

**Comment by emgerner-msft** [comment]
See #57. We're hoping for early 2016, but as always with releases that aren't totally done yet -- no guarantees. :)

**Comment by jehine-MSFT** [comment]
Hello @huangcd ,

We have released the 0.30 version (#132) which addressed this feature request. If you have issues with the new version in regards to this issue, please reopen it and continue the discussion.

Thanks!
