### ISSUE TITLE
get_container_acl always returns an empty azure.storage.models.SignedIdentifiers

### ISSUE THREAD

**Issue by themaxx75** [Azure/azure-storage-python#86]
I can list all containers from an account, and try to get their acl, but it always return an empty SignedIdentifiers object.
```
from azure.storage.blob import BlobService
bs = BlobService('account', 'private_key')

for c in bs.list_containers():
    container_acl = bs.get_container_acl(c.name)
```
`container_acl ` is always an empty object.

**Comment by jehine-MSFT** [comment]
Hello @themaxx75,

Have you made previous calls to set_container_acl? Are you sure these containers have acls already set on them?

Thanks!

**Comment by jehine-MSFT** [comment]
Closing as we have not received a response for this issue. Please reopen the issue if you have a repro for us.

Thanks!
