### ISSUE TITLE
Getting error on uploading file using put_page_blob_from_path

### ISSUE THREAD

**Issue by crwilcox** [Azure/azure-storage-python#9]
### Description:
Hi,
I got following error while uploading file as page blob-

azure/storage/blobservice.py\", line 1318, in put_page_blob_from_path
retry_wait)
IOError: close() called during concurrent operation on the same file object.

Thanks,
Vaibhav

#### @huguesv commented on 2015-04-14 23:08:56:
> Hi!  Is this something you can repro consistently?  Could you include the code I can use to repro it, including the size of the file you are trying to upload?

**Comment by jehine-MSFT** [comment]
Hello @vmksuw,

To follow up on Chris's question, are you still having this issue. Can you repro it consistently? Do you still need help?

Thanks!

**Comment by jehine-MSFT** [comment]
Closing this issue since we can't repro it. Please reopen this if you can help provide us with a repro.

Thanks!
