### ISSUE TITLE
querying table storage is extremely slow due to 1,000 entites limit

### ISSUE THREAD

**Issue by chanansh** [Azure/azure-storage-python#92]
I am trying to count how many rows I have and it takes ages. Much slower than Excel. According to the web, there is a way to query more than 1,000 entities at a time via [`AsTableServiceQuery`](http://stackoverflow.com/questions/18615673/how-to-get-more-than-1000-entities-from-an-azure-table-storage-query) but I cannot find it's Python equivalent. 
Currently I am doing something like:
```
field='field name'
data = table_service.query_entities('DetectionAlertsExportTableUnsent', select=field)
while hasattr(data, 'x_ms_continuation'):
    more_count += 1
    logging.debug('getting more data for the %d time', more_count)
    next_partition_key = data.x_ms_continuation['nextpartitionkey']
    next_row_key = data.x_ms_continuation['nextrowkey']
    more_data = table_service.query_entities('DetectionAlertsExportTableUnsent', select=field,
                                             next_partition_key=next_partition_key, next_row_key=next_row_key)
```

**Comment by jehine-MSFT** [comment]
Hello,

It's an expensive operation to iterate through all the rows in a table just to get a row count. You should review the following doc to help understand best practices for maximizing performance when querying our Table service:

https://azure.microsoft.com/en-us/documentation/articles/storage-performance-checklist/

The solution you mentioned that can query all rows in one call (even if there are more than 1000 rows) is not supported in our Python library at this time. There may be support for that using our .Net WCF client which leverages the OData library directly.

An alternative solution would be for you to keep a denormialized counter that tracks how many rows your table has and is updated after each insert and delete operation. That solution would be an O(1) operation as opposed to O(n).

**Comment by emgerner-msft** [comment]
>> The solution you mentioned that can query all rows in one call (even if there are more than 1000 rows) is not supported in our Python library at this time. There may be support for that using our .Net WCF client which leverages the OData library directly.

There is no way to query more than 1000 rows in one HTTP call. This is a service level choice.  AsTableServiceQuery processes the continuation tokens for you and may do many service calls. The convenience of following continuation tokens is something we plan to add in Python but this will not change anything performance-wise.

Given network time it's not surprising that querying the service is slower than excel for range queries. Like JC mentioned, take a look at the performance checklist, specifically at https://azure.microsoft.com/en-us/documentation/articles/storage-performance-checklist/#subheading30.

**Comment by emgerner-msft** [comment]
Closing as we haven't heard anything in more than a month and I think we've answered the question posed. Feel free to reopen with additional related comments or create a new issue for any other problems you've run into if necessary.
